graphql-dotnet/graphql-dotnet

- src/GraphQL/GraphQL.g4
GraphiQL starts up with a large comment at the top of the query.
Previously, if you had typed a query below the comments and executed it,
you would have received an "Unknown operation name:" error.
> Ignore comments

- src/GraphQL.Tests/GraphQL.Tests.csproj
- src/GraphQL.Tests/packages.config
I received a "Microsoft.Cci.Pdb.PdbDebugException: Unknown custom
metadata item kind: 7" error when performing a "Rebuild All" in Visual
Studio 2015 with Fixie.
The problem went away after upgrading to 1.0.0.29 and restarting Visual
Studio. I can now double click on the test in Test Explorer and it will
jump to the test where I can then use the built-in test runner.
> Upgrade Fixie to fix VS2015 Test Explorer issue

- src/GraphQL.Tests/Execution/Cancellation/CancellationTests.cs
- src/GraphQL.Tests/GraphQL.Tests.csproj
- src/GraphQL.Tests/QueryTestBase.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/ExecutionContext.cs
- src/GraphQL/Types/ResolveFieldContext.cs
This is an initial take on supporting cancellation, to address #16. 
It doesn't seem to be a big change at all, I felt that the `CancellationToken` only needed to be passed to the field resolvers for optional use and to `DocumentExecuter.ResolveField` to be checked. My reasoning is that they are the only points at which a long running async action may occur and all other  work takes a trivial amount of time.
I'm still working on tests around this.
> Cancellation Support

- src/GraphQL.Tests/GraphQL.Tests.csproj
- src/GraphQL.Tests/StarWars/StarWarsIntrospectionTests.cs
- src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs
- src/GraphQL/EnumerableExtensions.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/Introspection/SchemaMetaFieldType.cs
- src/GraphQL/Introspection/__Field.cs
- src/GraphQL/Language/GraphQLVisitor.cs
- src/GraphQL/Types/DateGraphType.cs
- src/GraphQL/Types/GraphType.cs
- src/GraphQL/Types/GraphTypesLookup.cs
- src/GraphQL/Utilities/SchemaPrinter.cs
Prints the shorthand schema syntax for a given schema.
```
var printer = new SchemaPrinter(new StarWarsSchema(...));
Console.WriteLine(printer.Print());
enum Episode {
NEWHOPE
EMPIRE
JEDI
}
interface Character {
id: String!
name: String
friends: [Character]
appearsIn: [Episode]
}
type Droid implements Character {
id: String!
name: String
friends: [Character]
appearsIn: [Episode]
primaryFunction: String
}
type Human implements Character {
id: String!
name: String
friends: [Character]
appearsIn: [Episode]
homePlanet: String
}
type Query {
hero: Character
human(id: String!): Human
droid(id: String!): Droid
}
```
You can also print the shorthand for introspection.
```
var schema = new Schema
{
Query = new ObjectGraphType
{
Name = "Root"
}
};
var printer = new SchemaPrinter(schema); …
```
> Add SchemaPrinter

- src/GraphQL.Tests/GraphQL.Tests.csproj
- src/GraphQL.Tests/Types/FloatGraphTypeTests.cs
- src/GraphQL/Types/FloatGraphType.cs
According to the GraphQL specification a Float type is a double precision floating point, so use a double to support the full range of values. Fixes #66.
> Make GraphQLFloat type correspond to double

- src/GraphQL.GraphiQL/Controllers/GraphQLController.cs
- src/GraphQL.Tests/GraphQL.Tests.csproj
- src/GraphQL.Tests/StarWars/StarWarsQuery.cs
- src/GraphQL.Tests/Types/QueryArgumentTests.cs
- src/GraphQL/Builders/ConnectionBuilder.cs
- src/GraphQL/Execution/ExecutionError.cs
- src/GraphQL/Execution/ExecutionResult.cs
- src/GraphQL/Execution/ExecutionResultJsonConverter.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/Types/QueryArgument.cs
* Added a serialization strategy to ExecutionResult to conform to
error spec
* Updated sample GraphQLController to return 400 status code on error
* Added GraphType constraint to ConnectionBuilder<,>.Argument
Issues: #73, #82
> Add serialization strategy for ExecutionResult

- src/GraphQL/Types/ObjectGraphType.cs
Needed for graphql-dotnet/conventions to avoid having to make a call to `Interface<TInterface>()` through reflection.
> Added ObjectGraphType.Interface(Type)

- src/GraphQL.Tests/Execution/EnumAsInputsTests.cs
- src/GraphQL.Tests/Execution/InputConversionTests.cs
- src/GraphQL.Tests/Execution/ResolveFieldContextTests.cs
- src/GraphQL.Tests/Execution/VariablesTests.cs
- src/GraphQL.Tests/GraphQL.Tests.csproj
- src/GraphQL/Language/GraphQLVisitor.cs
- src/GraphQL/ObjectExtensions.cs
- src/GraphQL/StringExtensions.cs
- src/GraphQL/Types/ResolveFieldContext.cs
* Fix issues when trying to cast between int/long in Argument<T>
* Fixed an issue where long values were not initialized properly in the
GraphQLVisitor
* Throw exception if argument doesn't exist
Github Issue: #103
> Fix issues with boxed value casting in Arguments

- src/GraphQL.Tests/Builders/FieldBuilderTests.cs
- src/GraphQL.Tests/Execution/VariablesTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/ObjectExtensions.cs
In DocumentExecuter.GetVariableValue the variables type's name was
retrieved. This stripped list and non-nullable information and made the
IsValidValue check fail.
This change instead gets the type via the GraphTypeFromType method. The
test executes_with_injected_input_variables is extended to cover the
scenario. The properly_parses_multiple_values_to_list does not demonstrate
a bug but is there for completeness.
Additionally GetArgument on context did not support IEnumerable as generic
parameter. This is fixed in ObjectExtensions and tested in
can_get_list_argument.
> Inject list input variables from query to field

- src/GraphQL.GraphiQL/Controllers/GraphQLController.cs
- src/GraphQL.Tests/Execution/Cancellation/CancellationTests.cs
- src/GraphQL.Tests/Execution/MutationTests.cs
- src/GraphQL.Tests/Execution/SchemaLifetimeTests.cs
- src/GraphQL/EnumerableExtensions.cs
- src/GraphQL/Execution/DocumentExecuter.cs
Explicitly call ConfigureAwait, in most cases the synchronization context is not needed.
I suggest installing something like [ConfigureAwaitFixer](https://visualstudiogallery.msdn.microsoft.com/07d8d8a4-f2cd-4350-aad8-751c33879d52).
> explicit ConfigureAwait calls

- README.md
- src/GraphQL.Tests/GraphQL.Tests.csproj
- src/GraphQL.Tests/Validation/UniqueFragmentNamesTests.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/Validation/DocumentValidator.cs
- src/GraphQL/Validation/Rules/UniqueFragmentNames.cs
Issue #10 
I noted this in the tests, but the column number is a bit different from qraphql-js. Their column number is the fragment name; the column number for this validation is "fragment". I wouldn't expect that to be a big deal for users, but it's a difference.
> Add unique fragment names validation rule

- src/GraphQL.Tests/Bugs/Bug138DecimalPrecisionTests.cs
- src/GraphQL.Tests/GraphQL.Tests.csproj
- src/GraphQL/Language/GraphQLVisitor.cs
* When FloatValue was updated to use double the GraphQLVisitor was
not updated to match.
Fixes #138
> Switch to double.Parse for FloatValue

- src/GraphQL.Tests/Types/DateGraphTypeTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/Language/IntValue.cs
- src/GraphQL/Types/DateGraphType.cs
This is done by introducing a `Language\DateTimeValue` class, avoiding the need to `.ToString()` DateTime objects in `DocumentExecuter.AstFromValue()`.
Also prevents round-tripping of DateTime objects in `DateGraphType`.
Fixes #139
> Retain Utc/Local information in provided DateTime argument values.

- README.md
- src/GraphQL.Tests/GraphQL.Tests.csproj
- src/GraphQL.Tests/Validation/NoUnusedFragmentsTests.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/Language/InlineFragment.cs
- src/GraphQL/Validation/DocumentValidator.cs
- src/GraphQL/Validation/Rules/NoUnusedFragments.cs
Issue #10 
Added `IHaveSelectionSet` to `InlineFragment`, which was required for the first test to pass, and matches the semantics of graphql-js.
> Added no unused fragments validation rule

- src/GraphQL.StarWars/StarWarsQuery.cs
- src/GraphQL.Tests/Bugs/Bug118SpacesInTypeNameTests.cs
- src/GraphQL.Tests/Bugs/Bug138DecimalPrecisionTests.cs
- src/GraphQL.Tests/Builders/ConnectionBuilderTests.cs
- src/GraphQL.Tests/Builders/FieldBuilderTests.cs
- src/GraphQL.Tests/Execution/EnumAsInputsTests.cs
- src/GraphQL.Tests/Execution/MutationTests.cs
- src/GraphQL.Tests/Execution/ResolveFieldContextTests.cs
- src/GraphQL.Tests/Execution/VariablesTests.cs
- src/GraphQL/Builders/ConnectionBuilder.cs
- src/GraphQL/Builders/FieldBuilder.cs
- src/GraphQL/Builders/ResolveConnectionContext.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/Introspection/__Type.cs
- src/GraphQL/Types/GraphType.cs
- src/GraphQL/Types/ResolveFieldContext.cs
This is my quick attempt at addressing #164
There are a few breaking hcanges here due to the nature of combining the two types. Some of them can be mitigated or undone if needed. 
Specifically I removed `WithObject` if favor of allowing `Field<TGraphType, TSourceType>`, This felt easier to me and works for both API's but it removes some functionality (see comments on the diff)
> Merge various `Resolve` context types

- src/GraphQL.Tests/Introspection/SchemaIntrospectionTests.cs
- src/GraphQL/Introspection/__InputValue.cs
- src/GraphQL/Resolvers/NameFieldResolver.cs
I was using introspection to get metadata on my input types so my React UI could change according to back-end specification and I encountered this bug.
The data is returned anyway (in the test), but there was an error in the `Errors` collection indicating a null reference exception when getting the description.
In `NameFieldResolver`, the `source` was the *type* `StringGraphType` and not an instance. I'm not too sure why or if it's normal, but it broke my use-case.
I'm not sure if the test is in the right place or my variables or the test schema, please comment and tell me what I can change!
> Add test and fix for weird description error on __type introspection.

- src/GraphQL.Tests/Errors/ErrorLocationTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/ExecutionContext.cs
- src/GraphQL/Execution/ExecutionError.cs
- src/GraphQL/Language/CoreToVanillaConverter.cs
This crashes Relay in https://github.com/facebook/relay/blob/17096c3f22fbd98d0b4ace26762917e6c6a54832/src/network-layer/default/RelayDefaultNetworkLayer.js#L185 since the line number is 0. The line is then undefined and `substr` fails with an undefined error.
From what I can tell, [DocumentExecuter](https://github.com/graphql-dotnet/graphql-dotnet/blob/b35e118f2d9e2a6154bb39498a55bf17d94af16a/src/GraphQL/Execution/DocumentExecuter.cs#L58) never has line or column on `SourceLocation` (I inspected the object in the debugger).
It seems to always be zero because of [this](https://github.com/graphql-dotnet/graphql-dotnet/blob/b35e118f2d9e2a6154bb39498a55bf17d94af16a/src/GraphQL/Language/CoreToVanillaConverter.cs#L305).
Here is a first draft of a fix. Is this right? 
I think my …
> Fix for "Location of errors is always line:0, column:0"

- src/GraphQL.Tests/Types/ObjectGraphTypeTests.cs
- src/GraphQL/Types/ObjectGraphType.cs
Using `IsSubclassOf()` will cause `Interface()` to throw an `ArgumentException` regardless of whether `type` implements the `IInterfaceGraphType` interface or not. Changed it to check for implemented interfaces instead.
> FIX: Unable to recognise interface using `IsSubclassOf()`

- src/GraphQL.Tests/Types/ObjectGraphTypeTests.cs
- src/GraphQL/Types/ObjectGraphType.cs
#212 fixed the non-generic version of `ObjectGraphType` but unfortunately there's some duplicated code.... Could the non-generic `ObjectGraphType` just derive from `ObjectGraphType<object>`?
Also fixed up the test, since the bug only gets hit when calling the `Interface(Type)` overload.
> Fix Interface(Type) for generic ObjectGraphType<>

- src/GraphQL/Instrumentation/MiddlewareResolver.cs
When the middleware resolver sees a faulted task, awaiting it would enter a loop and not report the underlying exception. This branch gets around that issue by re-throwing the reported task exception.
> Catch faulty tasks and rethrow exception on field resolution

- src/GraphQL.Tests/Execution/AstFromValueTests.cs
- src/GraphQL.Tests/Types/DecimalGraphTypeTests.cs
- src/GraphQL/GraphQLExtensions.cs
- src/GraphQL/Language/AST/IntValue.cs
- src/GraphQL/Types/DecimalGraphType.cs
DecimalGraphType break when used as inputs. This fixes the issue #251
> Add DecimalValue to the AST

- src/GraphQL.Tests/Bugs/Bug252ExecutorAppliesFIeldBuilderOnce.cs
- src/GraphQL/Execution/DocumentExecuter.cs
As discussed in the thread, move ApplyTo call into the schema initialization section.  Simple tests to count the number of times FieldMiddlewareBuilders.ApplyTo() is called over the lifetime of an executor/schema/builder.
> Bug 252 - reuse of schema causes stack overflow

- src/GraphQL/Resolvers/ExpressionFieldResolver.cs
Expression compilation is apparently expensive - this change alone yielded a ~10x speed improvement on my machine (a 15" MacBook Pro 2016) while testing the [DataLoader.StarWars](https://github.com/dlukez/dataloader-dotnet/tree/master/sample/DataLoader.StarWars) sample app.
> Compile and reuse resolver expression

- src/GraphQL.StarWars/StarWarsQuery.cs
- src/GraphQL/Resolvers/DelegateFieldModelBinderResolver.cs
- src/GraphQL/Resolvers/FuncFieldModelBinderResolver.cs
- src/GraphQL/Types/ComplexGraphType.cs
- src/GraphQL/Types/ResolveFieldContext.cs
Inspired by ASP.NET MVC model binder I added FuncFieldModelBinderResolver which inspects parameters of the resolver function, extracts them from the context arguments (by matching parameter name to argument name) and passes them to the resolver function. As a result instead of calling `context.GetArgument<string>("id")` you can just add a `string id` parameter to resolver function.
This is still work in progress but I wanted to get feedback from community before going too far with it. I find it useful because it allows to get rid of the magic strings in resolver function. The only downside is that you need to declare and intermediate variable for the resolver function before passing it as a resolver.
So what do you think ?
> [WIP ] Automatically extract and pass parameters from context to resolver

- docs/getting-started.md
Small doc change. Return `Task` and `Wait`ing on it. Otherwise, you have a chance to exit without finishing the entire execution, depending what `DocumentExecuter().ExecuteAsync` does.
> [Docs] Return Task and Wait on it

- src/GraphQL.Tests/Execution/VariablesTests.cs
- src/GraphQL/ObjectExtensions.cs
I've been trying to create a custom ScalarGraphType that would accept a JSON-encoded string, and output a deserialized object corresponding to that string, using JSON.NET. I was getting an error due to the fact that the `Conversions` class was trying to convert the value returned from the ScalarGraphType, even though there was no IConversionProvider registered for my custom type. I solved it by bypassing the attempt to convert when no provider is registered for the type.
> support variables for types that return custom objects

- src/GraphQL.Tests/Subscription/SubscriptionSchema.cs
- src/GraphQL.Tests/Subscription/SubscriptionTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/Resolvers/EventStreamResolver.cs
- src/GraphQL/Resolvers/IEventStreamResolver.cs
- src/GraphQL/Subscription/ISubscriptionExecuter.cs
- src/GraphQL/Subscription/ResolveEventStreamContext.cs
- src/GraphQL/Subscription/ResolveEventStreamResult.cs
- src/GraphQL/Subscription/SubscriptionExecuter.cs
- src/GraphQL/Subscription/SubscriptionExecutionResult.cs
- src/GraphQL/Types/EventStreamFieldType.cs
Provides a `SubscriptionExecuter` which allows subscribing to a source stream provided by the `EventStreamFieldType`. Returned stream is of type `IObservable<object>` allowing easy manipulation.
See the "unit tests": https://github.com/pekkah/graphql-dotnet/blob/features/subscription/src/GraphQL.Tests/Subscription/SubscriptionTests.cs
I'll be pushing out a separate NuGet/repo with the transport layer for Apollo Client compatibility after this makes it into the official GraphQL NuGet so I can just add it as an dependency.
> Subscription Executer

- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/GraphQLExtensions.cs
- src/GraphQL/Introspection/__Type.cs
- src/GraphQL/Types/InputObjectGraphType.cs
- src/GraphQL/Utilities/SchemaPrinter.cs
- src/GraphQL/Validation/TypeInfo.cs
This should allow strongly-typed classes to be used to define input types. It should continue to adhere to GraphQL spec as all added fields must be of ScalarGraphType or InputObjectGraphType.
Usage example:
```
public class MyClass
{
public int Id { get; set; }
public string RandomDescription { get; set; }
}
public class MyClassInputType : InputObjectGraphType<MyClass>
{
Field(x => x.Id);
Field(x => x.RandomDescription);
}
```
> Allow generic InputObjectGraphType for strongly-typed field definition

- src/GraphQL.Tests/StarWars/StarWarsFragmentTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Validation/Rules/PossibleFragmentSpreads.cs
The message was Key Object reference not set to an instance of an object."
Now it is "Unknown fragment \"unknown_fragment\"
> Wrong error message while referencing a unknown fragment

- src/GraphQL.Tests/Execution/AstFromValueTests.cs
- src/GraphQL/GraphQLExtensions.cs
- src/GraphQL/Language/AST/IValue.cs
- src/GraphQL/Language/AST/IntValue.cs
- src/GraphQL/Language/AST/NullValue.cs
- src/GraphQL/Language/AST/Variable.cs
- src/GraphQL/Types/IAstFromValueConverter.cs
- src/GraphQL/Types/Schema.cs
Addresses issue [458](https://github.com/graphql-dotnet/graphql-dotnet/issues/458)
I've tested this change in my organization's GraphQL API and our short and byte custom types work great.
> Added support for custom scalar types such as byte or short.

- src/GraphQL/Instrumentation/FieldMiddlewareBuilder.cs
If inner exception is thrown at this point - the original stack trace is lost.
By wrapping it into new exception the original stack trace is preserved
> Wrap inner exception during resolving

- src/GraphQL.Tests/Utilities/DateTimeOffsetTypeTests.cs
- src/GraphQL.Tests/Utilities/SchemaBuilderExecutionTests.cs
- src/GraphQL/Conversion/Conversions.cs
- src/GraphQL/Conversion/DateTimeOffsetConverter.cs
- src/GraphQL/ObjectExtensions.cs
That allows to pass `DateTimeOffset` type to methods marked with `[GraphQLMetadata]` attribute.
> Add converter for DateTimeOffset type

- src/GraphQL.GraphiQL/Controllers/GraphQLController.cs
Since GraphQL tool pass query parameter as an object, somehow this makes deserialization of query parameter failed as null.  Changing it JObject to guarantee success.
> Fix mutation failure when running with StarWar example project

- src/GraphQL/Execution/ExecutionResult.cs
- src/GraphQL/Execution/ExecutionResultJsonConverter.cs
- src/GraphQL/Instrumentation/Metrics.cs
- src/GraphQL/Instrumentation/PerfRecord.cs
In order to support the tracing proposed by https://github.com/apollographql/apollo-tracing there a few changes needed as far as i see it.
Firstly, the current time measurements in metrics is not precise enough. It is currently measured in milliseconds, but the spec expects nanoseconds.
Secondly, for things like apollo-tracing, apollo-cache-control, and other future extension points to work. There is a requirement to be able to expose an extension point in the result.
I've added this as a simple optional dictionary, that these types of extensions can choose to add to. The extensions will themselves be responsible to specify a JsonConverter in order to output expected JSON.
> Add ability to support things like apollo tracing

- src/GraphQL.Tests/Execution/ExecutionListenerTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Instrumentation/FieldMiddlewareBuilder.cs
- src/GraphQL/Instrumentation/MiddlewareResolver.cs
- src/GraphQL/Resolvers/FuncFieldResolver.cs
This addresses issue #508. All Tasks returned by resolvers are properly awaited. Any nested Tasks are unwrapped. 
I added a simple unit test to verify.
> Make sure Tasks from resolvers are properly awaited

- src/GraphQL/Execution/DocumentExecuter.cs
These fixes prevent thread starvation when processing a high number of graph queries that are running asynchronously. Will improve performance significantly under heavy load.
> Removed blocking of main thread. Passed CancellationToken into spawned threads

- .gitignore
- src/GraphQL.Tests/Extensions/GraphQLExtensionsTests.cs
- src/GraphQL/GraphQLExtensions.cs
I got an NRE in `GraphQL.Utilities.SchemaPrinter.ResolveName(IGraphType)` when *field of type [FieldType] must have a sub selection*. `resolve(type)` in `GraphQL.GraphQLExtensions.BuildNamedType` return `null`. In this case, I was expecting to see more relevan exception.
```
at GraphQL.Utilities.SchemaPrinter.ResolveName(IGraphType type) in C:\\Projects\\graphql-dotnet\\src\\GraphQL\\Utilities\\SchemaPrinter.cs:line 344\r\n
at GraphQL.Utilities.SchemaPrinter.ResolveName(IGraphType type) in C:\\Projects\\graphql-dotnet\\src\\GraphQL\\Utilities\\SchemaPrinter.cs:line 341\r\n
at GraphQL.Validation.ValidationContext.Print(IGraphType type) in C:\\Projects\\graphql-dotnet\\src\\GraphQL\\Validation\\ValidationContext.cs:line 158\r\n
at GraphQL.Validation.Rules.ScalarLeafs.Field(IGraphType type, …
```
> Throw exception when resolve delegate return null

- docs/src/getting-started.md
Query failed in Postman until `String` was changed to `String!`.
> Corrected type for $droidId

- src/GraphQL.Tests/StarWars/StarWarsSubFieldsTest.cs
- src/GraphQL/Execution/ExecutionHelper.cs
Fixed bug where the ResolveFieldContext.SubFields was null for ListGraphType items.
> Populate subfields for all graph types that have a SelectionSet. #547

- src/GraphQL.DataLoader.Tests/BatchDataLoaderTests.cs
- src/GraphQL.DataLoader.Tests/CollectionBatchLoaderTests.cs
- src/GraphQL/DataLoader/BatchDataLoader.cs
- src/GraphQL/DataLoader/CollectionBatchDataLoader.cs
- src/GraphQL/DataLoader/DataLoaderContextExtensions.cs
I found an issue with the `BatchDataLoader` and `CollectionBatchDataLoader`. If a key is requested in a batch, but not included in the results returned by the fetch delegate, it should return the default value or an empty enumerable. And this should be cached. 
I added unit tests for these scenarios and implemented the fixes.
> Fix issues with the DataLoaders and non-existent keys

- src/GraphQL.Tests/Utilities/SchemaBuilderExecutionTests.cs
- src/GraphQL/Reflection/AccessorFieldResolver.cs
Fix for issue #579.
`AccessorFieldResolver` was always attempting to resolve a target from its `_dependencyResolver` when asked to resolve a field value. Doing so loses context for the field accessor which is attempting to derive values from the `context.Source` in many cases.
It may be a naive fix, but I've altered it to check to see if `context.Source` is of the type declaring the field, if so, use the `context.Source` as the field accessor target, else resolve a new instance.
> Have AccessorFieldResolver use context.Source when appropriate

- src/GraphQL/GraphTypeRegistry.cs
- src/GraphQL/TypeExtensions.cs
Thoughts?
Proposing so the library doesn't have to worry about any other scalars than listed, but it'd be great if I didn't have to `ToString()` every time I have a Guid on the API.
Happy to touch up further to match project style and add tests, just wanted to get a rough implementation down before I forgot and moved on.
> Adds flexible type registry

- src/GraphQL.Tests/Execution/VariablesTests.cs
- src/GraphQL/Execution/ExecutionHelper.cs
When an argument is optional, has no default value specified, and it is not specified in the query, the arguments on the resolve context still contain the argument with a value of null.
This does not seem to manifest itself when using a nullable type such as `string`, so I added a test that uses `int`, which fails without the change.
When attempting to retrieve the value using `context.GetArgument`, an object reference exception is thrown because `context.HasArgument` returns true, so value resolving is attempted.
> Fix an issue causing unspecified optional arguments to have value

- src/GraphQL/Execution/ParallelExecutionStrategy.cs
Even though `ExecuteNodeAsync` calls `ThrowIfCancellationRequested`, the state machine wraps the exception and lets the `for` loop to finish before it unwraps on `Task.WhenAll`. In my code I terminate the query if it is taking too long to execute. The problem appears when all the objects are already created (and in my worst case it's ~5000) and we cancel. In this case we get 5000 exceptions.
What my fix does is it checks before each `ExecuteNodeAsync` is called. This way we don't create a bunch of tasks, which unwrap later.
>  Cancel executions before calling ExecuteNodeAsync

- appveyor.yml
- tools/tasks/dotnetPack.js
I think it could be useful for debugging purposes:
Added `--include-symbols` and `--include-source` flags to the main nuget package in order to get pdbs and sources available via the source server.
This will not affect the main package, it will just create a separate `symbols.nupkg` which will be pushed to the symbol server (See [docu](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack?tabs=netcore2x#description) for details)
I can't seem to find the logic which pushes to nuget.org, only to myget. Could you please help me out with that? In case you want to have this change of course.
> Include symbols for the nuget packages

- src/GraphQL.Tests/Bugs/NullableInputListTests.cs
- src/GraphQL/Execution/ExecutionHelper.cs
Handle issue raised by @amay in the [graphql-dotnet/conventions](https://github.com/graphql-dotnet/conventions) repository - null literals not treated properly for input lists:
https://github.com/graphql-dotnet/conventions/issues/73
> Bug fix - handle null list inputs

- src/GraphQL.Tests/Errors/ErrorCodeTests.cs
- src/GraphQL/Execution/ExecutionError.cs
- src/GraphQL/Execution/ExecutionResultJsonConverter.cs
We've been using this to more easily determine the reason for an error on the client side. E.g.,
instead of regex matching on the error message itself (which can even be localised), we can check `errors[*].code`.
Further we have enabled enrichment of errors by forwarding data that has been put into `Exception.Data` to the response.
- The error code is derived from the exception name; e.g., thrown `DatabaseQueryException`
results in an error code of `DATABASE_QUERY`.
- Any data included in a thrown exception (e.g., `Exception.Data`) gets put into `ExecutionError.Data` and consequently included in the serialised output.
The `Path` concept was also introduced in GraphQL.Conventions, but seems like that was been added to the main repo a while ago as well :) :+1:
> Add error code and data to ExecutionError

- src/GraphQL/Utilities/SchemaPrinter.cs
- src/GraphQL/Utilities/SchemaPrinterOptions.cs
* Fix printing of default input values of enum type
* Optional printing of descriptions
* Optional printing of deprecation reasons
(related PRs: graphql-dotnet/conventions#82)
> Fix SchemaPrinter bug + optional print options

- src/GraphQL/Execution/ExecutionError.cs
- src/GraphQL/Execution/InvalidValueException.cs
- src/GraphQL/Validation/ValidationError.cs
Newtonsoft.Json 11.0.1 [release notes](https://github.com/JamesNK/Newtonsoft.Json/releases/tag/11.0.1):
> Change - Types that implement ISerializable but don't have [SerializableAttribute] are not serialized using ISerializable
If someone will serialize exception, it will output `TargetSite` property, which has properties of type `Assembly`, etc. Result will be almost 10M per exception, you can use sample below to test.
````
using System;
using Newtonsoft.Json;
namespace Version11
{
class Program
{
static void Main()
{
try
{
throw new B("123");
}
catch (Exception e)
{
Console.WriteLine(JsonConvert.SerializeObject(e, new JsonSerializerSettings
{
Formatting = Formatting.Indented,
ReferenceLoopHandling = ReferenceLoopHandling.Ignore
}));
}
}
}
internal class B : Exception
{
public B(string …
```
> Add [Serializable] attribute to all exceptions.

- src/GraphQL/Builders/ResolveConnectionContext.cs
If the `first` and `last` properties are not set, `first` should default to the `defaultPageSize`. Right now, I have to write the following code for every `Connection`:
```
var first = context.First;
if (!context.First.HasValue && !context.Last.HasValue)
{
first = context.PageSize;
}
```
> First Should Return DefaultPageSize

- src/GraphQL/Builders/ConnectionBuilder.cs
The `ConnectionBuilder` was throwing exceptions the use of `before` when `first` or `after` were used. It also threw exceptions when `after` was used with `last` or `before`.
I can't see these restrictions in the [GraphQL Relay spec](https://facebook.github.io/relay/graphql/connections.htm#sec-undefined.PageInfo) but I could be wrong.
Using both `after` and `before` is used by Twitter when they add a `load more tweets` button:
1. Load some tweets.
2. User becomes inactive for a long period, not sure of the time Twitter uses.
3. User is active, load the latest tweets, then show a `load more tweets` button.
4. Clicking on `load more tweets` would load tweets `after` the latest tweets but `before` the older set.
> Allow before and after to be used together and with first or last

- src/GraphQL.Tests/Execution/InputConversionTests.cs
- src/GraphQL/ValueConverter.cs
When sending integer value instead of float, upon calling `GetArgument<float>` on ResolveFieldContext, we're getting `System.InvalidOperationException : Could not find conversion from System.Int32 to System.Double`.
This PR allows integers to be converted to floats.
> Add int to double conversion

- src/GraphQL.Tests/Utilities/TypeExtensionsTests.cs
- src/GraphQL/TypeExtensions.cs
Right now as a `ListGraphType` could be returned only a `List`. I want to be able to return `ICollection`, `IList`, `IEnumerable`, `IReadOnlyCollection` etc. as a `ListGraphType` I add some unit tests so we would be sure that everything works fine.
CC: @joemcbride
> Add support to return IEnumerable as a ListGraphType

- src/GraphQL.DataLoader.Tests/Stores/UsersStore.cs
- src/GraphQL/DataLoader/BatchDataLoader.cs
- src/GraphQL/DataLoader/DataLoaderContextExtensions.cs
DataLoader batches are currently required to return `Dictionary`, which is a bit rigid.
This changes it to `IDictionary`.
> Change return type of DataLoader batches to IDictionary instead of Dictionary

- src/GraphQL/Validation/Complexity/ComplexityAnalyzer.cs
The `ComplexityAnalyzer` is currently causing us issues intermittently due to it not being thread safe.
This PR reworks the class a little to make it thread-safe by passing around the context (complexity result, fragments and loop counter) in an instance of an inner class, so we don't have these are shared private members.
This relates to https://github.com/graphql-dotnet/graphql-dotnet/issues/280
> Make complexity analysis pass threadsafe

- src/GraphQL.Tests/Types/BooleanGraphTypeTests.cs
- src/GraphQL/Types/BooleanGraphType.cs
- src/GraphQL/ValueConverter.cs
> #606 boolean graph type not converting numerical string

- src/GraphQL.Tests/Types/InputObjectGraphTypeTests.cs
- src/GraphQL/Types/ComplexGraphType.cs
- src/GraphQL/Types/InputObjectGraphType.cs
> #587 inputobjectgraphtype referencing an objectgraphyype should throw specific error

- src/GraphQL/TypeExtensions.cs
- src/GraphQL/Utilities/GraphTypeInstanceRegistry.cs
- src/GraphQL/Utilities/GraphTypeTypeRegistry.cs
Fixes: #625 
* rename `TypeToGraphConverter` to a `GraphQLTypeTypeRegistry`
* move `TypeToGraphConverter` to `GraphQL.Utilities`
* rename function Convert to `Get` in `GraphQLTypeTypeRegistry` so it is coherent with function `Get` from `GraphQLInstanceRegistry`
CC: @joemcbride
> #625 rename GraphTypeRegistries and move them to the same location

- src/GraphQL.Tests/Builders/ConnectionBuilderTests.cs
- src/GraphQL.Tests/Types/ComplexGraphTypeTests.cs
- src/GraphQL/Builders/ConnectionBuilder.cs
- src/GraphQL/Builders/FieldBuilder.cs
- src/GraphQL/Types/ComplexGraphType.cs
- src/GraphQL/Utilities/FieldValidator.cs
> #475 when registering a field throw an error if the name doesn't match the spec

- src/GraphQL.Tests/Instrumentation/ApolloTracingTests.cs
- src/GraphQL/Instrumentation/ApolloTrace.cs
- src/GraphQL/Instrumentation/ApolloTracingExtensions.cs
- src/GraphQL/Instrumentation/InstrumentFieldsMiddleware.cs
Adds an extension method `EnrichWithApolloTracing` to `ExecutionResult` for adding a `tracing` extension in the [Apollo Tracing](https://github.com/apollographql/apollo-tracing) format, generated from the existing performance metrics. To get the necessary information for this, `InstrumentFieldsMiddleware` was modified to include the schema language-formatted name of the field's return type as well as the path to the field.
> generate Apollo Tracing report from execution metrics. fixes #381

- src/GraphQL.Tests/Instrumentation/FieldMiddlewareBuilderTests.cs
- src/GraphQL/Execution/ExecutionError.cs
I realize that there is no possibility to add Data to a `Data` field in an `ExecutionError` constructor explicitly. It could be set only via the Exception object. Since someone could use some `ResultType` with an `IError` which in fact doesn't have to be an `Exception` it is a little bit overhead to set an Error.Data via adding it like:
```csharp
var err = new ExecutionError("");
var err.Data.Add("key", "value");
var err.Data.Add("key1", "value");
var err.Data.Add("key2", "value");
var err.Data.Add("key3", "value");
```
so it would be more suitable to set "error data" via constructor like that:
```csharp
var errData = new Dictionary<string, object>();
var err = new ExecutionError("", errData);
```
this pr is a proposition if it doesn't align with how the library is intended to "look like" …
> Add possibility to set Data in ExecutionErrors ctor

- src/GraphQL.Tests/Validation/UniqueDirectivesPerLocationTests.cs
- src/GraphQL/GraphQLExtensions.cs
- src/GraphQL/Instrumentation/Metrics.cs
- src/GraphQL/Language/AST/Directives.cs
- src/GraphQL/Resolvers/NameFieldResolver.cs
- src/GraphQL/Types/ComplexGraphType.cs
- src/GraphQL/Types/EnumerationGraphType.cs
- src/GraphQL/Utilities/AstPrinter.cs
- src/GraphQL/Validation/TypeInfo.cs
A collection of minor non-breaking code tweaks that enhances the performance and scalability of graphql-dotnet significantly.
In particular, 92fc0a520ac920d9b3813ac3a4412bd4afa8dc5e improves service time of introspection queries on larger schemas by 30% by avoiding repeatedly new-ing an object thousands of times. The rest of the tweaks are simple things like reducing casting or avoiding reallocating objects in a loop.
Let me know if you've got any questions, and thanks for `graphql-dotnet` :)
> Performance enhancements

- docs2/site/docs/getting-started/introduction.md
The Query property has the string without the curly braces, which does not work and leads to an error as shown below,
```js
{
"errors": [
{
"message": "Syntax Error GraphQL (1:1) Unexpected Name \"hero\"\n1: hero { id name }\n   ^\n",
"code": "SYNTAX_ERROR"
}
]
}
```
> Getting error with the existing query structure

- src/GraphQL/IDependencyResolver.cs
currently if a type doesnt have a default constructor u get
```
System.MissingMethodException : No parameterless constructor defined for this object.
```
Note it doesnt tell u the type.
This pr changes the exception to 
```
System.Exception : Failed to call Activator.CreateInstance. Type: MyNamespace.MyType
---- System.MissingMethodException : No parameterless constructor defined for this object.
```
> wrap Activator.CreateInstance exception to provide more info

- docs2/site/docs/getting-started/installation.md
Not needed IMO since the latest release is the stable one
> Remove pre release installation instruction

- src/GraphQL/Execution/SubscriptionExecutionStrategy.cs
Not having the parent becomes an issue further down the chain, causing a NullRefException in InstrumentFieldsMiddleware.Resolve(), resulting in a null-object been sent to the subscribing client. This fixes that.
> Fixed issue in execution node for subscriptions

- src/GraphQL.Tests/Types/EnumGraphTypeTests.cs
- src/GraphQL/Types/EnumerationGraphType.cs
The default behavior of EnumGraphType<TEnum> converts the enum values to uppercase. This commit allows you to specify a custom behavior for changing case.
> Allow custom casing on inferred enum graph types

- src/GraphQL.DataLoader.Tests/QueryTestBase.cs
- src/GraphQL.Harness.Tests/SuccessResultAssertion.cs
- src/GraphQL.Harness/GraphQLMiddleware.cs
- src/GraphQL.Tests/BasicQueryTestBase.cs
- src/GraphQL.Tests/Introspection/IntrospectionResult.cs
- src/GraphQL.Tests/Introspection/SchemaIntrospectionTests.cs
- src/GraphQL.Tests/QueryTestBase.cs
- src/GraphQL.Tests/Utilities/SchemaBuilderExecutionTests.cs
- src/GraphQL.Tests/Utilities/SchemaBuilderTestBase.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/Http/DocumentWriter.cs
- src/GraphQL/Http/HttpResponseStreamWriter.cs
- src/GraphQL/Http/JsonArrayPool.cs
- src/GraphQL/Http/PooledByteResult.cs
- Added a new method to IDocumentWriter.
` Task WriteAsync(Stream stream, ExecutionResult value);`
- Marked the old method as obsolete
- Added implementation for DocumentWriter. 
**Note**: the StreamWriter can be a bottleneck here, since it doesn't use ArrayPool in default implementation (see https://github.com/dotnet/corefx/issues/23874, Asp.Net has it's own implementation https://github.com/aspnet/HttpAbstractions/blob/bcb7bcbb7a6461204f4cefd9848e2a782ebb0a6b/src/Microsoft.AspNetCore.WebUtilities/HttpResponseStreamWriter.cs). This can further improve the performance.
- Added an extension method for DocumentWriter that mimics the old behavior. After some thought, I've allowed encoding to be passed.
- Updates unit tests to use the extension method in place of now obsolete method.
- …
> Implemented #798: IDocumentWriter - added support writing to response stream directly.

- src/GraphQL.Tests/Types/SchemaTests.cs
- src/GraphQL/Types/GraphTypesLookup.cs
I ran into a problem after upgrading to v2.2.0+ where the input types was not being registered if there where multiple arguments and they have `ResolvedType` explicit specified. Only the first type was being registered but not the rest.
Not sure why this hasn't been a problem before.
> Fix input types not being registered when ResolvedType is specified

- src/GraphQL/Utilities/GraphTypeTypeRegistry.cs
usage
`
GraphQL.Utilities.GraphTypeTypeRegistry.Register<MyClrType, MyGraphType>();
`
and
`
GraphQL.Utilities.GraphTypeTypeRegistry.Get<MyClrType>();
`
> add Generic Version of Register and Get Method

- docs2/site/docs/getting-started/introduction.md
having an instance method of schema(e.g. Execute) taking the schema instance as argument is confusing. Why do I have to pass the schema instance twice( once as this and again as Schema property)
> Updateed introduction.md

- src/GraphQL.DataLoader.Tests/DataLoaderQueryTests.cs
- src/GraphQL.DataLoader.Tests/Models/Fake.cs
- src/GraphQL.DataLoader.Tests/QueryTestBase.cs
- src/GraphQL.DataLoader.Tests/Stores/IProductReviewsStore.cs
- src/GraphQL.DataLoader.Tests/Types/ProductReviewType.cs
- src/GraphQL.DataLoader.Tests/Types/QueryType.cs
- src/GraphQL/Execution/ParallelExecutionStrategy.cs
Based on the conversation in #889, I looked at how the `ParallelExecutionStrategy` could be improved upon. 
Currently it executes in steps where nodes are executed and then we wait for them all to complete before starting to execute the child nodes. This repeats until the edges of the graph are reached. 
The problem with this is that the currently executing nodes could finish at different times. If one node takes a long time, we have to wait for that node to complete before executing the child nodes of the nodes that have already completed. 
I made some changes so that we can start executing child nodes as soon as parent nodes complete. And this works with the DataLoader because `OnBeforeExecutionStepAwaitedAsync` is called at the appropriate times. If we can start executing child nodes …
> Optimize ParallelExecutionStrategy

- src/GraphQL/Types/DateGraphType.cs
- src/GraphQL/Types/DateTimeGraphType.cs
- src/GraphQL/Types/DateTimeOffsetGraphType.cs
- src/GraphQL/Types/DecimalGraphType.cs
- src/GraphQL/Types/UriGraphType.cs
since we already have the strong type value, there is no point doing the call to `ParseValue`. so less code and avoids some calls to `ValueConverter.ConvertTo`
> remove some redundant parse calls

- docs2/site/docs/guides/links.md
Fixing a small typo on the "links" page.
> Fix small typo ("in" → "on")

- src/GraphQL.Tests/Types/TimeSpanMillisecondsGraphTypeTests.cs
- src/GraphQL.Tests/Types/TimeSpanSecondsGraphTypeTests.cs
- src/GraphQL/Types/TimeSpanMillisecondsGraphType.cs
- src/GraphQL/Types/TimeSpanSecondsGraphType.cs
With timespans not being a supported type from the GraphQL side of things they are transported as a numeric value and converted in the library.  
When the library is parsing values into their fields it refers back to the AST where the value is an numeric value.  This currently fails as it expects a TimeSpan to have been passed which isn't the case.  The only conversion I can see is validation of the field value but this doesn't affect the value stored in the AST.
> Fix TimeSpan Parsing

- src/GraphQL.Tests/Execution/RegisteredInstanceTests.cs
- src/GraphQL.Tests/Introspection/IntrospectionResult.cs
- src/GraphQL.Tests/StarWars/StarWarsIntrospectionTests.cs
- src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs
- src/GraphQL/Types/GraphTypesLookup.cs
> fix UriGraphType registration and related failing test cases

- src/GraphQL.Tests/TypeExtensionsTests.cs
- src/GraphQL/TypeExtensions.cs
When using `AutoRegisteringObjectGraphType`, strings are being registered as non-nullable. This fixes this issue.
> IsNullable should include strings

- README.md
- src/GraphQL.Tests/Validation/SingleRootFieldSubscriptionsTests.cs
- src/GraphQL/Validation/DocumentValidator.cs
- src/GraphQL/Validation/Rules/SingleRootFieldSubscriptions.cs
> 999 validation rule subscription operations must have exactly one root field

- src/GraphQL.Tests/Validation/SingleRootFieldSubscriptionsTests.cs
- src/GraphQL/Validation/Rules/SingleRootFieldSubscriptions.cs
@joemcbride this is a public method. so good to fix for v3. do u want me to re-add the old method with an obsolete attribute?
> fix typos InvalidNumberOfRootFieldMessaage

- src/GraphQL/Validation/Rules/FieldsOnCorrectType.cs
given this is a public method. we cannot be certain that the input enumeration support multiple iterations. if they dont (or for some reason we change what is passed in), this would result in a "consumption and discard' bug
> fix some multi enumerations

- src/GraphQL/Language/CoreToVanillaConverter.cs
these are at best redundant, at worse make it difficult to debug issues in release mode
In debug mode, when we r running the solution locally, the debugs currently do not trigger. So changing them to casts will still protect against the same scenario.
In release mode the asserts are compiled out, and could result in a null ref exception
> remove debug asserts

- src/GraphQL.Tests/Types/EnumGraphTypeTests.cs
- src/GraphQL/Types/EnumerationGraphType.cs
Having an optional Description is a nice-to-have that makes integrating C# enums into GraphQL Enums more complete.
**Example usage:**
Enum:
```
[Flags]
public enum OrderStatuses {
[Description("Order was created")]
CREATED = 2,
[Description("Order is being processed")]
PROCESSING = 4,
[Description("Order is completed")]
COMPLETED = 8,
[Description("Order was cancelled")]
CANCELLED = 16,
[Description("Order was closed")]
CLOSED = 32
}
```
GraphQL Type:
` public class OrderStatusesEnum : EnumerationGraphType<OrderStatuses> { }`
> Added the ability to extract an optional DescriptionAttribute from the enum within the EnumerationGraphType<TEnum> constructor

- src/GraphQL.DataLoader.Tests/QueryTestBase.cs
- src/GraphQL.Harness/GraphQLSettings.cs
- src/GraphQL.Harness/GraphQLUserContext.cs
- src/GraphQL.Tests/BasicQueryTestBase.cs
- src/GraphQL.Tests/Execution/ExecutionListenerTests.cs
- src/GraphQL.Tests/QueryTestBase.cs
- src/GraphQL.Tests/Utilities/SchemaBuilderExecutionTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/ExecutionContext.cs
- src/GraphQL/Execution/ExecutionOptions.cs
change `ExecutionOptions.UserContext ` to be a `IDictionary<string,object>`
replaces https://github.com/graphql-dotnet/graphql-dotnet/pull/1037
> change user context to a dictionary

- src/GraphQL.StarWars/IoC/SimpleContainer.cs
- src/GraphQL.Tests/Bugs/Bug68NonNullEnumGraphTypeTests.cs
- src/GraphQL/GraphQLExtensions.cs
- src/GraphQL/GraphQLMetadataAttribute.cs
- src/GraphQL/ObjectExtensions.cs
- src/GraphQL/TypeExtensions.cs
- src/GraphQL/Types/ObjectGraphType.cs
- src/GraphQL/Types/UnionGraphType.cs
- src/GraphQL/Utilities/TypeConfig.cs
Remove unnecessary use of `GetTypeInfo()` because of netstandard2.0 only  (also see https://github.com/dotnet/corefx/issues/16305)
> No more GetTypeInfo()

- src/GraphQL/Execution/ExecutionErrors.cs
- src/GraphQL/Instrumentation/FieldMiddlewareBuilder.cs
- src/GraphQL/Language/AST/Arguments.cs
- src/GraphQL/Language/AST/Directives.cs
- src/GraphQL/Language/AST/Document.cs
- src/GraphQL/Language/AST/Fragments.cs
- src/GraphQL/Language/AST/Operations.cs
- src/GraphQL/Language/AST/SelectionSet.cs
- src/GraphQL/Language/AST/Variables.cs
- src/GraphQL/Types/ComplexGraphType.cs
- src/GraphQL/Types/EnumerationGraphType.cs
- src/GraphQL/Types/InterfaceGraphType.cs
- src/GraphQL/Types/ObjectGraphType.cs
- src/GraphQL/Types/QueryArguments.cs
- src/GraphQL/Types/Schema.cs
- src/GraphQL/Types/UnionGraphType.cs
- src/GraphQL/Utilities/TypeSettings.cs
Relates to #978.
Identifies at an earlier stage the situation when trying to add the `null` value to collections.
> Add null/duplicates checks for public API

- src/GraphQL.Tests/Builders/FieldBuilderTests.cs
- src/GraphQL/Builders/FieldBuilder.cs
- src/GraphQL/GraphQLExtensions.cs
- src/GraphQL/Types/FieldType.cs
- src/GraphQL/Types/GraphType.cs
- src/GraphQL/Types/QueryArgument.cs
- src/GraphQL/Utilities/MetadataProvider.cs
- fixes #1019
- avoid double metadata checking
- fixes potential NRE in MetadataProvider.HasMetadata
> Metadata for QueryArgument

- src/GraphQL/Types/ResolveFieldContext.cs
- src/GraphQL/Validation/DocumentValidator.cs
- src/GraphQL/Validation/ValidationContext.cs
The UserContext that is built by IUserContextBuilder.BuildUserContext is an IDictionary<string, object>. That should be reflected in some classes to make code more type safe and avoid tedious casting. Note: It changes an interface, IDocumentValidator, but I think it's ok given the recent change to IUserContextBuilder and the project being in some kind of preview state.
> Change the type of the UserContext-property in some places to IDictionary<string, object>

- src/GraphQL.Tests/Introspection/IntrospectionResult.cs
- src/GraphQL.Tests/Introspection/SchemaIntrospectionTests.cs
- src/GraphQL.Tests/Types/ComplexGraphTypeTests.cs
- src/GraphQL.Tests/Types/StringGraphTypeTests.cs
- src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs
- src/GraphQL/Introspection/__EnumValue.cs
- src/GraphQL/Types/StringGraphType.cs
* `__EnumValue` introspection `isDeprecated` field was defined as a `String` vs. `Boolean`
fixes #1177
> Ensures StringGraphType serializes values to strings

- src/GraphQL.Tests/Bugs/CamelCaseArgumentTest.cs
- src/GraphQL.Tests/Bugs/PascalCaseTests.cs
- src/GraphQL.Tests/Conversion/FieldNameConverterTests.cs
- src/GraphQL.Tests/Execution/Performance/ListPerformanceTests.cs
- src/GraphQL.Tests/Execution/Performance/StarWarsPerformanceTests.cs
- src/GraphQL.Tests/QueryTestBase.cs
- src/GraphQL/Conversion/CamelCaseFieldNameConverter.cs
- src/GraphQL/Conversion/DefaultFieldNameConverter.cs
- src/GraphQL/Conversion/IFieldNameConverter.cs
- src/GraphQL/Conversion/PascalCaseFieldNameConverter.cs
- src/GraphQL/Execution/ExecutionOptions.cs
- src/GraphQL/Types/GraphTypesLookup.cs
- src/GraphQL/Types/Schema.cs
- src/GraphQL/Validation/Rules/KnownArgumentNames.cs
Converters are stateless and can be reused.
> fieldnameconverter no longer allocates memory

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.approved.txt
- src/GraphQL.Tests/Bugs/Issue1152ExceptionDelegate.cs
- src/GraphQL.Tests/QueryTestBase.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/ExecutionContext.cs
- src/GraphQL/Execution/ExecutionOptions.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/Execution/UnhandledExceptionContext.cs
Move from `Func<>` to `Action<>` to get away from future method signature changes
> Better UnhandledExceptionDelegate

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.approved.txt
- src/GraphQL.Tests/Instrumentation/FieldMiddlewareBuilderTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Instrumentation/Metrics.cs
fixes #1324
I myself faced the problem of excessive memory consumption on one of my projects. Profiling and investigation led to the real culprit - `ConcurrentBag<T>`:
https://stackoverflow.com/questions/5353164/possible-memoryleak-in-concurrentbag
https://stackoverflow.com/questions/9256735/is-concurrentbag-cause-of-memory-leak
https://stackoverflow.com/questions/10850443/is-there-a-memory-leak-in-the-concurrentbagt-implementation
So just changing it to ordinary `List<T>` with simple locking. I think that there will be problems with such blocking, because adding to the list is almost instantaneous, and the lock design is hybrid and first makes the spinlock instead of putting the thread in the wait state.
> Remove ConcurrentBag<T> usage im Metrics in favor of List<T>

- src/GraphQL.Tests/Execution/RegisteredInstanceTests.cs
- src/GraphQL.Tests/Utilities/FederatedSchemaBuilderTests.cs
- src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs
- src/GraphQL/Utilities/SchemaPrinter.cs
Relates to ChilliCream/hotchocolate#890
Also see dotnet/corefx#15825
We personally faced such a problem on our projects. Our tests began to fail because the approved graphql schema was generated on a Windows (by developer) machine and the CI tests (deploy, introspection, etc.) run on Linux machine. It turned out a different type order in the schema.
> Fixes different sort order in SchemaPrinter on Windows and Linux

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.approved.txt
- src/GraphQL/Types/EnumerationGraphType.cs
- src/GraphQL/Types/FieldType.cs
- src/GraphQL/Types/GraphType.cs
- src/GraphQL/Types/IProvideMetadata.cs
- src/GraphQL/Types/QueryArgument.cs
- src/GraphQL/Utilities/MetadataProvider.cs
- src/GraphQL/Utilities/SchemaBuilderExtensions.cs
* Added `TType GetMetadata<TType>(string key, Func<TType> defaultValueFactory)` to IProvideMetadata to prevent unnecessary memory allocation
* Inherited all possible classes from default implementation MetadataProvider to remove identical implementation.
> Extend IProvideMetadata with default value factory

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.approved.txt
- src/GraphQL.Tests/Utilities/SchemaBuilderExecutionTests.cs
- src/GraphQL/SchemaExtensions.cs
removes an unnecessarily `.GetAwaiter().GetResult();`
> Obsolete SchemaExtensions.Execute

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.approved.txt
- src/GraphQL/GraphQL.csproj
- src/GraphQL/Utilities/SchemaBuilder.cs
- src/NuGet.config
Relates to graphql/graphql-spec#653
`SchemaBuilder` should fail to build incorrectly typed SDL. Otherwise, one could came across the problem of non-deterministic behavior. When constructing the schema, a second instance of the type (some input type in my case) was created and replaced the reference to this type already added in the type dictionary. This led to the fact that, depending on the type arrangement in the SDL, the `GraphTypesLookup.ApplyTypeReferences` method did not completely replace `GraphQLTypeReference`.  And this, in turn, led to runtime errors:
```
System.InvalidCastException: 'Unable to cast object of type 'GraphQL.Types.GraphQLTypeReference' to type 'GraphQL.Types.ScalarGraphType'.'
```
in `GraphQLExtensions.IsValidLiteralValue`.
> Check for redefinitions in SDL

- src/GraphQL.Tests/Types/QueryArgumentTests.cs
- src/GraphQL/Types/QueryArgument.cs
Relates to #1436 
By the way, two tests were written incorrectly. Fixed.
> Prevent use ObjectGraphType in QueryArgument

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.approved.txt
- src/GraphQL/Instrumentation/FieldResolverBuilderExtensions.cs
In #1442 middleware functionality was changed to create an instance of the middleware every time the middleware's resolve function was executed.  This PR fixes that behavior.
> Middleware regression fix - create middleware once

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.approved.txt
- src/GraphQL.Tests/Utilities/SchemaVisitorTests.cs
- src/GraphQL/Reflection/SinglePropertyAccessor.cs
- src/GraphQL/Types/ComplexGraphType.cs
- src/GraphQL/Types/Schema.cs
- src/GraphQL/Utilities/DeprecatedDirectiveVisitor.cs
- src/GraphQL/Utilities/DirectiveVisitorSelector.cs
- src/GraphQL/Utilities/ISchemaNodeVisitor.cs
- src/GraphQL/Utilities/SchemaBuilder.cs
- src/GraphQL/Utilities/SchemaBuilderExtensions.cs
Relates to #1451 
@joemcbride Do you mind these changes? I am still working on how to best implement the application of directives in GraphType first approach in #1451. However, it is obvious that there is a part that we will have to implement in any case. This PR adds directive support for all necessary elements of the schema. After merge, #1451 will be more focused on further changes.
> Add more directive locations for visitors

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.approved.txt
- src/GraphQL.StarWars/Types/CharacterInterface.cs
- src/GraphQL.Tests/StarWars/StarWarsIntrospectionTests.cs
- src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs
- src/GraphQL.Tests/Validation/ResultTypeValidationSchema.cs
- src/GraphQL.Tests/Validation/ValidationSchema.cs
- src/GraphQL/GraphQLExtensions.cs
- src/GraphQL/Types/InterfaceGraphType.cs
- src/GraphQL/Types/ObjectGraphType.cs
Also fixes `friendsConnection` field type and some tests. Regression in #995.
This PR fixes the problem of mismatching field types in interface implementations. I came across this problem when I wanted to add GraphQL Playground. It was a long time ago and I did not understand why Playground refuses to work. Now I managed to take a closer look at the problem. It turned out that the server returned an invalid introspection response, and the SPA application validated it and displayed an error in the console. At the same time, neither the schema nor the docs were displayed as if the server was not responding to the request at all.
> Add interface match check

- src/GraphQL.Tests/Introspection/IntrospectionResult.cs
- src/GraphQL.Tests/StarWars/StarWarsIntrospectionTests.cs
- src/GraphQL/Introspection/__InputValue.cs
fixes #1055
fixes #1386
After making this change, GraphQL Playground began to correctly display arguments for which the default value is not set, that is, it stopped adding `="null"` in introspection response.
Before:
```
"defaultValue": "null"
```
After:
```
"defaultValue": null
```
> Fix for null default value for field arguments

- src/GraphQL/GraphQLExtensions.cs
EnumerationGraphType inherits from ScalarGraphType so the second "is" is redundant
> remove  || namedType is EnumerationGraphType

- README.md
- docs2/site/docs/getting-started/altair-graphql.md
- docs2/site/sitemap.yml
Added [Altair GraphQL Client](https://altair.sirmuel.design/) usage to the docs.
> Added Altair GraphQL Client usage to docs

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.approved.txt
- src/GraphQL/Types/IResolveFieldContext.cs
- src/GraphQL/Types/ResolveFieldContext.cs
I suggest that IResolveFieldContext.Arguments be of type `IDictionary<string, object>` rather than `Dictionary<string, object>`, similar to the SubFields property.
Note: this PR will need to be updated if/when #1500 is pulled (or vice versa).
> Use IDictionary for IResolveFieldContext.Arguments

- README.md
- docs2/site/docs/getting-started/authorization.md
- docs2/site/docs/getting-started/malicious-queries.md
Some time ago, I began to consider options for how it is more convenient to provide api diff between major versions. I even started writing my own utility for this, although I was looking for ready-made solutions. As a result, I settled on the fact that the simplest and cheapest solution would be to give a link to this wonderful site - https://www.fuget.org
> Add notes about backward compatibility and link to api diff, fix typos

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/Execution/ParallelExecutionStrategy.cs
This small change reduces an allocation per _synchronous_ resolver.  Note that some of the performance benefits may be lost with the updated DataLoader code, unfortunately.
```
// * Summary *
BenchmarkDotNet=v0.12.0, OS=Windows 10.0.18362
Intel Core i7-7740X CPU 4.30GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.1.101
[Host]     : .NET Core 3.1.1 (CoreCLR 4.700.19.60701, CoreFX 4.700.19.60801), X64 RyuJIT
DefaultJob : .NET Core 3.1.1 (CoreCLR 4.700.19.60701, CoreFX 4.700.19.60801), X64 RyuJIT
*** BEFORE ***
|        Method |        Mean |    Error |   StdDev |    Gen 0 |   Gen 1 | Gen 2 | Allocated |
|-------------- |------------:|---------:|---------:|---------:|--------:|------:|----------:|
| Introspection | 1,509.92 us | 9.103 us | 8.070 us | 207.0313 | 76.1719 …
```
> Change ExecuteNodeAsync to return Task

- src/GraphQL/Execution/ExecutionOptions.cs
- src/GraphQL/Execution/IProvideUserContext.cs
Moving the xml comment from ExecutionOptions.UserContext to IProvideUserContext.UserContext
Intellisense will pick up the comment within ExecutionOptions so there is no need to duplicate the comment
Also provides the same xml comment to field resolvers, etc.
> Add xml comments to IProvideUserContext

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL/Types/ISchema.cs
- src/GraphQL/Types/Schema.cs
Shouldn't `IDisposable` be implemented on `Schema`, rather than `ISchema`?  It's not like `ISchema` is expected to hold any unmanaged references, so implementing `IDisposable` at all seems questionable.
Ok to merge or close.
> Move IDisposable from ISchema to Schema

- src/GraphQL.DataLoader.Tests/SimpleDataLoaderTests.cs
Occassionally appveyor fails testing due to SimpleDataLoaderTests.Operation_Can_Be_Cancelled
See: https://ci.appveyor.com/project/graphql-dotnet-ci/graphql-dotnet/builds/30927760
This is due to the wrong order of execution of the threads of testing, probably due to server load.  This increases the time limit for a successful test from 200ms to 5 sec.  It also configures `Task.Delay` to immediately return if the task is canceled (which it should be canceled after 5ms), so it actually runs faster in most instances (since it would wait a fixed 200ms previously).
> Increase appveyor testing reliability

- src/GraphQL/Execution/ExecutionOptions.cs
- src/GraphQL/SchemaExtensions.cs
- src/GraphQL/Types/ISchema.cs
- src/GraphQL/Types/Schema.cs
@sungam3r Please review. In particular, the comments for `RegisterValueConverter` and `FindValueConverter`, as I do not know how that would be used.  Perhaps a short example would be fitting.  Would this be for a custom date/time formatter?  But then wouldn't you simply implement a custom `ScalarFieldType` for bi-directional conversion?
Note that #1537 and #1549 will both slightly affect these comments, but this PR is based off the current `master` branch.  If we pull this PR first, I'll update #1549 - or vice versa.
The comment from `Schema.Filter` was removed so that it inherits the comments from `ISchema.Filter`.  Also, the `Schema` class was set to clone the comment from the `ISchema` interface.
> Add xml comments to ISchema

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL/ResolveFieldContextExtensions.cs
- src/GraphQL/Types/ResolveFieldContext.cs
- src/GraphQL/Types/ResolveFieldContextAdapter.cs
I'd like to make `ResolveFieldContextExtensions.As` public, as I have a need for it in one of my projects.  I can of course duplicate the entire `ResolveFieldContextAdapter` into my own project, but if it's okay, I'd like to simply make the method public.
> Make ResolveFieldContextExtensions.As public

- docs2/site/docs/getting-started/dependency-injection.md
- docs2/site/docs/getting-started/field-middleware.md
- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL.Harness/CountFieldMiddleware.cs
- src/GraphQL.Harness/GraphQLMiddleware.cs
- src/GraphQL.Harness/Startup.cs
- src/GraphQL.Tests/Bugs/Bug252ExecutorAppliesFIeldBuilderOnce.cs
- src/GraphQL.Tests/Instrumentation/FieldMiddlewareBuilderTests.cs
- src/GraphQL/Execution/ExecutionOptions.cs
- src/GraphQL/Execution/IDocumentExecuter.cs
- src/GraphQL/Execution/IExecutionStrategy.cs
- src/GraphQL/Execution/IProvideUserContext.cs
- src/GraphQL/Instrumentation/FieldMiddlewareBuilder.cs
- src/GraphQL/Instrumentation/FieldMiddlewareBuilderExtensions.cs
- src/GraphQL/Instrumentation/FieldResolverBuilderExtensions.cs
- src/GraphQL/Instrumentation/IFieldMiddleware.cs
- src/GraphQL/Instrumentation/IFieldMiddlewareBuilder.cs
- src/GraphQL/Instrumentation/InstrumentFieldsMiddleware.cs
- src/GraphQL/Resolvers/AsyncFieldResolver.cs
- src/GraphQL/Resolvers/FuncFieldResolver.cs
- src/GraphQL/Resolvers/IFieldResolver.cs
- src/GraphQL/Resolvers/NameFieldResolver.cs
- src/GraphQL/Types/ISchema.cs
- src/GraphQL/Types/Schema.cs
Fixes #1020 
Requires changes in server project: `InstrumentFieldsMiddleware` must be registered in DI now.
@Shane32 You might be interested. You had a PR #1443 that was not merged. It was an attempt to improve Field Middlewares though without all DI stuff. It so happened that on our projects there was a need to use middleware with dependencies, so I returned to this issue. As it turned out, adding this feature was not so difficult.
@joemcbride Please review this and update the site with the documentation.
> Add DI support for Field Middleware, IFieldMiddleware interface

- src/GraphQL/Execution/DocumentExecutionListener.cs
Added very basic comments for this interface. See changed files.
I might suggest that `IDocumentExecutionListener<T>` inherit from `IDocumentExecutionListener`.  Since the infrastructure only supports the latter interface, it is basically required for any implementation.  If you agree I can make that change also, or do so in a separate PR.  For now I just let it alone.
> Add basic xml comments to IDocumentExecutionListener

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL/Types/Schema.cs
Somehow I didn't see this in my last review, but now Schema.Services points to ... nothing
> Remove Schema.Services

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL.Tests/Execution/ExecutionListenerTests.cs
- src/GraphQL/DataLoader/DataLoaderDocumentListener.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/DocumentExecutionListener.cs
- src/GraphQL/Execution/ExecutionContext.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/Execution/IExecutionContext.cs
- src/GraphQL/Execution/SubscriptionExecutionStrategy.cs
With this change, more meta data about the execution is exposed, in particular `ExecutionErrors` can be useful, if one wants a service to be able to report multiple errors, and add errors without throwing.
It is a breaking change though, as it changes the interface.
> Expose ExecutionContext through the IDocumentExecutionListener

- src/GraphQL/Execution/ExecutionContext.cs
The applicable comment already exists in both IExecutionContext and ExecutionOptions
> Remove extra xml comment in ExecutionContext.cs

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL.StarWars/StarWarsSchema.cs
- src/GraphQL.Tests/Files/PetComplex.graphql
- src/GraphQL.Tests/Introspection/IntrospectionResult.cs
- src/GraphQL.Tests/Introspection/SchemaIntrospection.cs
- src/GraphQL.Tests/Utilities/SchemaBuilderExecutionTests.cs
- src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs
- src/GraphQL/Execution/ExecutionContext.cs
- src/GraphQL/Introspection/SchemaMetaFieldType.cs
- src/GraphQL/Language/AST/Directive.cs
- src/GraphQL/Types/ISchema.cs
- src/GraphQL/Types/Schema.cs
- src/GraphQL/Utilities/SchemaBuilder.cs
http://spec.graphql.org/draft/#sec-Schema-Introspection : 
```graphql
type __Schema {
description: String   <---
types: [__Type!]!
queryType: __Type!
mutationType: __Type
subscriptionType: __Type
directives: [__Directive!]!
}
```
GraphQL Playground, GraphiQL, Voyager, Altair - everything works fine with these changes.
> Add Schema.Description property from draft spec

- src/GraphQL/Execution/ExecutionResult.cs
These are mostly adaptations of xml comments in `ExecutionOptions`, `IExecutionContext` or `IResolveFieldContext`.  Since the use case by implementations is to typically read these values, the comments were adapted in that vein.
> Add xml comments to ExecutionResult

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL.NewtonsoftJson/ExecutionResultContractResolver.cs
- src/GraphQL/Execution/ExecutionResult.cs
I ran into an error when serializing `class MyExecutionResult : ExecutionResult { ... }` led to `OutOfMemoryException` since custom converter for `ExecutionResult` was not used because of strict condition inside `ExecutionResultContractResolver`. Then serializer started to serialize all properties from `ExecutionResult`. I wanted to use the copy constructor, but I could not, because it is `protected`. So it is `public` now too.
> Support for serialize custom ExecutionResult

- src/GraphQL.Tests/Bugs/ScalarsInputTest.cs
- src/GraphQL/GraphQLExtensions.cs
- src/GraphQL/Types/Fields/FieldType.cs
- src/GraphQL/Types/QueryArgument.cs
- src/GraphQL/Validation/Rules/ArgumentsOfCorrectType.cs
http://spec.graphql.org/June2018/#sec-Required-Arguments :
> Arguments can be required. An argument is required if the argument type is non‐null **and does not have a default value**. Otherwise, the argument is optional.
Given such a schema
```graphql
type Query
{
a: A
}
type A
{
field(p: Int! = 10): SomeType
}
```
and  query
```graphql
{
a {
field { <---- no args
...
}
}
}
```
`ValidationError` occures: `$"Expected \"{ofType.Name}!\", found null."`
> Fix validation rule for required arguments

- docs2/site/docs/getting-started/errors.md
Updated documentation to include information on `ExecutionOptions.ThrowOnUnhandledException` for the Error Handling section.
Adding example usage for both `ExecutionOptions.ThrowOnUnhandledException` and `ExecutionOptions.UnhandledExceptionDelegate`.
Added in a note that if `ExecutionOptions.ThrowOnUnhandledException` is true, it will pass on the exception before `ExecutionOptions.UnhandledExceptionDelegate` is invoked.
Linked Issue #777
> Add documentation for ThrowOnUnhandledException

- src/GraphQL.Tests/Bugs/ScalarsInputTest.cs
- src/GraphQL.Tests/QueryTestBase.cs
- src/GraphQL.Tests/Types/DecimalGraphTypeTests.cs
- src/GraphQL/Language/CoreToVanillaConverter.cs
- src/GraphQL/Types/Scalars/DecimalGraphType.cs
- src/GraphQL/Utilities/SchemaBuilder.cs
Now `decimal` takes priority over `BigInteger`. Also `DecimalGraphType` now can parse from `BigIntValue` literal.
> bugfix: Expected type "Decimal", found 39614081257132168796771975168.

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL.Tests/Bugs/BubbleUpTheNullToNextNullable.cs
- src/GraphQL.Tests/DocumentWriterTests.cs
- src/GraphQL.Tests/Errors/ErrorLocationTests.cs
- src/GraphQL/Execution/ExecutionError.cs
- src/GraphQL/Execution/ExecutionNode.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/Execution/SubscriptionExecutionStrategy.cs
- src/GraphQL/Instrumentation/ApolloTracingExtensions.cs
- src/GraphQL/ResolveFieldContext/IResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ReadonlyResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContextAdapter.cs
Currently the `errors[].path` property returned in the graphql response returns strings to indicate positions within an array.  According to the spec it should return numbers.  This fixes that error.
See https://spec.graphql.org/June2018/#sec-Errors
> This field should be a list of path segments starting at the root of the response and ending with the field associated with the error. Path segments that represent fields should be strings, and path segments that represent list indices should be 0‐indexed integers. If the error happens in an aliased field, the path to the error should use the aliased name, since it represents a path in the response, not in the query.
>
> For example, if fetching one of the friends’ names fails in the following query:
> ```
> {
>   hero(episode: $episode) {
> …
```
> Fix errors.path property to return numbers for list indexes

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL/Language/AST/Directives.cs
This was one of the few (only?) exceptions to the AST being
full read-write, and prevented some processing of docs to
sanitize directives, for example, prior to execution.
There was really no apparent reason to introduce this limitation
at the AST level, so we implement `ICollection<Directive>` to
allow full mutation of this collection.
> Allow full manipulation of Directives in AST node

- src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs
- src/GraphQL/Utilities/SchemaPrinter.cs
Co-Authored-By: Maria Miller <mariajmiller@users.noreply.github.com>
Enum values like `RED` were getting schema-printed as `"RED"` when used as default values, which is wrong. The fix is to just move the check of whether it is an enum first when printing.
> Stop escaping enum literals when used as default values

- src/GraphQL.Tests/Bugs/Issue1189.cs
- src/GraphQL/Reflection/SingleMethodAccessor.cs
When using schema-first approach, resolvers are dynamically dispatched. This causes any exception raised inside resolver logic to be wrapped in a TargetInvocationException. As a result ExecutionError mechanism doesn't work properly (as described in #1189)
> fix issue #1189

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL.Tests/Execution/ExecutionNodeTests.cs
- src/GraphQL/Execution/ExecutionNode.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/Execution/SubscriptionExecutionStrategy.cs
- src/GraphQL/ResolveFieldContext/IResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ReadonlyResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContextAdapter.cs
According to [the GraphQL spec](http://spec.graphql.org/June2018/#sec-Errors) the path in an error, when a field is aliased, should include the alias and not the name. Specifically:
```
If the error happens in an aliased field, the path to the error should use the aliased name, since it represents a path in the response, not in the query.
```
My first thought was to simply change `ExecutionNode.Path` to prefer the alias since it is only used to populate error paths, however I quickly decided that could be a breaking change for consumers that are accessing the path in their resolvers and are expecting the "query" path.
So instead I've implemented a new `ResponsePath` property that is now used to populate `ExecutionError.Path`. It's also exposed in the `ResolveFieldContext` for any …
> Make sure error paths prefer aliases

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL/Validation/ValidationResult.cs
At the moment in consuming code I have to have
```
var result = new ValidationResult(Enumerable.Empty<ValidationError>());
```
> make SuccessfullyValidatedResult public

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL.Tests/Bugs/Bug1205VeryLongInt.cs
- src/GraphQL.Tests/Bugs/Bug1699InvalidEnum.cs
- src/GraphQL.Tests/Execution/VariablesTests.cs
- src/GraphQL/Execution/ExecutionHelper.cs
- src/GraphQL/Execution/ExecutionNode.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/Execution/InvalidValueException.cs
- src/GraphQL/GraphQLExtensions.cs
- src/GraphQL/Types/Scalars/ScalarGraphType.cs
- src/GraphQL/Validation/Rules/ProvidedNonNullArguments.cs
Fixes #1699 
Fixes both input and output serialization coercion to meet these graphql requirements:
Scalars:
> 3.5 Result Coercion: A GraphQL server, when preparing a field of a given scalar type, must uphold the contract the scalar type describes, either by coercing the value or producing a field error if a value cannot be coerced or if coercion may result in data loss.
> 3.5 Input Coercion: If a GraphQL server expects a scalar type as input to an argument, coercion is observable and the rules must be well defined. If an input value does not match a coercion rule, a query error must be raised.
Enums:
> 3.9 Result Coercion: GraphQL servers must return one of the defined set of possible values. If a reasonable coercion is not possible they must raise a field error.
> 3.9 Input Coercion: …
> Raise errors upon failed coercion to meet graphql specifications

- src/GraphQL.Tests/Errors/UnhandledExceptionTests.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
This allows `UnhandledExceptionDelegate`s to return custom messages, just like throwing an `ExecutionError` directly from a resolver can already do.
> Prevent unnecessary wrapping of ExecutionErrors in ExecutionStrategy

- src/GraphQL.Tests/Bugs/Bug1699InvalidEnum.cs
- src/GraphQL.Tests/Execution/VariablesTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/InvalidValueException.cs
Right now all unhandled `Exception`s are wrapped inside an `ExecutionError` within `DocumentExecuter` (unless `ThrowOnUnhandledException` is set).  This prevents additional data, such as location or codes, from being returned either from library code or from the `UnhandledExceptionDelegate`.  This can be seen in the `Input_Enum_InvalidEnum_Variable` test, as it can only return the location information with this change.
> Prevent unnecessary wrapping of ExecutionErrors in DocumentExecuter

- src/GraphQL.Tests/Errors/QueryErrorTests.cs
- src/GraphQL/Execution/GraphQLDocumentBuilder.cs
- src/GraphQL/GraphQL.csproj
Right now graphql syntax errors are passed through directly from the graphql parser library.  The error messages are multi-line and the location information is embedded inside the message string rather than attached to the graphql error response.  This PR parses the exception message from the graphql-parser library into the proper fields for the graphql response.
~~Note that this PR requires #1763 in order to work properly, as currently ExecutionErrors are wrapped, dropping location information.~~ Merged
The returned error code will not change with this PR (currently SYNTAX_ERROR).  In a separate PR, I will look at updating all of the error codes, including this one, that should be returned.
> Add location information to query parsing errors

- src/GraphQL.Tests/Bugs/Bug1769.cs
- src/GraphQL/Execution/DocumentExecuter.cs
With these changes, if `options.Query` or `options.Schema` is `null`, an exception is raised back to the caller, rather than a graphql result being returned.  This also validates that the constructor parameters are valid.
If `options.Query` is an empty string or only consists of whitespace, a ~~`SYNTAX_ERROR`~~ `NO_OPERATION` graphql error result is returned to the caller.
> Add checks for null DocumentExecuter parameters

- src/GraphQL.Tests/Bugs/Bug1770.cs
- src/GraphQL.Tests/Bugs/Bug1772.cs
- src/GraphQL/Execution/DocumentExecuter.cs
Right now, if `options.OperationName` is invalid, the `DocumentExecuter` treats this as a query error, whereas this should be an `InvalidOperationException` thrown back to the caller, since it is an invalid option passed to the `DocumentExecuter`.
However, the document needs to be parsed before this option can be validated, and document parsing takes place within the `try { }` block.  I propose we select one of the following options:
1. Throw `InvalidOperationException`, and let this get caught by the unhandled exception processing - for instance, throwing immedaitely when `ThrowOnUnhandledException` is true, or wrapping it when it is false.
2. Create a small amount of additional logic to throw this exception directly to the caller.
Another option (option 3) would be to leave it as a …
> Change DocumentExecuter to throw for invalid operation name

- src/GraphQL.Tests/Types/SchemaTests.cs
- src/GraphQL/Types/GraphTypesLookup.cs
All of the errors changed below should never occur during normal operation, but would represent a schema error. They can only occur while the `GraphTypesLookup` class is being built (during `Schema.Initialize`).  Any information contained within these errors could potentially represent privileged information.
These exceptions have been changed to a native exception type. If one of these exceptions were to occur, they would be wrapped into an ExecutionError inside the DocumentExecuter with a code that represents the inner error (since the schema is initialized during document execution, if it has not yet been initialized).
> Cleanup GraphTypesLookup exceptions

- src/GraphQL.Tests/Bugs/Bug1781.cs
- src/GraphQL.Tests/CoreToVanillaConverterTests.cs
- src/GraphQL/Language/CoreToVanillaConverter.cs
As indicated in #1778 I went back to review the last `ExecutionError` within `CoreToVanillaConverter`.  I determined that it is impossible for an `ASTNodeKind.IntValue` to produce a value that cannot be cast to a `BigInteger`.  So I changed that exception to an `InvalidOperationException`, as if it was triggered, it would indicate a parsing problem within graphql-parser.
Then I reviewed `ASTNodeKind.FloatValue` and determined that for values beyond the range of a `decimal`, an overflow/parsing exception can occur.  This I fixed by using `decimal.TryParse`.  I also determined that values beyond the range of a `double` are simply interpreted as `Infinity` and `-Infinity` so there is no possibility of a failed conversion.  I added a test (which would have previously failed) to verify this …
> CoreToVanillaConverter cleanup

- src/GraphQL.Tests/Bugs/BubbleUpTheNullToNextNullable.cs
- src/GraphQL.Tests/Bugs/Bug1699InvalidEnum.cs
- src/GraphQL.Tests/Bugs/Bug1773.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
Right now, after a resolver returns a value, the infrastructure attempts to convert it to the correct graph type.  For example, if the resolver returns a string of "1" for an IntGraphType, the infrastructure attempts to convert it to the number 1.  When this fails, the conversion throws an exception of FormatException which can be handled and logged by the UnhandledExceptionDelegate.  It is then wrapped in a generic "failure resolving {fieldname}" message, which is accurate - this is a server side code issue.  The ExecutionError also properly includes a code of "FORMAT" in this case.
However, if the resolver returns a string of "test" for an enumeration graph type (where "test" is invalid), the infrastructure throws a ExecutionError.  This cannot be caught or logged by the …
> Clarify and unify conversion exceptions from resolver returned values

- src/GraphQL.Tests/Bugs/Bug1156.cs
- src/GraphQL.Tests/Bugs/Bug1772.cs
- src/GraphQL/Execution/DocumentExecuter.cs
The `DocumentExecuter` does not properly hide unhandled exception error messages, as unhandled errors that occur within a field resolver do.  This fixes that.  Inner exception codes are still returned as always.
> DocumentExecuter does not properly hide unhandled exception error messages

- src/GraphQL.Tests/Bugs/BubbleUpTheNullToNextNullable.cs
- src/GraphQL.Tests/Execution/AbstractTypeTests.cs
- src/GraphQL.Tests/Types/NonNullGraphTypeTests.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
In #1773 somehow I changed the exceptions thrown during `ExecutionStrategy.SetArrayItemNodes` but not `ExecutionStrategy.ValidateNodeResult`.  These represent the same basic changes - invalid results from the resolver (e.g. null for a non-null field) throw an `InvalidOperationException` rather than an `ExecutionError`.
> Update ValidateNodeResult to throw InvalidOperationException

- src/GraphQL.Tests/Bugs/BubbleUpTheNullToNextNullable.cs
- src/GraphQL.Tests/Bugs/Bug1205VeryLongInt.cs
- src/GraphQL.Tests/Bugs/Bug1699InvalidEnum.cs
- src/GraphQL.Tests/Bugs/Bug1773.cs
- src/GraphQL.Tests/Bugs/Issue1189.cs
- src/GraphQL.Tests/Errors/ErrorExtensionsTests.cs
- src/GraphQL.Tests/Errors/ErrorLocationTests.cs
- src/GraphQL.Tests/Execution/AbstractTypeTests.cs
- src/GraphQL.Tests/Types/NonNullGraphTypeTests.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/Execution/SubscriptionExecutionStrategy.cs
* Changes `Error trying to resolve {node.Name}.` to `Error trying to resolve field '{node.Name}'.`, and same for subscriptions
* Changes `Subscriber not set for field {node.Field.Name}` to `Subscriber not set for field '{node.Field.Name}'.`
* Changes `Could not subscribe to field '{node.Field.Name}' in query '{context.Document.OriginalQuery}'` to include period at end
> Change default field resolver message

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL/Instrumentation/ApolloTracingExtensions.cs
apollo trace doesnt use operation. https://github.com/apollographql/apollo-tracing  so remove a redundant parameter
> remove Operation from ApolloTrace

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL.Tests/Bugs/Bug1769.cs
- src/GraphQL/Execution/DocumentError.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/ExecutionHelper.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/Execution/GraphQLDocumentBuilder.cs
- src/GraphQL/Execution/InvalidOperationError.cs
- src/GraphQL/Execution/InvalidValueError.cs
- src/GraphQL/Execution/InvalidVariableError.cs
- src/GraphQL/Execution/NoOperationError.cs
- src/GraphQL/Execution/SyntaxError.cs
- src/GraphQL/Execution/UnhandledError.cs
- src/GraphQL/Validation/ValidationError.cs
* Add abstract `DocumentError`, which inherits `ExecutionError` and has these implementations:
* `NoOperationError` (code `NO_OPERATION`)
* `InvalidOperationError` (code `INVALID_OPERATION`)
* `SyntaxError` (code `SYNTAX_ERROR`)
* `InvalidVariableError` (renamed from `InvalidValueException`; unchanged code `INVALID_VALUE`)
* `ValidationError` (code depends on which validation rule failed)
* Add `UnhandledError`, which inherits from `ExecutionError`, which is created when an unhandled error occurs.  No additional code is set for this error type; only the inner exception's codes are returned.
By convention, errors that inherit from `ExecutionError` now all end with the word `Error`, and regular exceptions end with `Exception`.
See #1768 
I also changed this error message: "Cannot execute …
> Update exception types

- src/GraphQL.Tests/Errors/UnhandledExceptionTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
When setting `UnhandledExceptionContext.ErrorMessage` during an error caught in the `DocumentExecuter`, the error message is now overridden as it should be.
Added tests to verify this both for `DocumentExecuter` and `ExecutionStrategy`.
> Support UnhandledExceptionContext.ErrorMessage within DocumentExecuter

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL.Tests/Execution/ResolveFieldContextTests.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContextExtensions.cs
I propose to delete `ResolveFieldContextExtensions.TryAsyncResolve` from the main GraphQL library.  It is only used by `ResolveFieldContextTests.cs`, and seems a bit useless otherwise.  Also, the logic is designed for tests: if an error occurs and an exception handler was specified, it will completely ignore the exception (not adding it to the list of document errors), and call the exception handler with the list of errors from the context, returning a `TResult` from the exception handler.  This logic is obviously useful only to a test.
> Remove ResolveFieldContextExtensions.TryAsyncResolve

- src/GraphQL.Harness/GraphQLMiddleware.cs
Although there currently is no sample within the Harness sample project demonstrating scoped services, I feel that a proper demonstration of typical integration with Asp.Net Core should set the `RequestServices` property based on `HttpContext.RequestServices`.  Then people that use cut & paste from the `Harness` sample will already have the proper configuration for scoped services in their project, matching what's shown in the documentation.
> Set RequestServices in Harness sample

- src/GraphQL/Types/Scalars/DateGraphType.cs
No functional change.  Tests already validate everything needed - for example, that it returns a DateTime.Kind of DateTimeKind.Utc.
> Eliminate double conversion of date within DateGraphType

- appveyor.yml
I think it's time to suppress the build when we change the documentation only.
> Try to skip build on changes in docs

- src/GraphQL.DataLoader.Tests/BatchDataLoaderTests.cs
- src/GraphQL.DataLoader.Tests/GraphQL.DataLoader.Tests.csproj
- src/GraphQL.Tests/Bugs/Bug138DecimalPrecisionTests.cs
- src/GraphQL.Tests/Types/BooleanGraphTypeTests.cs
- src/GraphQL.Tests/Types/ObjectGraphTypeTests.cs
- src/GraphQL.Tests/Utilities/SchemaBuilderTestBase.cs
- src/GraphQL/Language/CoreToVanillaConverter.cs
Fixes tests with .Net Core 2.1 LTS and .Net Framework 4.8 due to the following:
- System.Text.Json does not properly deserialize floating point numbers in prior versions of .Net Core - it has rounding errors, not sure why.  The broken test was actually testing serialization, which works just fine in prior versions.
- Some native exception messages have changed over the different framework versions
- Parsing overflowed floating point values changed in .Net Core 3.1 (bug fix for prior .Net Core versions)
> Fixes tests for .Net Core 2.1 LTS and .Net Framework 4.8

- src/GraphQL.Tests/Execution/Cancellation/CancellationTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
Right now, if a request is canceled, pending async operations get caught as an `OperationCanceledException` and passed to the `UnhandledExceptionDelegate`.
Then when the next node is attempting to be resolved, the cancellation token is checked and thrown back to the `DocumentExecuter`, which then runs the `UnhandledExceptionDelegate` a second time and serializes a response.
This code change makes it so that when an operation is cancelled, the `OperationCanceledException` is immediately rethrown back to the caller of the `DocumentExecuter` -- no unhandled exception delegates are called, and no `ExecutionResult` is returned.
Without this change, the `UnhandledExceptionDelegate` often runs twice when a pending document is canceled.  With typical database logging code in the delegate, this …
> Rethrow canceled operations properly; do not call unhandled exception delegate

- docs2/site/docs/getting-started/errors.md
The error codes were not showing up properly due to markdown; see revisions
> Fix error docs: underscores not visible

- docs2/site/docs/getting-started/mutations.md
Changed resolver to provider in mutation example as it read misleading to me at first. I see provider being injected and another variable name is then used to resolve the services called resolver.
> Misleading variable name in example

- src/GraphQL.Tests/Bugs/Bug1699InvalidEnum.cs
- src/GraphQL.Tests/Types/EnumGraphTypeTests.cs
- src/GraphQL/Types/Scalars/EnumerationGraphType.cs
See #1832 and #1835 
Given:
```csharp
public enum IsSet
{
NotSet = 0,
Set = 1
}
```
Since C# does not consider `IsSet.NotSet` to equal `0`, an `EnumerationGraphType` must add values based on the enumeration member.  For example:
```csharp
public class AssignmentStateEnumType  : EnumerationGraphType {
public AssignmentStateEnumType()
{
//this does not work
AddValue(name: "NotAssigned", description: "There is no assignment", value: 0);
AddValue(name: "Assigned", description: "There is an assignment", value: 1);
//this is correct
AddValue(name: "NotAssigned", description: "There is no assignment", value: IsSet.NotSet);
AddValue(name: "Assigned", description: "There is an assignment", value: IsSet.Set);
}
}
```
~~This did work in prior versions of `GraphQL.NET`.~~  This PR ~~reverts~~ …
> Enhancement: allows enumeration members to be specified by underlying value

- src/GraphQL.Tests/Validation/ValidationCodeTests.cs
- src/GraphQL/Builders/ConnectionBuilder.cs
- src/GraphQL/DataLoader/BatchDataLoader.cs
- src/GraphQL/DataLoader/DataLoaderContextExtensions.cs
- src/GraphQL/EnumerableExtensions.cs
- src/GraphQL/Execution/DocumentError.cs
- src/GraphQL/Execution/ExecutionError.cs
- src/GraphQL/Execution/ExecutionOptions.cs
- src/GraphQL/Execution/IDocumentExecuter.cs
- src/GraphQL/Execution/IExecutionStrategy.cs
- src/GraphQL/Execution/InputsExtensions.cs
- src/GraphQL/Execution/InvalidVariableError.cs
- src/GraphQL/Execution/UnhandledError.cs
- src/GraphQL/Instrumentation/FieldMiddlewareBuilderExtensions.cs
- src/GraphQL/LightweightCache.cs
- src/GraphQL/ObjectExtensions.cs
- src/GraphQL/Reflection/ReflectionHelper.cs
- src/GraphQL/ResolveFieldContext/IResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ReadonlyResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContextExtensions.cs
- src/GraphQL/Resolvers/IFieldResolver.cs
- src/GraphQL/SchemaExtensions.cs
- src/GraphQL/TypeExtensions.cs
- src/GraphQL/Types/Scalars/EnumerationGraphType.cs
Mostly everything was one of the following:
* Incorrect xml comment syntax (missing member)
* Missing some, but not all, xml comments for parameters
* Shortcut syntax for methods and properties
> Fix all build warnings except CS1591 warnings

- docs2/site/docs/getting-started/databases.md
Join Monster for .NET is a query planner and batch data fetcher between GraphQL and SQL built for GraphQL for NET.
Adding it to the list as it could be valuable to people using GraphQL for NET.
> Adds Join Monster .NET to the list of tools to use with GraphQL.NET

- .github/workflows/build-artifacts-code.yml
It seems the key must be added to the `dotnet nuget push` command.  (Tested in my fork.)  One of my other projects did not require this here as it was configured with the `actions/setup-dotnet` command as described in the documentation.  No idea why it is required here.  Perhaps the `Directory.Build.props` file's `<clear/>` is messing with it.
> Fix package upload workflow

- .github/workflows/pr-tests-code.yml
Version `1.7.1` of the GitHub `actions/setup-dotnet` workflow contains the ability to configure multiple .NET SDKs for a test run.  This PR removes the hack previously necessary to be able to run tests against multiple versions of .NET Core.
> Update for setup-dotnet workflow changes

- .github/workflows/build-artifacts-code.yml
- src/Directory.Build.props
This configures merged PRs to automatically publish nuget packages to GitHub Packages
This would be effective for both master and develop branches.  Version numbers will be different because `Directory.Build.props` contains a different version prefix for each.
- master branch: `3.0.0-preview.{build}`
- develop branch `4.0.0-preview.{build}`
Where `{build}` is incremented automatically with every execution of this GitHub Action.
> Publish merged PRs as nuget packages to GitHub Packages

- src/GraphQL.Tests/Bugs/BugAliasedInputFieldInList.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContextExtensions.cs
> Fix for aliased list arguments

- docs2/site/docs/guides/migration3.md
Creating this PR to fixed the link for Dataloader documentation in Migration Guide [v2 ->v3]
> Update Migration 2-> 3 doc for the Dataloader link

- docs2/site/docs/guides/migration4.md
- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL.StarWars/GraphQL.StarWars.csproj
- src/GraphQL.StarWars/StarWarsSchema.cs
- src/GraphQL/Utilities/ServiceProviderExtensions.cs
The majority of things consuming will already reference `Microsoft.Extensions.DependencyInjection.Abstractions`. Which means ServiceProviderExtensions regularly causes type conflicts when using as an extension method
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0121	The call is ambiguous between the following methods or properties: 
'GraphQL.Utilities.ServiceProviderExtensions.GetRequiredService<T>(System.IServiceProvider)' and 
'Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<T>(System.IServiceProvider)'	
```
So this PR makes ServiceProviderExtensions internal
replaces #1929
> make ServiceProviderExtensions internal

- .github/workflows/test-code.yml
- .github/workflows/test-documentation.yml
With this change, both code and documentation build checks (which are in different workflows) will create a common "buildcheck" status which can be set in the branch protection options.
I imagine we want to turn off the old branch protection option (set for appveyor) and change to the 'buildcheck' status, which is triggered by either the `test-code.yml` or `test-documentation.yml` workflows.
Current configuration:
> Add common status check for build checks

- .github/workflows/publish-code.yml
- https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
- https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files
> Remove set-env from workflow

- .github/workflows/test-code.yml
With this change, a failed execution step will still cause the 'buildcheck' status to report.  So, if someone changes both code and docs in a single PR, and the docs pass (reporting a successful 'buildcheck' status), and the code fails, the failed code run will report a failed 'buildcheck' status, preventing the PR from being merged.
> Fix code test workflow to always report buildcheck status

- src/Directory.Build.props
- src/GraphQL.Tests/Files/CustomSubscription.graphql
- src/GraphQL.Tests/Utilities/SchemaBuilderExecutionTests.cs
- src/GraphQL/Utilities/SchemaBuilder.cs
Before this fix all subscription fields were created as `FieldType` (not `EventStreamFieldType`) if subscription root type has custom name != 'Subscription'.
> Fix issue with custom subscription name

- src/GraphQL.Tests/Types/ComplexGraphTypeTests.cs
- src/GraphQL/Builders/ConnectionBuilder.cs
- src/GraphQL/Builders/FieldBuilder.cs
- src/GraphQL/Types/Composite/ComplexGraphType.cs
- src/GraphQL/Types/Fields/FieldType.cs
- src/GraphQL/Types/GraphTypesLookup.cs
- src/GraphQL/Types/QueryArgument.cs
- src/GraphQL/Types/QueryArguments.cs
- src/GraphQL/Utilities/NameValidator.cs
Closes #1840 
The purpose of this PR is the following:
1. Allow invalid field and argument graphql names prior to schema initialization (not currently allowed)
2. Apply NameConverter to field and argument names during schema initialization (already exists)
3. Validate that the updated names are valid during schema initialization (currently does not happen)
The purpose of this PR is NOT:
1. Code cleanup / consolidation
2. Allow invalid field / argument names in an intialized schema
> Move ValidateName calls after NameConverter is applied

- docs2/site/docs/migrations/migration3.md
Creating this PR to fix the link for FAQ documentation in Migration Guide [v2 ->v3]
> Update the Link for FAQ in Migration 2-> 3

- .github/workflows/build-artifacts-code.yml
- src/GraphQL/Types/GraphTypesLookup.cs
This is regression. I found it while migrating on 3.1.2. No time to write tests but I can reproduce the bug with simple example.
Change StarWarsSchema.cs adding new directive
```c#
using System;
using GraphQL.Types;
using GraphQL.Utilities;
namespace GraphQL.StarWars
{
public class StarWarsSchema : Schema
{
public StarWarsSchema(IServiceProvider serviceProvider)
: base(serviceProvider)
{
Query = serviceProvider.GetRequiredService<StarWarsQuery>();
Mutation = serviceProvider.GetRequiredService<StarWarsMutation>();
RegisterDirective(new LinkDirective());
Description = "Example StarWars universe schema";
}
}
public class LinkDirective : DirectiveGraphType
{
public LinkDirective() : base("link", new[] { DirectiveLocation.FieldDefinition, DirectiveLocation.Object, DirectiveLocation.Interface …
```
> Fix type registration for directive args

- src/GraphQL.Benchmarks/GraphQL.Benchmarks.csproj
- src/GraphQL.StarWars/GraphQL.StarWars.csproj
- src/GraphQL.StarWars/IoC/SimpleContainer.cs
- src/GraphQL.Tests/Bugs/BugWithCustomScalarsInDirective.cs
- src/GraphQL.Tests/MsDiContainer.cs
- src/GraphQL.Tests/QueryTestBase.cs
- src/GraphQL.Tests/StarWars/StarWarsTestBase.cs
- src/GraphQL/Utilities/SchemaBuilder.cs
fixes #1977
You can comment out two lines in `GraphTypesLookup` to see that test fails
```c#
foreach (var arg in directive.Arguments)
{
if (arg.ResolvedType != null)
{
lookup.AddTypeIfNotRegistered(arg.ResolvedType, ctx);  <-----------------------------------
arg.ResolvedType = lookup.ConvertTypeReference(directive, arg.ResolvedType);
}
else
{
lookup.AddTypeIfNotRegistered(arg.Type, ctx); <-----------------------------------
arg.ResolvedType = lookup.BuildNamedType(arg.Type, ctx.ResolveType);
}
}
```
> Test for custom scalars in directives

- src/GraphQL/ObjectExtensions.cs
- src/GraphQL/Reflection/SingleMethodAccessor.cs
This fixes two bugs:
- When using `SingleMethodAccessor`, exceptions are unwrapped but stack traces are not retained.
- When using the `ToObject` extension method (for instance, within `TryGetArgument`), constructor exceptions are not unwrapped.
> Retain stack traces and unwrap constructor exceptions

- src/Directory.Build.props
- src/GraphQL/Types/QueryArgument.cs
```c#
if (!(type is ScalarGraphType inputType))
throw new ArgumentOutOfRangeException(nameof(type), $"Must provide Input Type, cannot use: {type}");
```
->
```
System.ArgumentOutOfRangeException: 'Must provide Input Type, cannot use: __GraphQLTypeReference '
```
on
```
productId: Long! = 0
```
because of
```c#
public object DefaultValue
{
get => _defaultValue;
set
{
if (!(ResolvedType is GraphQLTypeReference))
_ = value.AstFromValue(null, ResolvedType); // HACK: https://github.com/graphql-dotnet/graphql-dotnet/issues/1795
_defaultValue = value;
_defaultValueAST = null;
}
}
```
> Fix schema first issue - custom scalar with default value as GraphQLTypeReference!

- src/GraphQL.ApiTests/GraphQL.SystemTextJson.approved.txt
- src/GraphQL.NewtonsoftJson/ExecutionResultJsonConverter.cs
- src/GraphQL.SystemTextJson/ExecutionResultJsonConverter.cs
To reproduce just throw exception in the first line of `ChatSubscriptions.cs`:
```c#
private IObservable<Message> Subscribe(IResolveEventStreamContext context)
{
throw new Exception("test");           //  <----------------------------------------
var messageContext = context.UserContext.As<MessageHandlingContext>();
var user = messageContext.Get<ClaimsPrincipal>("user");
string sub = "Anonymous";
if (user != null)
sub = user.Claims.FirstOrDefault(c => c.Type == "sub")?.Value;
return _chat.Messages(sub);
}
```
and then query
```graphql
subscription
{
messageAdded
{
content
}
}
```
Result: 
```
System.Text.Json.JsonException: 'A possible object cycle was detected which is not supported. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 0.' …
```
> Fix serialization of SubscriptionExecutionResult for System.Text.Json

- src/GraphQL.Benchmarks/GraphQL.Benchmarks.csproj
- src/GraphQL.StarWars/GraphQL.StarWars.csproj
- src/GraphQL.SystemTextJson/GraphQL.SystemTextJson.csproj
- src/GraphQL.Tests/Bugs/Bug138DecimalPrecisionTests.cs
- src/GraphQL/GraphQL.csproj
```
Warning	NETSDK1138	The target framework 'netcoreapp3.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.	GraphQL.SystemTextJson	C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets	28	
```
I suggest that we just change the patch version. `GraphQL.SystemTextJson` is already multitargeted for `netstandard2.0` so even old clients (netcoreapp3.0 as well) can continue to consume its bits.
> Retarget System.Text.Json to netcoreapp3.1

- .github/labeler.yml
- .github/workflows/label.yml
- docs2/site/docs/migrations/migration3.md
- src/Directory.Build.props
- src/GraphQL.ApiTests/GraphQL.NewtonsoftJson.approved.txt
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL/GraphQLExtensions.cs
- src/GraphQL/Types/IGraphType.cs
- src/GraphQL/Types/IProvideMetadata.cs
- src/GraphQL/Types/ISchema.cs
- src/GraphQL/Utilities/MetadataProvider.cs
@Shane32 Formally it is breaking change since I added a new requirement to `ISchema`. But I don't know anymore if it's worth worrying about this kind of change and postponing it until the next major version. See https://github.com/graphql-dotnet/server/pull/470#issuecomment-739498710
> ISchema inherits IProvideMetadata

- src/Directory.Build.props
- src/GraphQL.Tests/Bugs/ScalarsInputTest.cs
- src/GraphQL.Tests/Types/FloatGraphTypeTests.cs
- src/GraphQL/Conversion/ValueConverter.cs
- src/GraphQL/Types/Scalars/BooleanGraphType.cs
- src/GraphQL/Types/Scalars/DateGraphType.cs
- src/GraphQL/Types/Scalars/DateTimeGraphType.cs
- src/GraphQL/Types/Scalars/DateTimeOffsetGraphType.cs
- src/GraphQL/Types/Scalars/DecimalGraphType.cs
- src/GraphQL/Types/Scalars/EnumerationGraphType.cs
- src/GraphQL/Types/Scalars/FloatGraphType.cs
- src/GraphQL/Types/Scalars/IdGraphType.cs
- src/GraphQL/Types/Scalars/LongGraphType.cs
- src/GraphQL/Types/Scalars/StringGraphType.cs
- src/GraphQL/Types/Scalars/TimeSpanMillisecondsGraphType.cs
- src/GraphQL/Types/Scalars/TimeSpanSecondsGraphType.cs
- src/GraphQL/Types/Scalars/UriGraphType.cs
Fixes #2047 . Also fixes bug when `FloatGraphType.Value` cannot be casted to `float` even when fractional part was specified.
I decided to remove all `Convert.To` calls and use the `checked` operator explicitly. First, this is how our intentions are more clearly expressed. Secondly, it turned out that we left unchecked context (C# uses unchecked by default) in some places. Examples:
```
Register<sbyte, byte>(value => (byte)value);
Register<sbyte, ulong>(value => (ulong)value);
```
I didn't add tests for all cases, because it is very expensive. I became convinced that some existing tests started failing when I changed `Convert.To` calls to explicit cast operator. So I added `checked` in every line with downcast.
> Unify scalar conversions

- src/GraphQL.Tests/Types/ULongGraphTypeTests.cs
- src/GraphQL/Introspection/__EnumValue.cs
- src/GraphQL/Types/Scalars/BigIntGraphType.cs
- src/GraphQL/Types/Scalars/BooleanGraphType.cs
- src/GraphQL/Types/Scalars/ByteGraphType.cs
- src/GraphQL/Types/Scalars/DateGraphType.cs
- src/GraphQL/Types/Scalars/DateTimeGraphType.cs
- src/GraphQL/Types/Scalars/DateTimeOffsetGraphType.cs
- src/GraphQL/Types/Scalars/DecimalGraphType.cs
- src/GraphQL/Types/Scalars/EnumerationGraphType.cs
- src/GraphQL/Types/Scalars/FloatGraphType.cs
- src/GraphQL/Types/Scalars/GuidGraphType.cs
- src/GraphQL/Types/Scalars/IdGraphType.cs
- src/GraphQL/Types/Scalars/IntGraphType.cs
- src/GraphQL/Types/Scalars/LongGraphType.cs
- src/GraphQL/Types/Scalars/SByteGraphType.cs
- src/GraphQL/Types/Scalars/ShortGraphType.cs
- src/GraphQL/Types/Scalars/StringGraphType.cs
- src/GraphQL/Types/Scalars/TimeSpanMillisecondsGraphType.cs
- src/GraphQL/Types/Scalars/TimeSpanSecondsGraphType.cs
- src/GraphQL/Types/Scalars/UIntGraphType.cs
- src/GraphQL/Types/Scalars/ULongGraphType.cs
- src/GraphQL/Types/Scalars/UShortGraphType.cs
- src/GraphQL/Types/Scalars/UriGraphType.cs
Also fixes a bug:
- `ULongGraphType` cannot parse integer literals greater than `long.MaxValue` and less than or equal to `ulong.MaxValue`.
> XML comments for scalar graph types

- .github/workflows/test-code.yml
Problem started to occur around 12/20/2020.  See https://github.com/actions/virtual-environments/issues/1090#issuecomment-748432535 .  See https://www.hossambarakat.net/2020/06/24/fix-error-NU1101/ .  Fixed by adding Nuget.config file (automatically via the workflow).
- This is now occurring in `master` and `develop` branches.
- It is not due to code changes; rerunning old build check workflows now results in an error
- The build-artifacts and publish workflows are not affected as they already create a Nuget.config file within them (tested).
- It is not caused by installing both 2.1 and 3.1 SDKs, and the order of side-by-side SDK installation does not matter.
Once this PR is merged, `master` needs to be merged into `develop`, and from there into any open PRs.
> Fix build process

- .github/workflows/label.yml
- src/GraphQL.Tests/Types/DecimalGraphTypeTests.cs
- src/GraphQL/Language/CoreToVanillaConverter.cs
Inspired by https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/984.
Resolves old TODO with `decimal.GetBits`.
> DecimalValue check does not allocate memory

- docs2/site/docs/migrations/migration4.md
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.Tests/Bugs/Bug138DecimalPrecisionTests.cs
- src/GraphQL/AuthorizationExtensions.cs
- src/GraphQL/Execution/SerialExecutionStrategy.cs
See https://github.com/graphql-dotnet/server/issues/293 and especially https://github.com/graphql-dotnet/server/issues/293#issuecomment-740469302 .I believe it would be correct to provide a base API for declaration of authorization requirements in the main project. In this case, the implementation will remain in the corresponding separate repositories.
> Extension methods to configure authorization requirements for GraphQL elements: types, fields, schema.

- docs2/site/docs/migrations/migration4.md
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL/LightweightCache.cs
`GetKey` isn't implemented and doesn't override a member.
`First` is not used and does not seem to fulfill a purpose.
Targeting `develop` of course.
> Remove LightweightCache.GetKey and .First

- docs2/site/docs/migrations/migration4.md
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL/Types/IHaveDefaultValue.cs
- src/GraphQL/Types/IProvideResolvedType.cs
As you can see, no code changes were necessary.  But perhaps we should rename `IProvideResolvedType` to `IProvideType` ?  I'd probably leave it as-is.
Note: xml comments to be done in separate PR targeting the `master` branch
> Move IHaveDefaultValue.Type to IProvideResolvedType.Type

- docs2/site/docs/migrations/migration4.md
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL/Types/Relay/DataObjects/Connection.cs
@sungam3r Any comments? Seems rather obvious to me when considering this existing code:
```cs
Field<IntGraphType>()
.Name("totalCount")
.Description(
"A count of the total number of objects in this connection, ignoring pagination. " +
"This allows a client to fetch the first five objects by passing \"5\" as the argument " +
"to `first`, then fetch the total count so it could display \"5 of 83\", for example. " +
"In cases where we employ infinite scrolling or don't have an exact count of entries, " +
"this field will return `null`.");
```
> Change Connection.TotalCount to nullable int

- docs2/site/docs/guides/known-issues.md
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.Tests/Bugs/Bug1699InvalidEnum.cs
- src/GraphQL.Tests/Bugs/Bug2159.cs
- src/GraphQL.Tests/Bugs/Issue1127.cs
- src/GraphQL/Execution/ExecutionHelper.cs
- src/GraphQL/Language/AST/Variable.cs
- src/GraphQL/Language/AST/Variables.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContextExtensions.cs
Fixes #2159
Requires a signature change to CoerceValue and ValueFor.  They are added optional fields, so although not binary-compatible, it is "compile-compatible".
Changed one test that relied on incorrect behavior.  Added a number of tests that verify this fix.
Should note this behavior and signature change in the release notes.
> Don't override argument null literals with default values

- src/Directory.Build.props
- src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs
- src/GraphQL/Utilities/SchemaPrinter.cs
before
```graphql
type Query {
str(argOne: SomeInput! = GraphQL.Tests.Utilities.SchemaPrinterTests+SomeInput): String!
}
input SomeInput {
age: Int!
name: String!
isDeveloper: Boolean!
}
```
after
```graphql
type Query {
str(argOne: SomeInput! = { age: 42, name: "Tom", isDeveloper: true }): String!
}
input SomeInput {
age: Int!
name: String!
isDeveloper: Boolean!
}
```
> SchemaPrinter can print inputobject default values

- docs2/site/docs/guides/known-issues.md
- docs2/site/docs/migrations/migration4.md
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL/Execution/ExecutionContext.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/ResolveFieldContext/IResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ReadonlyResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContextExtensions.cs
Updated PR of #1584 
This re-uses `ReadonlyResolveFieldContext` for synchronous resolvers.
|        Method | UseCaching |       Mean |     Error |    StdDev |   Gen 0 |   Gen 1 | Gen 2 | Allocated |
|-------------- |----------- |-----------:|----------:|----------:|--------:|--------:|------:|----------:|
| Introspection |      False | 949.071 us | 3.9364 us | 3.6821 us | 87.8906 | 23.4375 |     - | 544.37 KB |
|          Hero |      False |  17.149 us | 0.0353 us | 0.0330 us |  1.4343 |       - |     - |   8.84 KB |
| Introspection |       True | 707.605 us | 6.1738 us | 5.7750 us | 82.0313 | 27.3438 |     - | 504.67 KB |
|          Hero |       True |   3.509 us | 0.0137 us | 0.0129 us |  0.6790 |  0.0038 |     - |   4.16 KB |
|        Method | UseCaching |       Mean |     Error | …
> Add ReadonlyResolveFieldContext "pool"

- src/GraphQL.Tests/Execution/MultithreadedTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Types/ISchema.cs
Fixes #2208 
Adds test which proves bug exists and fails prior to this fix.
> Add lock for multithreaded initialization

- docs2/site/docs/migrations/migration4.md
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/ExecutionHelper.cs
- src/GraphQL/Execution/ExecutionOptions.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/Instrumentation/InstrumentFieldsMiddleware.cs
- src/GraphQL/Instrumentation/Metrics.cs
``` ini
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.14393.3986 (1607/AnniversaryUpdate/Redstone1)
Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
Frequency=3515611 Hz, Resolution=284.4456 ns, Timer=TSC
.NET Core SDK=5.0.102
[Host]     : .NET Core 3.1.11 (CoreCLR 4.700.20.56602, CoreFX 4.700.20.56604), X64 RyuJIT
DefaultJob : .NET Core 3.1.11 (CoreCLR 4.700.20.56602, CoreFX 4.700.20.56604), X64 RyuJIT
```
before
|        Method | UseCaching |         Mean |     Error |    StdDev |    Gen 0 |   Gen 1 | Gen 2 | Allocated |
|-------------- |----------- |-------------:|----------:|----------:|---------:|--------:|------:|----------:|
| **Introspection** |      **False** | **1,112.457 μs** | **7.9694 μs** | **6.6548 μs** | **107.4219** | **33.2031** |     **-** | …
> Optimize metrics collection

- docs2/site/docs/getting-started/field-middleware.md
- docs2/site/docs/migrations/migration4.md
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.Benchmarks/Properties/launchSettings.json
- src/GraphQL.Harness/GraphQLMiddleware.cs
- src/GraphQL.Harness/Startup.cs
- src/GraphQL.Tests/Bugs/Bug1769.cs
- src/GraphQL.Tests/Bugs/Bug252ExecutorAppliesFIeldBuilderOnce.cs
- src/GraphQL.Tests/Execution/MultithreadedTests.cs
- src/GraphQL.Tests/Instrumentation/ApolloTracingTests.cs
- src/GraphQL.Tests/Instrumentation/FieldMiddlewareBuilderTests.cs
- src/GraphQL.Tests/Types/SchemaTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/ExecutionOptions.cs
- src/GraphQL/Instrumentation/FieldMiddlewareBuilder.cs
- src/GraphQL/Instrumentation/FieldMiddlewareBuilderExtensions.cs
- src/GraphQL/Instrumentation/IFieldMiddleware.cs
- src/GraphQL/Instrumentation/IFieldMiddlewareBuilder.cs
- src/GraphQL/Types/Collections/SchemaTypes.cs
- src/GraphQL/Types/ISchema.cs
- src/GraphQL/Types/Schema.cs
Similar to how `NameConverter` and `SchemaFilter` were moved from `ExecutionOptions` to `Schema`, the same is now true for `FieldMiddleware`, since that also defines the schema configuration, rather than being an execution option.
Also simplifies middleware `Use` methods and overall design.
> Move FieldMiddleware from ExecutionOptions to Schema

- src/GraphQL.ApiTests/GraphQL.ApiTests.csproj
Any particular reason the API tests run for both net5 and net3.1 ?
> Prevent API tests from running twice

- src/GraphQL.ApiTests/ApiApprovalTests.cs
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.Benchmarks/Properties/launchSettings.json
- src/GraphQL.Tests/Types/ComplexGraphTypeTests.cs
- src/GraphQL/GlobalSwitches.cs
- src/GraphQL/Introspection/__Directive.cs
- src/GraphQL/Introspection/__EnumValue.cs
- src/GraphQL/Introspection/__Field.cs
- src/GraphQL/TypeExtensions.cs
- src/GraphQL/Utilities/NameValidator.cs
Inspired by https://github.com/graphql-dotnet/graphql-dotnet/pull/1451#issuecomment-768395522 😄 
``` ini
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.14393.3986 (1607/AnniversaryUpdate/Redstone1)
Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
Frequency=3515611 Hz, Resolution=284.4456 ns, Timer=TSC
.NET Core SDK=5.0.102
[Host]     : .NET Core 3.1.11 (CoreCLR 4.700.20.56602, CoreFX 4.700.20.56604), X64 RyuJIT
DefaultJob : .NET Core 3.1.11 (CoreCLR 4.700.20.56602, CoreFX 4.700.20.56604), X64 RyuJIT
```
|Method|Stage|Mean [base]|Mean [current]|Mean [% of base]|Allocated [base]|Allocated [current]|Allocated [% of base]|
|---|---|--:|--:|--:|--:|--:|--:|
|Introspection|Build|6,212,182.516 ns|1,329,152.997 ns|<span style="color:green">21</span>|2639115 B|323648 …
> Add global switches

- docs2/site/docs/migrations/migration4.md
- src/GraphQL.ApiTests/GraphQL.NewtonsoftJson.approved.txt
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.DataLoader.Tests/DataLoaderQueryTests.cs
- src/GraphQL.NewtonsoftJson/ExecutionResultContractResolver.cs
- src/GraphQL.NewtonsoftJson/ExecutionResultJsonConverter.cs
- src/GraphQL.NewtonsoftJson/ObjectPropertyArrayJsonConverter.cs
- src/GraphQL.NewtonsoftJson/StringExtensions.cs
- src/GraphQL.SystemReactive/SubscriptionExecutionStrategy.cs
- src/GraphQL.SystemTextJson/ExecutionResultJsonConverter.cs
- src/GraphQL.SystemTextJson/ObjectDictionaryConverter.cs
- src/GraphQL.Tests/Bugs/Issue661.cs
- src/GraphQL.Tests/Execution/Performance/ThreadPerformanceTests.cs
- src/GraphQL.Tests/Execution/UnionInterfaceTests.cs
- src/GraphQL.Tests/QueryTestBase.cs
- src/GraphQL.Tests/TestExtensions.cs
- src/GraphQL.Tests/Utilities/FederatedSchemaBuilderTests.cs
- src/GraphQL.Tests/Utilities/SchemaBuilderExecutionTests.cs
- src/GraphQL/Execution/ExecutionResult.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/Execution/Nodes/ArrayExecutionNode.cs
- src/GraphQL/Execution/Nodes/ObjectExecutionNode.cs
NOTE: `ExecutionResult.Data` format breaking changes. Both serializers received the necessary changes to produce the same JSON as before. However, consumers using `ExecutionResult` instances directly will fail.
``` ini
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.14393.3986 (1607/AnniversaryUpdate/Redstone1)
Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
Frequency=3515611 Hz, Resolution=284.4456 ns, Timer=TSC
.NET Core SDK=5.0.102
[Host]     : .NET Core 3.1.11 (CoreCLR 4.700.20.56602, CoreFX 4.700.20.56604), X64 RyuJIT
DefaultJob : .NET Core 3.1.11 (CoreCLR 4.700.20.56602, CoreFX 4.700.20.56604), X64 RyuJIT
```
develop -> 2cca930
|Method|Stage|Mean [base]|Mean [current]|Mean [% of base]|Allocated [base]|Allocated [current]|Allocated [% of base]| …
> Change ExecutionResult.Data internals from dictionaries to arrays

- docs2/site/docs/migrations/migration4.md
- src/GraphQL.ApiTests/GraphQL.SystemReactive.approved.txt
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.SystemReactive/SubscriptionExecutionStrategy.cs
- src/GraphQL.Tests/Execution/ExecutionNodeTests.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/Execution/Nodes/ExecutionNode.cs
- src/GraphQL/Execution/Nodes/ObjectExecutionNode.cs
- src/GraphQL/Execution/Nodes/SubscriptionArrayExecutionNode.cs
- src/GraphQL/Execution/Nodes/SubscriptionObjectExecutionNode.cs
- src/GraphQL/Execution/Nodes/SubscriptionValueExecutionNode.cs
Should provide 16 bytes of savings for every instance of ExecutionNode, including ValueExecutionNode instances.  Have not yet run benchmarks
* `Source` is only set during subscription execution.  It is left `null` for any other execution.  To reduce memory, `_source` has been removed from `ExecutionNode` along with the setter, and for subscriptions, another class is used that overrides the source property.
* `IsResultSet` is unnecessary, since the execution strategy almost always is required to process nodes like this: 1. create node 2. execute node 3. execute data loader, if any.   The only exception is that root nodes are not executed, and children of array nodes are not executed.  A simple type check (`node is RootExecutionNode` or `node.Parent is ArrayExecutionNode`) can determine …
> Remove ExecutionNode.IsResultSet and memory for Source

- .github/ISSUE_TEMPLATE/question.md
- README.md
- docs2/site/docs/getting-started/dependency-injection.md
- docs2/site/docs/getting-started/introduction.md
- docs2/site/docs/getting-started/relay.md
- docs2/site/docs/getting-started/schema-types.md
- docs2/site/docs/guides/dataloader.md
- docs2/site/docs/guides/links.md
- docs2/site/docs/guides/schema-generation.md
- docs2/site/sitemap.yml
`GraphQL .NET` usages: 10
`GraphQL.NET` usages: 32   -> _winner_
> Add format column, fix GraphQL.NET naming

- docs2/site/docs/migrations/migration4.md
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.Tests/Introspection/AppliedDirectivesTests.cs
- src/GraphQL.Tests/Types/InvalidEnumGraphTypeTests.cs
- src/GraphQL.Tests/Utilities/Visitors/DescriptionDirectiveVisitor.cs
- src/GraphQL.Tests/Utilities/Visitors/UppercaseDirectiveVisitor.cs
- src/GraphQL/ExperimentalFeatures.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/Introspection/SchemaMetaFieldType.cs
- src/GraphQL/Introspection/__Directive.cs
- src/GraphQL/Introspection/__DirectiveLocation.cs
- src/GraphQL/Introspection/__Schema.cs
- src/GraphQL/SchemaExtensions.cs
- src/GraphQL/Types/Collections/SchemaTypes.cs
- src/GraphQL/Types/Directives/DirectiveGraphType.cs
- src/GraphQL/Types/ISchema.cs
- src/GraphQL/Types/Scalars/EnumerationGraphType.cs
- src/GraphQL/Types/Schema.cs
- src/GraphQL/Utilities/SchemaBuilder.cs
- src/GraphQL/Utilities/SchemaPrinter.cs
- src/GraphQL/Utilities/Visitors/AppliedDirectivesValidationVisitor.cs
- src/GraphQL/Utilities/Visitors/BaseSchemaNodeVisitor.cs
- src/GraphQL/Utilities/Visitors/DeprecatedDirectiveVisitor.cs
- src/GraphQL/Utilities/Visitors/DirectivesValidationVisitor.cs
- src/GraphQL/Utilities/Visitors/ISchemaNodeVisitor.cs
This is a continuation of working with directives. Fixes #1496.
> Support for repeatable directives, refactored schema visitors (stateless), directives validation, small optimizations

- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.DataLoader.Tests/QueryTestBase.cs
- src/GraphQL.Harness.Tests/GraphQLAssertion.cs
- src/GraphQL.NewtonsoftJson/ExecutionResultJsonConverter.cs
- src/GraphQL.SystemReactive/SubscriptionExecutionStrategy.cs
- src/GraphQL.SystemTextJson/ExecutionResultJsonConverter.cs
- src/GraphQL.Tests/Bugs/BubbleUpTheNullToNextNullable.cs
- src/GraphQL.Tests/Bugs/Bug1156.cs
- src/GraphQL.Tests/Bugs/Bug1205VeryLongInt.cs
- src/GraphQL.Tests/Bugs/Bug1699InvalidEnum.cs
- src/GraphQL.Tests/Bugs/Bug1767InvalidByte.cs
- src/GraphQL.Tests/Bugs/Bug1769.cs
- src/GraphQL.Tests/Bugs/Bug1831.cs
- src/GraphQL.Tests/Bugs/Bug2159.cs
- src/GraphQL.Tests/Bugs/Issue1189.cs
- src/GraphQL.Tests/Bugs/NullArguments.cs
- src/GraphQL.Tests/Bugs/ScalarsInputTest.cs
- src/GraphQL.Tests/DocumentWriterTests.cs
- src/GraphQL.Tests/Errors/UnhandledExceptionTests.cs
- src/GraphQL.Tests/Execution/LongTests.cs
- src/GraphQL.Tests/Execution/VariablesTests.cs
- src/GraphQL.Tests/QueryTestBase.cs
- src/GraphQL.Tests/Shared/JsonStringExtensions.cs
- src/GraphQL.Tests/StarWars/StarWarsFragmentTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/ExecutionErrors.cs
- src/GraphQL/Execution/ExecutionResult.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/Resolvers/FuncFieldResolver.cs
- src/GraphQL/Validation/ValidationResult.cs
See https://spec.graphql.org/June2018/#sec-Data
> If an error was encountered before execution begins, the data entry should not be present in the result.
> If an error was encountered during the execution that prevented a valid response, the data entry in the response should be null.
> The ExecutionResult.Data property is serialized only if the request was executed.

- src/GraphQL.Tests/Bugs/Issue1927ResolvedTypeWithType.cs
- src/GraphQL/TypeExtensions.cs
- src/GraphQL/Types/Composite/ComplexGraphType.cs
- src/GraphQL/Types/Composite/ListGraphType.cs
- src/GraphQL/Types/Composite/NonNullGraphType.cs
- src/GraphQL/Types/Fields/FieldType.cs
See issue #1927 
This does not fix the underlying issue, that `IsInputType` sometimes cannot accurately identify if the supplied type is an input or output type, but rather this code does not call `IsInputType` on `Type` if `ResolvedType` is set.
Note: both tests failed before and both pass now.  Also, the original code sample within #1927 was tested and now works.
Note: these are almost the only uses of `IsInputType(Type type)` and `IsOutputType(Type type)`.  The one other use does not suffer the same issue.
Also added check to `FieldType.Type` setter.
> Patch for issue 1927 - adding a field where Type = ListGraphType

- docs2/site/docs/migrations/migration4.md
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL/Types/Scalars/BigIntGraphType.cs
- src/GraphQL/Types/Scalars/BooleanGraphType.cs
- src/GraphQL/Types/Scalars/ByteGraphType.cs
- src/GraphQL/Types/Scalars/DecimalGraphType.cs
- src/GraphQL/Types/Scalars/FloatGraphType.cs
- src/GraphQL/Types/Scalars/GuidGraphType.cs
- src/GraphQL/Types/Scalars/IdGraphType.cs
- src/GraphQL/Types/Scalars/IntGraphType.cs
- src/GraphQL/Types/Scalars/LongGraphType.cs
- src/GraphQL/Types/Scalars/SByteGraphType.cs
- src/GraphQL/Types/Scalars/ScalarGraphType.cs
- src/GraphQL/Types/Scalars/ShortGraphType.cs
- src/GraphQL/Types/Scalars/StringGraphType.cs
- src/GraphQL/Types/Scalars/UIntGraphType.cs
- src/GraphQL/Types/Scalars/ULongGraphType.cs
- src/GraphQL/Types/Scalars/UShortGraphType.cs
This cleans up the API and eliminates boxing for many types of scalar graph types when accessed by `CanParseLiteral`.
I did not add code for `CanParseValue` because in almost all instances, `ValueConverter` is called, and so it cannot be determined which types can be supported.  Besides, that code path is not used by GraphQL.Net.
A `try..catch` block was only needed by a couple scalars.
> Cleanup ScalarGraphType

- src/GraphQL.Tests/Bugs/Bug2279.cs
This passes both against `master` and `develop`... ???
See #2279
> Test for duplicate type name for generic graph type

- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL/Types/Composite/NonNullGraphType.cs
Of note, `ResolvedType` is of type `IGraphType`, and `ListGraphType<>`'s constraint is already `IGraphType`
> Change generic type constraint of NonNullGraphType

- docs2/site/docs/migrations/migration4.md
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.Tests/Types/ComplexGraphTypeTests.cs
- src/GraphQL/GlobalSwitches.cs
- src/GraphQL/Utilities/NameValidator.cs
Fixes #2204 
Also renamed `GlobalSwitches.Validation` to `GlobalSwitches.NameValidation` to better indicate what this delegate is validating.
> Remove ValidationOnSchemaInitialize

- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL/Types/ISchema.cs
- src/GraphQL/Types/Schema.cs
Realized this property was missing when trying to enumerate the additionally registered graph type instances.
> Add ISchema.AdditionalTypeInstances

- docs2/site/docs/migrations/migration4.md
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL/Types/GraphQLTypeReference.cs
Fixes #2364 
These three classes seem necessary (or at the very least, useful) for people writing dynamic schema builder code.
- `GraphQLTypeReference`
- `GraphQLClrOutputTypeReference`
- `GraphQLClrInputTypeReference`
This PR makes them public.
> Make type reference classes public

- docs2/site/docs/migrations/migration4.md
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL/Utilities/AstPrinter.cs
If someone needs access to the `AstPrinter` internals, we can make it public again.  Or refactor and then make it public again.  Seems that the only thing needed might be a hook in case someone adds another `ValueNode<T>` implementation, but with the new scalar types design, it should not be necessary.  All scalar nodes should be one of the predefined types.
> Change AstPrinter guts to internal

- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL/Types/Scalars/ScalarGraphType.cs
Does not affect built-in types, since specific implementations reduce boxing.
For custom scalars, now a person can simply implement `ParseValue` and all other methods have default implementations.
> Add default implementation of ParseLiteral

- src/GraphQL/GraphQL.csproj
Fixes #2399 for version 3.3.x (if we decide to release another revision)
https://docs.microsoft.com/en-us/nuget/concepts/package-versioning
Package version is now defined as:
- `[5.3.3,6)`
- Compatible with >= 5.3.3 and < 6
- Prefer smallest compatible version (5.3.3)
Alternate choice:
- `[5.*,6)`
- Compatible with >= 5 and < 6
- Prefer highest compatible version (currently 5.3.3)
> Update package reference to GraphQL-Parser

- src/GraphQL.Tests/Language/ValueNodeTests.cs
- src/GraphQL.Tests/NameFieldResolverTests.cs
- src/GraphQL.Tests/Utilities/AstPrinterTests.cs
- src/GraphQL.Tests/Validation/ArgumentsOfCorrectTypeTests.cs
- src/GraphQL/Language/AST/NameNode.cs
- src/GraphQL/Language/AST/ValueNodes/EnumValue.cs
- src/GraphQL/Language/AST/ValueNodes/FloatValue.cs
- src/GraphQL/Language/AST/ValueNodes/ObjectField.cs
- src/GraphQL/Language/AST/ValueNodes/StringValue.cs
- src/GraphQL/Language/AST/VariableReference.cs
- src/GraphQL/Utilities/AstPrinter.cs
Fixed bugs:
- Strings are not escaped
- Negative integers are not printed with the invariant culture, so the negative symbol can be incorrect
- Floating-point `double` values are not printed in the shortest form possible, either using an integer if possible or a "1.0E+44" syntax when necessary to represent very small or very large numbers.  Note that it is explicitly allowed that integer values can represent floating point input fields/arguments.
- Floating-point `double` values would not print very small values (e.g. less than 0.000000000001) at all.  Per the spec it should hold any value that can be represented by IEEE 754.
- Floating-point `decimal` values are not printed with the proper amount of precision, or in the shortest form possible
- Floating-point NaN/infinity values are …
> Fix formatting for AstPrinter value nodes

- src/Directory.Build.props
- src/GraphQL.SystemReactive/SubscriptionExecutionStrategy.cs
Fixes `Subscribe_and_mutate_messages` test for https://github.com/graphql-dotnet/server/pull/518 . The error is that the data from the subscription comes with empty body.
> Fix to serialize ExecutionResult from subscriptions

- .github/workflows/wipcheck.yml
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs
- src/GraphQL/Introspection/__DirectiveLocation.cs
- src/GraphQL/Introspection/__TypeKind.cs
- src/GraphQL/Types/IGraphType.cs
- src/GraphQL/Types/Scalars/BigIntGraphType.cs
- src/GraphQL/Types/Scalars/BooleanGraphType.cs
- src/GraphQL/Types/Scalars/ByteGraphType.cs
- src/GraphQL/Types/Scalars/DateGraphType.cs
- src/GraphQL/Types/Scalars/DateTimeGraphType.cs
- src/GraphQL/Types/Scalars/DateTimeOffsetGraphType.cs
- src/GraphQL/Types/Scalars/DecimalGraphType.cs
- src/GraphQL/Types/Scalars/EnumerationGraphType.cs
- src/GraphQL/Types/Scalars/FloatGraphType.cs
- src/GraphQL/Types/Scalars/GuidGraphType.cs
- src/GraphQL/Types/Scalars/IdGraphType.cs
- src/GraphQL/Types/Scalars/IntGraphType.cs
- src/GraphQL/Types/Scalars/LongGraphType.cs
- src/GraphQL/Types/Scalars/SByteGraphType.cs
- src/GraphQL/Types/Scalars/ScalarGraphType.cs
- src/GraphQL/Types/Scalars/ShortGraphType.cs
- src/GraphQL/Types/Scalars/StringGraphType.cs
- src/GraphQL/Types/Scalars/TimeSpanMillisecondsGraphType.cs
- src/GraphQL/Types/Scalars/TimeSpanSecondsGraphType.cs
- src/GraphQL/Types/Scalars/UIntGraphType.cs
- src/GraphQL/Types/Scalars/ULongGraphType.cs
- src/GraphQL/Types/Scalars/UShortGraphType.cs
- src/GraphQL/Types/Scalars/UriGraphType.cs
- src/GraphQL/Utilities/Federation/AnyScalarGraphType.cs
I suggest gradually add `#nullable enable` by individual PRs. It will be easier. When we add nullable annotations throughout the code, then we can add `<Nullable>enable</Nullable>` to Directory.build.props and delete all `#nullable enable` from files.
> Apply NRT annotations to scalars

- src/GraphQL.Tests/Utilities/GetGraphTypeFromTypeTests.cs
- src/GraphQL/TypeExtensions.cs
> Fix GetGraphTypeFromType to support untyped IDataLoaderResult and throw for Task types

- src/GraphQL.Tests/Utilities/GetGraphTypeFromTypeTests.cs
- src/GraphQL/Types/Collections/SchemaTypes.cs
- src/GraphQL/Types/QueryArgument.cs
Arguments' types are not mapped via the CLR type mappings.  Critical bug for anyone using who was using the `GraphTypeTypeRegistry` in v3 for argument types.
> Fix argument type mapping regression

- src/Directory.Build.props
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.Tests/Initialization/SchemaInitializationTestBase.cs
- src/GraphQL.Tests/Initialization/SchemaInitializationTests.cs
- src/GraphQL.Tests/Utilities/StringUtilsTests.cs
- src/GraphQL/DirectivesExtensions.cs
- src/GraphQL/Types/Collections/AppliedDirectives.cs
- src/GraphQL/Types/Directives/DirectiveArgument.cs
- src/GraphQL/Types/Fields/FieldType.cs
- src/GraphQL/Types/GraphType.cs
- src/GraphQL/Types/Scalars/EnumerationGraphType.cs
- src/GraphQL/Types/Schema.cs
- src/GraphQL/Utilities/SchemaBuilder.cs
- src/GraphQL/Utilities/StringUtils.cs
- src/GraphQL/Utilities/Visitors/AppliedDirectivesValidationVisitor.cs
- src/GraphQL/Utilities/Visitors/DeprecatedDirectiveVisitor.cs
This PR addresses a problem with duplication of `@deprecated` directive set as `DeprecationReason` property and as applied directive in schema element metadata. Now it is stored in metadata. `DeprecationReason` became computed property. This also saves a bit of memory for each field, type and enum value if they don't have `DeprecationReason` which is expected in the most cases (wasn't a goal, but 😄).  No breaking changes.
> DeprecationReason as computed property stored in Metadata (in applieddirectives), also changes " to ' in some error messages

- src/GraphQL.Tests/IsExternalInit.cs
Not a big deal for a test project, but I believe that IsExternalInit should always be marked internal when defined in a library.
> Make IsExternalInit internal

- src/GraphQL.ApiTests/GraphQL.MicrosoftDI.approved.txt
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.MicrosoftDI/ConnectionResolverBuilder.cs
- src/GraphQL.MicrosoftDI/ScopedConnectionBuilderExtensions.cs
- src/GraphQL.Tests/Builders/ConnectionBuilderTests.cs
- src/GraphQL/Builders/ConnectionBuilder.cs
- src/GraphQL/Builders/ConnectionBuilder_Typed.cs
Captures IsBidirectional and PageSize properties when creating the connection resolver, preventing a metadata dictionary lookup and enumeration of field arguments each time that the connection is resolved.  This issue did not exist prior to 4.3 so this is a performance regression fix caused by #2458 .
Added test to verify that the PageSize value is utilized.  (There was no test for this previously.)
Also see #2518.
> Optimize connection builder

- src/Directory.Build.props
- src/GraphQL.Tests/Initialization/SchemaInitializationTests.cs
- src/GraphQL/Types/Schema.cs
- src/GraphQL/Utilities/SchemaPrinter.cs
- src/GraphQL/Utilities/Visitors/AppliedDirectivesValidationVisitor.cs
- src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs
Also fixes (potential) bug with escaping when printing deprecation reason in `SchemaPrinter`.
> Better error handling for AppliedDirectivesValidationVisitor and SchemaValidationVisitor

- src/GraphQL.ApiTests/GraphQL.ApiTests.csproj
- src/GraphQL.ApiTests/GraphQL.NewtonsoftJson.approved.txt
- src/GraphQL.ApiTests/GraphQL.SystemTextJson.approved.txt
- src/GraphQL.Harness/GraphQLMiddleware.cs
- src/GraphQL.Harness/GraphQLRequest.cs
- src/GraphQL.NewtonsoftJson/StringExtensions.cs
- src/GraphQL.SystemTextJson/StringExtensions.cs
- src/GraphQL.Tests/Serialization/NewtonsoftJsonTests.cs
- src/GraphQL.Tests/Serialization/ObjectDictionaryConverterFacts.cs
- src/GraphQL.Tests/Serialization/SystemTextJsonTests.cs
- src/GraphQL/Validation/DocumentValidator.cs
See #2510 
- `FromJson` and `FromJsonAsync` are new methods for `GraphQL.SystemTextJson`.  They cannot be implemented for Newtonsoft due to its nature.  Or least, I'm not sure how at the moment.
- `ToInputs(this JsonElement element)` is a new method in `GraphQL.SystemTextJson`.  This mimics a similar method within `GraphQL.NewtonsoftJson` that already exists there (as `ToInputs(this JObject obj)`).  It uses a local `GetValue` function.  There exists a similar `GetValue` function in the `GraphQL.NewtonsoftJson` library for the same purpose which is public.  I do not see why this needs to be public, so it remains private in `GraphQL.SystemTextJson`.
> Add additional deserialization extensions to GraphQL

- src/Directory.Build.props
- src/GraphQL.Tests/Types/DateTimeOffsetGraphTypeTests.cs
- src/GraphQL/Types/Scalars/DateTimeOffsetGraphType.cs
I've noticed that it seems like impossible to send argument of `DateTimeOffset` type via variables to `GraphQL.Server` if `.AddNewtonsoftJson()` serializer with default settings is used. At this case I received the following response:
**Query:**
```
mutation test($arg: DateTimeOffset) {
someOperation(arg1: $arg)
}
```
**Variables:**
```
{
"arg": "2015-12-22T10:10:10+03:00"
}
```
**Response:**
```
{
"errors": [
{
"message": "GraphQL.Validation.InvalidVariableError: Variable '$arg' is invalid. Unable to convert '12/22/2015 10:10:10' to 'DateTimeOffset'\r\n ---> System.InvalidOperationException: Unable to convert '12/22/2015 10:10:10' to the scalar type 'DateTimeOffset'\r\n   at GraphQL.Types.ScalarGraphType.ThrowValueConversionError(Object value) in …
```
> DateTime value processing for DateTimeOffsetGraphType

- src/GraphQL.Tests/Types/UriGraphTypeTests.cs
- src/GraphQL/Types/Scalars/UriGraphType.cs
`Uri.ToString()` may return a corrupt URI. See https://faithlife.codes/blog/2010/08/uritostring_must_die/.
> Correctly serialize Uris.

- src/GraphQL.SystemTextJson/ExecutionResultJsonConverter.cs
- src/GraphQL.Tests/Bugs/Bug2553.cs
Extensions in errors should be serialized along with other values in the ExecutionResultJsonConverter
Addresses issue: https://github.com/graphql-dotnet/graphql-dotnet/issues/2552
> Serialize Error Extensions in System.Text.Json with provided options

- src/GraphQL.Tests/Utilities/Federation/FederatedSchemaPrinterTests.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContextExtensions.cs
- src/GraphQL/Utilities/Federation/FederatedSchemaPrinter.cs
Updated the FederatedSchemaPrinter file to prevent adding an empty Query { } as part of the SDL. This occurs if the query type only contains federated fields.
This does not prevent the Query type from being part of the SDL if the type includes non-federated fields.
Added an xUnit test case for this, and as there was no associated test class for FederatedSchemaPrinter a new test class was created.
See issue #2563.
> Updated the FederatedSchemaPrinter file to prevent adding an empty Query { } as part of the SDL.

- src/GraphQL.Tests/Bugs/Bug2557.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContextExtensions.cs
Fixes #2557 
The bug is a regression against v3.2.0 and prior, but exists in 3.3.0 and newer.  The bug was introduced in ~#1456~ #2160.
> Allow GetArgument with default value to operate on reference types

- docs2/site/docs/getting-started/dependency-injection.md
This is my attempt to make it absolutely clear on the importance of using Singleton Schema and the kind of performance benefits it has. We have seen first-hand the enormous improvement in performance once we moved to singleton schema and used service locator pattern. 
The idea with the doc update is to make it clear to the reader that we know it's an anti-pattern but in this specific situation, it's a necessity considering the huge performance degradation, if we don't go this route. 
May be the next reader will go away with less ambiguity because it did happen to me when I first read it, I didn't pay attention to it and paid the price dearly.
> Highlight the importance of using Singleton Schema

- src/GraphQL.ApiTests/GraphQL.MicrosoftDI.approved.txt
- src/GraphQL.MicrosoftDI/GraphQLBuilder.cs
Allows extension methods to cast `IGraphQLBuilder` to `GraphQLBuilder` and retrieve the `IServiceCollection` via `Services`.  Works for only Microsoft-based DI of course, but this is needed for authorization extension methods that integrate with ASP.Net within the server project.
> Expose Services within GraphQLBuilder

- src/GraphQL.ApiTests/GraphQL.MicrosoftDI.approved.txt
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.DataLoader.Tests/GraphQLBuilderTests.cs
- src/GraphQL.MicrosoftDI.Tests/GraphQLBuilderTests.cs
- src/GraphQL.MicrosoftDI/GraphQLBuilder.cs
- src/GraphQL.Tests/DI/GraphQLBuilderBaseTests.cs
- src/GraphQL.Tests/DI/GraphQLBuilderTests.cs
- src/GraphQL/DI/GraphQLBuilderBase.cs
- src/GraphQL/DI/IConfigureExecution.cs
- src/GraphQL/DI/IGraphQLBuilder.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/GraphQLBuilderExtensions.cs
- Allow casting IGraphQLBuilder to IServiceCollection so that a reference to GraphQL.MicrosoftDI is not needed if it is necessary to access the underlying IServiceCollection
- Allow asynchronous execution configurations
- Allow service registrations that replace existing registrations
> IGraphQLBuilder improvements

- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.Tests/Types/SchemaTests.cs
- src/GraphQL/Types/Collections/SchemaTypes.cs
- src/GraphQL/Types/Schema.cs
This allows overriding `SchemaTypes.GetGraphType` for a custom implementation.  For example, one may want to automatically map unmapped CLR types to `AutoRegisteringObjectGraphType<>`.  With this change, it is possible with just a few lines of code.
> Allow overriding SchemaTypes.GetGraphType

- src/GraphQL/Types/Composite/AutoRegisteringObjectGraphType.cs
Updated AutoRegisteringObjectGraphType and AutoRegisteringInputObjectGraphType constructors to allow nullable properties to be ignored
> Update AutoRegisteringObjectGraphType nullable types

- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.Tests/Types/Collections/SchemaTypesTests.cs
- src/GraphQL/Types/Collections/SchemaTypes.cs
The current design of `SchemaTypes` is such that no properties can be set on derived classes before initialization occurs.  For example, this code doesn't work:
```cs
private class MySchemaTypes : SchemaTypes
{
private readonly Dictionary<Type, Type> _mapping;
public MySchemaTypes(ISchema schema, IServiceProvider serviceProvider, Dictionary<Type, Type> customMapping)
: base(schema, serviceProvider)
{
_mapping = customMapping;
}
protected override Type? GetGraphTypeFromClrType(Type clrType, bool isInputType, List<(Type ClrType, Type GraphType)> typeMappings)
{
var ret = base.GetGraphTypeFromClrType(clrType, isInputType, typeMappings);
if (ret != null) return ret;
//custom logic here, which requires values passed into the constructor
if (!isInputType)
return _mapping[clrType]; //throws null …
```
> Add SchemaTypes.Initialize

- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs
- src/GraphQL/Introspection/ISchemaComparer.cs
- src/GraphQL/Utilities/SchemaPrinter.cs
- src/GraphQL/Utilities/SchemaPrinterOptions.cs
Fixes #2685 
Note: due to the limitations of `ISchemaComparer`, there is no way to sort directive locations or directive arguments.  Changing an interface signature is a breaking change and will need to be done in v5; an issue will be created to address this.  I think this is still worthwhile to include the other changes in v4.
Another temporary solution would be to evaluate `Options.Comparer is AlphabeticalSchemaComparer`, and if so, sort the members alphabetically.  I did not do so.
> Enable SchemaPrinter to sort output

- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL/ResolveFieldContext/ResolveFieldContextExtensions.cs
See:
- #2705 
This is a non-breaking change.  I think it's the right answer.  If a user anticipates a null response, they can indicate it as such when they call `GetArgument` - for example `GetArgument<string?>`.
> Update GetArgument nullability definitions

- src/GraphQL.DataLoader.Tests/BatchDataLoaderTests.cs
- src/GraphQL.DataLoader.Tests/CollectionBatchLoaderTests.cs
- src/GraphQL.DataLoader/DataLoaderBase.cs
- src/GraphQL.DataLoader/DataLoaderResult.cs
Replaces:
- #2702
Not a breaking change because before an ArgumentNullException would have been thrown by the underlying dictionary.  So null values (reference or value types) were not supported previously.
> Allow nulls in data loaders to pass through

- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL/ResolveFieldContext/IResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ReadonlyResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContextAdapter.cs
- src/GraphQL/Subscription/ResolveEventStreamContext.cs
- src/GraphQL/Types/Collections/SchemaTypes.cs
- src/GraphQL/Types/Composite/ObjectGraphType.cs
- src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs
Fixes #2705
With this PR, `IResolveFieldContext<T>.Source` is not marked as nullable (unless `T` is a nullable type).  This is useful because in almost every use case, `Source` is not nullable -- only field resolvers within the root node (Query, Mutation, or Subscription) can have a null `Source` property.
`IResolveFieldContext.Source` is still typed as `object?`, and `ObjectGraphType` derives from `ObjectGraphType<object?>` so the `Source` property is still marked as nullable in these cases (since `ObjectGraphType` is most likely to be used for a root node).
Please note that this is a NON-breaking change, as nullability reference annotations do not change method signatures.  ~At least for reference types -- could this be a breaking change for generic types where the generic type is a …
> Update nullability attribute of typed Source fields

- src/GraphQL/Validation/Rules/OverlappingFieldsCanBeMerged.cs
Very minor memory improvement: since `false` was never stored in the `Dictionary<string, bool>`, there was no reason to use it over a `HashSet<string>`.
Also replace `ObjMap` with its underlying type for clarification when reading the code.
> Update OverlappingFieldsCanBeMerged to use HashSet

- src/GraphQL.Tests/Types/DateTimeOffsetGraphTypeTests.cs
- src/GraphQL/Types/Scalars/DateTimeOffsetGraphType.cs
`DateTimeOffsetGraphType.ParseDate` drops the offset and there is no way to get the original client's offset. I've removed flag ` DateTimeStyles.AdjustToUniversal` and changed test: later it checked using `DateTimeOffset.Equals` that compares UTC time. Now it checks properties separately to avoid data loss.
> fix 'DateTimeOffset's Offset loss

- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Validation/DocumentValidator.cs
Hello. I guess `OperationName` property of `ValidationContext` has been always empty.
> OperationName for ValidationContext

- .github/workflows/publish-code.yml
Already tested here https://github.com/graphql-dotnet/server/blob/master/.github/workflows/publish.yml#L61
> Fix github-script@v5 usage

- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL/Utilities/Federation/FederatedSchemaPrinter.cs
- src/GraphQL/Utilities/SchemaPrinter.cs
Fixes #2577 - Rough and straightforward. Just a reminder - I said that we can get rid of most printer code if use the SDL visitor from the parser project.
> Initialize schema for all public methods in printers

- src/GraphQL.DataLoader/BatchDataLoader.cs
- src/GraphQL.DataLoader/CollectionBatchDataLoader.cs
- src/GraphQL.MicrosoftDI/ScopedAsyncFieldResolver.cs
- src/GraphQL.MicrosoftDI/ScopedConnectionBuilderExtensions.cs
- src/GraphQL/DirectivesExtensions.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/ParallelExecutionStrategy.cs
- src/GraphQL/Introspection/__Type.cs
- src/GraphQL/Validation/DocumentValidator.cs
Note: Need to check `DocumentExecuter` (call to `IDocumentCache.GetAsync`) and `DocumentValidator` for v5
> Add forgotten ConfigureAwait(false) for v4

- src/GraphQL.Tests/Utilities/Federation/FederatedSchemaPrinterTests.cs
- src/GraphQL/Utilities/Federation/FederatedSchemaPrinter.cs
- src/GraphQL/Utilities/SchemaPrinter.cs
See #2576. I think that it should be done in different way. First - type for queries may have any name, not only "Query".  Second - empty type definitions are allowed by the spec. See https://github.com/graphql-dotnet/parser/pull/117 fix. I changed both printers and test.
> Rework of FederatedSchemaPrinter fix

- src/GraphQL.Tests/DI/GraphQLBuilderTests.cs
- src/GraphQL/GraphQLBuilderExtensions.cs
It would be disposed when it should not have been because the wrong `Register` method was called
> Fix bug: schema instance was registered incorrectly by AddSchema

- .github/labeler.yml
- src/GraphQL.ApiTests/ApiApprovalTests.cs
- src/GraphQL.ApiTests/GraphQL.ApiTests.csproj
> Generate received files for all TFMs in one test run.

- src/GraphQL.ApiTests/ApiApprovalTests.cs
- src/GraphQL.MemoryCache/MemoryDocumentCache.cs
@Shane32 I think you like it.
The idea is pretty simple. We have long we use this test not as a test, but as a tool for controlling changes in API. We manually rename _approval_ files. Now this happens automatically, but only locally to accidentally not miss the changes.
> Auto approve API

- src/GraphQL/SchemaExtensions.cs
> Fix SchemaExtensions.Run

- docs2/site/docs/migrations/migration5.md
- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Benchmarks/Benchmarks/DetailedBenchmark.cs
- src/GraphQL.Benchmarks/Benchmarks/ValidationBenchmark.cs
- src/GraphQL.Tests/Validation/ValidationTestBase.cs
- src/GraphQL.Tests/Validation/ValidationTestConfig.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Validation/DocumentValidator.cs
- src/GraphQL/Validation/Rules.Custom/InputFieldsAndArgumentsOfCorrectLength.cs
- src/GraphQL/Validation/ValidationContext.cs
- src/GraphQL/Validation/ValidationOptions.cs
First commit - refactoring of `DocumentValidator.ValidateAsync` to wrap all arguments into one new for backward compatibility reasons in future.
Second commit - add extensions into `ValidationOptions`.
Third commit - migration notes.
> Introduce ValidationOptions

- docs2/site/docs/guides/known-issues.md
- src/GraphQL.ApiTests/GraphQL.NewtonsoftJson.approved.txt
- src/GraphQL.DataLoader.Tests/GraphQL.DataLoader.Tests.csproj
- src/GraphQL.DataLoader.Tests/QueryTestBase.cs
- src/GraphQL.NewtonsoftJson/DocumentWriter.cs
- src/GraphQL.NewtonsoftJson/FixPrecisionConverter.cs
- src/GraphQL.NewtonsoftJson/GraphQL.NewtonsoftJson.csproj
- src/GraphQL.Tests/DocumentWritersTestData.cs
- src/GraphQL.Tests/QueryTestBase.cs
First commit demonstrates issue with Newtonsoft.
Inspired by changes in tests from #2841.
> Fix number precision for Newtonsoft.Json

- docs2/site/docs/getting-started/dependency-injection.md
The docs for ResolveScopedAsync had incorrect code, so I had to go look at the source. This should now be correct.
> Fix the docs for ResolveScopedAsync

- src/GraphQL.ApiTests/GraphQL.NewtonsoftJson.approved.txt
- src/GraphQL.ApiTests/GraphQL.SystemTextJson.approved.txt
- src/GraphQL.NewtonsoftJson/GraphQLSerializer.cs
- src/GraphQL.SystemTextJson/GraphQLSerializer.cs
For Newtonsoft.Json, the method that builds the serializer is static and can't be made virtual.  So I exposed the constructor with the serializer as protected, so derived classes can build their own serializer.
For System.Text.Json, derived classes can place additional configuration within the derived constructor of the class.
> Configure serializers so they can be easily extended if need be

- docs2/site/docs/migrations/migration5.md
- src/GraphQL.Tests/Types/ObjectGraphTypeTests.cs
- src/GraphQL.Tests/Utilities/SchemaBuilderTests.cs
- src/GraphQL/Types/GraphType.cs
See #2876 
Suggest to remove support for this attribute on graph type classes in code-first scenarios since the attribute was designed for schema-first and is not fully supported for code-first in any case.  There is no good reason for this attribute, because if a user has derived from `ObjectGraphType` in order to add an attribute, then they certainly can add code to the constructor.
Only possibly way I could see someone wishing to use the attribute today would be as follows:
```cs
[GraphQLMetadata("Person")]
public class PersonType : AutoRegisteringObjectGraphType<Human> { }
```
Even if such a scenario was desired, it should have supported all relevant properties.  In any case, in a subsequent PR, I will be adding support for the attribute to be applied to the CLR type as in the …
> Remove support for GraphQLMetadata attribute to set graph type name

- docs2/site/docs/migrations/migration5.md
- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Types/AutoRegisteringInputObjectGraphTypeTests.cs
- src/GraphQL.Tests/Types/AutoRegisteringObjectGraphTypeTests.cs
- src/GraphQL/IgnoreAttribute.cs
- src/GraphQL/Types/Composite/AutoRegisteringInputObjectGraphType.cs
- src/GraphQL/Types/Composite/AutoRegisteringObjectGraphType.cs
Adds `[Ignore]` attribute so properties on data models can be easily skipped when auto-registering graph types:
```cs
public class ShoppingCartItem
{
[OutputType(typeof(NonNullGraphType<IdGraphType>))]
public int Id { get; set; }
public int Quantity { get; set; }
public string Description { get; set; }
public decimal Price { get; set; }
[Ignore]
public decimal Total => Quantity * Price;
}
```
This new attribute does not inherit from `GraphQLAttribute`.  We could add another protected method to the `GraphQLAttribute` class -- something like `bool Ignore(PropertyInfo property, bool isInputType)` -- and then rewrite `IgnoreAttribute` to inherit `GraphQLAttribute`, but so far I don't see a good reason to do so.
> Add Ignore attribute

- src/GraphQL.Harness/GraphQLMiddleware.cs
- src/GraphQL.Harness/Startup.cs
- Make the middleware a singleton
- Pulls `ISchema` via DI
- Middleware implements ASP.Net `IMiddleware` interface
> Update middleware sample

- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL/Utilities/SchemaBuilder.cs
Rel: #2959 . I continue to fight deadlocks in my tests. Now I want to be able to override `Schema.Validate` using schema built from `SchemaBuilder` so I need new protected method to return my subsclass with overridden method.
> Add SchemaBuilder.CreateSchema

- src/GraphQL.SystemTextJson/GraphQL.SystemTextJson.csproj
- src/GraphQL.SystemTextJson/InputsJsonConverter.cs
- src/GraphQL.Tests/Bugs/Bug2958DecimalPrecisionTests.cs
- src/GraphQL/GraphQLExtensions.cs
Fixes #2958 
@[dulcisclade](https://github.com/dulcisclade) note that for NSJ you may set `settings.FloatParseHandling = Newtonsoft.Json.FloatParseHandling.Decimal`
> Fix rounding of decimal numbers for STJ

- src/GraphQL.SystemTextJson/GraphQLSerializer.cs
- src/GraphQL.Tests/Serialization/SystemTextJson/GraphQLSerializerTests.cs
- src/GraphQL.Tests/Serialization/SystemTextJson/InputsConverterTests.cs
Rel: #2865 #2797 
Before:
> System.InvalidOperationException: 'Serializer options cannot be changed once serialization or deserialization has occurred.'
> Fix STJ bug

- src/GraphQL.Tests/Types/AutoRegisteringObjectGraphTypeTests.cs
- src/GraphQL/Validation/ValidationOptions.cs
Fixes a bit weird (new) compiler errors on 6.0.200 SDK:
> A 'struct' with field initializers must include an explicitly declared constructor
See https://github.com/dotnet/sdk/issues/23971
Core idea of new compiler "feature" - run field initializers from declared constructors **only**.
> Fix compiler errors

- docs2/site/docs/migrations/migration5.md
- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/DI/GraphQLBuilderBaseTests.cs
- src/GraphQL.Tests/Execution/DocumentExecuterTests.cs
- src/GraphQL/DI/GraphQLBuilderBase.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/IDocumentExecuter.cs
I would like to add this to better support multiple schemas.  It adds a single interface to the public API.  An example of its use is provided in the tests - see `StringExecuter` sample class.
> Add typed IDocumentExecuter

- src/GraphQL.ApiTests/GraphQL.DataLoader.approved.txt
- src/GraphQL.DataLoader.Tests/DataLoaderQueryTests.cs
- src/GraphQL.DataLoader.Tests/Types/QueryType.cs
- src/GraphQL.DataLoader/DataLoaderExtensions.cs
> Add 'Then' data loader extension method for lists of data loader results.

- src/GraphQL.ApiTests/GraphQL.NewtonsoftJson.approved.txt
- src/GraphQL.NewtonsoftJson/GraphQLRequestJsonConverter.cs
- src/GraphQL.NewtonsoftJson/GraphQLRequestListJsonConverter.cs
- src/GraphQL.SystemTextJson/GraphQLRequestListJsonConverter.cs
- src/GraphQL.Tests/Serialization/GraphQLRequestTests.cs
Fixes a bug where if a batch request as follows was processed by the server:
```json
[null]
```
Then the server would only receive an empty array and respond like this:
```json
[]
```
Rather than the correct response which should be something of this nature:
```json
[
{
"errors": [{"message":"GraphQL request cannot be null."}]
}
]
```
> Fix deserialization bug for batches containing null

- src/Directory.Build.props
- src/Directory.Build.targets
- src/GraphQL.Benchmarks/GraphQL.Benchmarks.csproj
- src/GraphQL.Harness/CountFieldMiddleware.cs
- src/GraphQL.Harness/GraphQL.Harness.csproj
- src/GraphQL.StarWars/GraphQL.StarWars.csproj
- src/GraphQL.SystemTextJson/ExecutionResultJsonConverter.cs
- src/GraphQL.SystemTextJson/InputsJsonConverter.cs
- src/GraphQL.Tests/QueryTestBase.cs
- src/GraphQL/Utilities/Federation/FederatedSchemaBuilder.cs
- src/GraphQL/Validation/Errors/DefaultValuesOfCorrectTypeError.cs
- src/GraphQL/Validation/Errors/KnownArgumentNamesError.cs
- src/GraphQL/Validation/Errors/PossibleFragmentSpreadsError.cs
- src/GraphQL/Validation/Errors/ProvidedNonNullArgumentsError.cs
- src/GraphQL/Validation/Errors/ScalarLeafsError.cs
- src/GraphQL/Validation/Errors/VariablesInAllowedPositionError.cs
- src/Tests.props
Changes:
- `ToString()` is marked as nullable, it seems (not in the IDE, but to the compiler) -- added `!` where necessary -- then removed NoWarn for that issue
- Fixed two or three other minor issues causing build warnings
- Enabled warnings-as-errors for the entire solution
- Disabled xml comments warning for all projects that do not pack solution-wide (was so already individually per project)
> Cleanup build warnings

- docs2/site/docs/getting-started/subscriptions.md
- docs2/site/docs/migrations/migration5.md
- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.DataLoader.Tests/Types/SubscriptionType.cs
- src/GraphQL.MicrosoftDI.Tests/ScopedAttributeTests.cs
- src/GraphQL.MicrosoftDI/DynamicScopedSourceStreamResolver.cs
- src/GraphQL.MicrosoftDI/ScopedAttribute.cs
- src/GraphQL.Tests/Subscription/SubscriptionExecutionStrategyTests.cs
- src/GraphQL.Tests/Subscription/SubscriptionSchema.cs
- src/GraphQL.Tests/Subscription/SubscriptionSchemaWithReflection.cs
- src/GraphQL/Builders/FieldBuilder.cs
- src/GraphQL/Execution/SubscriptionExecutionStrategy.cs
- src/GraphQL/GraphQLMetadataAttribute.cs
- src/GraphQL/Reflection/ReflectionHelper.cs
- src/GraphQL/Resolvers/ISourceStreamResolver.cs
- src/GraphQL/Resolvers/SourceStreamMethodResolver.cs
- src/GraphQL/Resolvers/SourceStreamResolver.cs
- src/GraphQL/Types/Composite/AutoRegisteringObjectGraphType.cs
- src/GraphQL/Types/Composite/ComplexGraphType.cs
- src/GraphQL/Types/Fields/FieldType.cs
- src/GraphQL/Utilities/FieldConfig.cs
- src/GraphQL/Utilities/SchemaBuilder.cs
Last of #3022
- Rename SubscribeAsync to ResolveAsync
- Rename Subscriber to StreamResolver
- Rename field builder methods Subscribe and SubscribeAsync to ResolveStream and ResolveStreamAsync
Does not rename field builder method parameters containing delegates which are currently 'resolve' and 'subscribe'.
> Rename SubscribeAsync to ResolveAsync and similar

- src/GraphQL/GraphQL.csproj
Parser 8.0.0 is not compatible with GraphQL.NET 4.8
> For 4.8, restrict parser to pre-8 versions

- docs2/site/docs/migrations/migration5.md
Add `ExecutionError` as a supported serialization type
> Update migration doc re serialization

- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Validation/RequestServicesTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Validation/DocumentValidator.cs
- src/GraphQL/Validation/ValidationContext.cs
- src/GraphQL/Validation/ValidationError.cs
- src/GraphQL/Validation/ValidationOptions.cs
I tried to write a validation rule today and was quite surprised to find that I could not access the scoped service provider provided to the request.
Also, to add an error to the validation context, you have to add an instance of `ValidationError`, which currently requires that `Number` be provided.  This is merely a NRT error, as `Number` is not actually required.  Note that `Number` is defined as the following:
> Gets or sets the rule number of this validation error corresponding to the paragraph number from the official specification.
So obviously there is no "paragraph number from the official specification" for custom validation errors.  Hence `Number` should not be required for custom validation errors anyway.
> Add RequestServices to ValidationContext

- src/GraphQL.Tests/Bugs/Bug2194.cs
- src/GraphQL.Tests/Bugs/Bug_nested_type_names_dont_conflict.cs
- src/GraphQL.Tests/CultureTestHelper.cs
- src/GraphQL.Tests/Extensions/PrintTests.cs
- src/GraphQL.Tests/ObjectExtensionsTest.cs
- src/GraphQL.Tests/StaticTestsCollection.cs
- src/GraphQL.Tests/Types/ComplexGraphTypeTests.cs
- src/GraphQL.Tests/Types/DateGraphTypeTests.cs
- src/GraphQL.Tests/Types/DateOnlyGraphTypeTests.cs
- src/GraphQL.Tests/Types/DateTimeGraphTypeTests.cs
- src/GraphQL.Tests/Types/DateTimeOffsetGraphTypeTests.cs
- src/GraphQL.Tests/Types/DecimalGraphTypeTests.cs
- src/GraphQL.Tests/Types/FloatGraphTypeTests.cs
- src/GraphQL.Tests/Types/TimeOnlyGraphTypeTests.cs
- src/GraphQL.Tests/Types/TimeSpanMillisecondsGraphTypeTests.cs
- src/GraphQL.Tests/Types/TimeSpanSecondsGraphTypeTests.cs
- src/GraphQL.Tests/Validation/ArgumentsOfCorrectTypeTests.cs
- src/GraphQL/GlobalSwitches.cs
Fixes remainder of #2982 issues (hopefully).
See:
- https://xunit.net/docs/shared-context
- https://xunit.net/docs/running-tests-in-parallel
> By default, each test class is a unique test collection. Tests within the same test class will not run in parallel against each other.
> If we need to indicate that multiple test classes should not be run in parallel against one another, then we place them into the same test collection. This is simply a matter of decorating each test class with an attribute that places them into the same uniquely named test collection:
> Parallel-capable test collections will be run first (in parallel), followed by parallel-disabled test collections (run sequentially).
So with these changes,
1. All tests that modify static variables are now placed in the same "test …
> Make tests that modify static variables run without parallelism

- src/GraphQL.Tests/Bugs/Issue2932_DemoDIGraphType.cs
- src/GraphQL.Tests/Types/ArgumentInformationTests.cs
- src/GraphQL/Types/ArgumentInformation.cs
New feature of C#10 https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-expressions#natural-type-of-a-lambda-expression - compiler now may infer type of lambda used for methods and expressions.
Rel: https://github.com/github/codeql/issues/8627
> C#10: Natural type of a lambda expression

- docs2/site/docs/migrations/migration5.md
- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/AuthorizationTests.cs
- src/GraphQL/Authorization/AuthorizationExtensions.cs
- src/GraphQL/Authorization/GraphQLAuthorizeAttribute.cs
This allows the role name (or multiple allowed role names) to be directly specified, bringing the `GraphQLAuthorizeAttribute` more in line with the ASP.Net `AuthorizeAttribute`.
It also will be simpler to use for those (like me) that often just wish to specify one or more roles rather than having to create policies that map to the configured roles.
Finally, as it is used in the GraphQL Server project, checking for roles is a much faster operation (probably zero-allocation), as the claim principal's `IsInRole` method can be easily called rather than having to call the asynchronous policy checker method and then using `GetAwaiter().GetResult()` to validate the policy.
> Add role support to authorization extensions

- src/GraphQL.DataLoader.Tests/BatchDataLoaderTests.cs
- src/GraphQL.DataLoader.Tests/CollectionBatchLoaderTests.cs
- src/GraphQL.DataLoader.Tests/DataLoaderExtensionsTests.cs
- src/GraphQL.DataLoader.Tests/DataLoaderSubscriptionTest.cs
- src/GraphQL.DataLoader.Tests/SimpleDataLoaderTests.cs
- src/GraphQL.Tests/Subscription/ObservableExtensionsTests.cs
Twice today different tests have failed for no apparent reason.  One seems to be a deadlock, presumably due to the synchronization context required for xUnit.  Adding `.ConfigureAwait(false)` should solve the problem.
> Add ConfigureAwait(false) to tests

- docs2/site/docs/migrations/migration5.md
As 5.0.0 is only 9 days old, and 5.1.0 will likely be released today, I suggest adding this note to the 'new features' section of the migration document.
> ### 21. `RequestServices` added to `ValidationContext` in GraphQL 5.1.0
> 
> This allows for validation rules to access scoped services if necessary.
> Add migration note regarding RequestServices

- docs2/site/docs/migrations/migration5.md
- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/AuthorizationTests.cs
- src/GraphQL/Authorization/AuthorizationExtensions.cs
- src/GraphQL/Authorization/GraphQLAuthorizeAttribute.cs
Closes #3076
This also fixes the attribute so that it applies the metadata to query arguments or enum definitions also, if it is marked on those type of objects.
> Authorization update

- src/GraphQL/Execution/ExecutionStrategy.cs
Fixes graphql-dotnet/graphql-dotnet#3093
It's possible there is a better way to do this but it seems to work. There might be some performance impact..
> Fix counting of nested named fragments

- src/GraphQL.Tests/Bugs/Bug3046.cs
- src/GraphQL/Resolvers/FuncFieldResolver.cs
See:
- #3046
Fixes this scenario, but few others:
```cs
Field<CharacterInterface>("hero", resolve: GetDroidByIdAsync);
Task<Droid> GetDroidByIdAsync(IResolveFieldContext<object> context)
=> _data.GetDroidByIdAsync("3");
```
Exceptions are thrown either during schema construction or schema initialization.  Debugging will reveal the faulty line of code.
Note that we could alter this code to accept the delegate and handle it correctly.  I elected not to do so, and require users to use the `FieldAsync` method or correct constructor.
> Partial fix to detect asynchronous return types within field delegates

- src/GraphQL/Execution/DocumentExecuter.cs
Very simple change here, which allows `IConfigureExecution` instances to configure `Schema`, `Query` and `Document` properties of `ExecutionOptions`.
> Allow execution configurations to set Schema and Query

- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL/Builders/ConnectionBuilder.cs
- src/GraphQL/Builders/ConnectionBuilder_Typed.cs
- src/GraphQL/Builders/FieldBuilder.cs
I need this for some of my code.  Even though all the methods are `virtual`, since the constructor is `private`, I cannot inherit the class.
@sungam3r I will merge tonight if you do not get a chance to review before then; if you have comments we can always add another PR to address them.
Thanks!
> Make FieldBuilder constructor public

- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Instrumentation/ApolloTracingTests.cs
- src/GraphQL/DI/IConfigureExecution.cs
- src/GraphQL/DI/IConfigureExecutionOptions.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/GraphQLBuilderExtensions.cs
- src/GraphQL/Instrumentation/ApolloTracingDocumentExecuter.cs
This allows for 'middleware' or 'plugin' behavior to the document executer.  This will be immediately useful for appending Apollo Tracing results, as well as implementation of Automatic Persisted Queries.
`IConfigureExecution` works similarly to "Apollo Link"s as seen below:
Within our library, these components are implemented similarly to this:
| Apollo | GraphQL.NET |
|---|---|
| GraphQL operation | `IDocumentExecuter` |
| Link | `IConfigureExecution` |
| Terminating Link | `GraphQLHttpMiddleware` |
(In the diagram above, Apollo Links are shown in the context of a client, but same design applies to a server.)
> Add IConfigureExecution

- .github/workflows/build-artifacts-code.yml
- .github/workflows/publish-code.yml
- .github/workflows/test-code.yml
- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
See:
- https://github.com/PublicApiGenerator/PublicApiGenerator/issues/207
Without this PR, api approvals will generate differently locally than within GitHub Actions (assuming that the current version of Visual Studio is installed locally).
> Update api approvals for .NET SDK 6.0.300

- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Complexity/ComplexityMetaDataTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Validation/Complexity/AnalysisContext.cs
- src/GraphQL/Validation/Complexity/ComplexityAnalayzerMetadataExtensions.cs
- src/GraphQL/Validation/Complexity/ComplexityAnalyzer.cs
- src/GraphQL/Validation/Complexity/ComplexityVisitor.cs
- src/GraphQL/Validation/Complexity/IComplexityAnalyzer.cs
An ability to specify a particular field's complexity impact by means of `Field<IntGraphType>("id").WithComplexityImpact(123)`, which will be taken into account by `ComplexityAnalyzer`. It is a possible solution of the issues #1254 and #298.
> Field's impact for ComplexityAnalyzer

- src/GraphQL/GraphQLBuilderExtensions.cs
Fixes issue reported at:
- https://github.com/graphql-dotnet/authorization/issues/235
> Throw proper exception when RequestServices is null

- src/GraphQL.Tests/Execution/ExecutionStrategyTests.cs
- src/GraphQL.Tests/Files/JSON/AppliedDirectivesResult.json
- src/GraphQL.Tests/Introspection/AppliedDirectivesTests.cs
- src/GraphQL.Tests/Introspection/SchemaIntrospectionTests.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
Currently a `ARGUMENT_NULL` error is returned to the client when a query request arrives for a schema with no root query type.  This PR aligns the error message with the similar case for mutation and subscription types, until such time as we decide to disallow schemas without a root query type (in accordance with the spec).
Note that there is an upcoming RFC to the spec for a validation rule to address this condition:
https://github.com/graphql/graphql-spec/pull/955
> Fix error message when no query is defined

- src/GraphQL.MemoryCache/AutomaticPersistedQueries/AutomaticPersistedQueriesExecutionBase.cs
Saves 2 `byte[]` allocations:
1. `Encoding.UTF8.GetBytes`: string -> byte[]
2. return value of `ComputeHash` (len = 32)
> Optimize hashing for APQ

- src/GraphQL/Types/Composite/AutoRegisteringObjectGraphType.cs
> Improved comment on AutoRegisteringObjectGraphType.GetRegisteredMembers()

- src/GraphQL/Validation/ValidationContext.GetRecursivelyReferencedFragments.cs
With the addition of overriding the operation, all other node types should be skipped, I believe.
> Add override for VisitOperationDefinitionAsync

- docs2/site/docs/getting-started/subscriptions.md
- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.DataLoader.Tests/Types/SubscriptionType.cs
- src/GraphQL.Tests/Subscription/SubscriptionSchema.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/Execution/SubscriptionExecutionStrategy.cs
- src/GraphQL/Resolvers/NameFieldResolver.cs
- src/GraphQL/Resolvers/SourceFieldResolver.cs
- src/GraphQL/Types/Composite/ComplexGraphType.cs
Allows to keep `Resolver` property unspecified (`null`) for top-level nodes of subscriptions since resolvers for such nodes always return `source` object. The goal - simplify field configuration on the caller side.
> Use SourceFieldResolver for top-level nodes of subscriptions

- .github/workflows/build-artifacts-code.yml
- docs2/site/docs/migrations/migration7.md
- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Benchmarks/Benchmarks/DetailedBenchmark.cs
- src/GraphQL.MicrosoftDI/ScopedResolveConnectionContextAdapter.cs
- src/GraphQL.MicrosoftDI/ScopedResolveFieldContextAdapter.cs
- src/GraphQL.Tests/Execution/ResolveFieldContextTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/ExecutionContext.cs
- src/GraphQL/Execution/ExecutionOptions.cs
- src/GraphQL/Execution/IExecutionContext.cs
- src/GraphQL/ResolveFieldContext/IResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ReadonlyResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContextAdapter.cs
- src/GraphQL/Validation/DocumentValidator.cs
- src/GraphQL/Validation/ValidationContext.cs
- src/GraphQL/Validation/ValidationOptions.cs
See https://github.com/graphql-dotnet/server/issues/314
Matches `HttpContext.User` except that it is nullable.
It might be better to default `User` to a static implementation of an anonymous user, sorta like ASP.NET Core does, so it does not need to be nullable.
This feature allows separation of the execution which defines the user from the validation rule which validates the request against the user, rather than requiring AsyncLocal to provide this mechanism.
> Add IResolveFieldContext.User

- .github/workflows/build-artifacts-code.yml
- src/Directory.Build.props
- src/Directory.Build.targets
- src/GraphQL.DataLoader/GraphQL.DataLoader.csproj
- src/GraphQL.MemoryCache/GraphQL.MemoryCache.csproj
- src/GraphQL.MicrosoftDI/GraphQL.MicrosoftDI.csproj
- src/GraphQL.NewtonsoftJson/GraphQL.NewtonsoftJson.csproj
- src/GraphQL.SystemTextJson/GraphQL.SystemTextJson.csproj
This, for example, restricts GraphQL.DataLoader to use only GraphQL 5.x versions.  Specifically, the matching version that was published, and any version up to but excluding the next major version number.  This will prevent GraphQL.DataLoader 5.3.3 from being compatible with GraphQL 7.0.0, and indirectly prevents #3229 from happening in the future.  A similar change should be made in the server repo.
See:
- https://github.com/NuGet/Home/issues/5556
- https://github.com/NuGet/Home/issues/5525
> Fix package versioning

- .github/workflows/test-code.yml
- src/GraphQL.DataLoader.Tests/BatchDataLoaderTests.cs
- src/GraphQL.DataLoader.Tests/DataLoaderExtensionsTests.cs
- src/GraphQL.DataLoader.Tests/DataLoaderQueryTests.cs
- src/GraphQL.DataLoader.Tests/GraphQL.DataLoader.Tests.csproj
- src/GraphQL.DataLoader.Tests/QueryTestBase.cs
- src/GraphQL.MicrosoftDI.Tests/GraphQL.MicrosoftDI.Tests.csproj
It was only used, I believe, because of missing ConfigureAwait calls, which have been fixed, and currently there is a build error for any missing ConfigureAwaits.
Required by:
- #3265
> Remove dependency on Nito.AsyncEx.Context

- src/GraphQL/ResolveFieldContext/ResolveFieldContext.cs
we are getting a null reference on ResolveConnectionContext since it uses the the constructor of ResolveFieldContext which does not duplicate the `User`
> user not duplicated in context

- src/GraphQL.Tests/Validation/InputFieldsAndArgumentsOfCorrectLengthRequiredTests.cs
- src/GraphQL.Tests/Validation/ValidationSchema.cs
- src/GraphQL/Validation/Rules.Custom/InputFieldsAndArgumentsOfCorrectLength.cs
> Fix InputFieldsAndArgumentsOfCorrectLength validation rule

- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL/Attributes/Authorization/AuthorizeAttribute.cs
- src/GraphQL/Validation/ValidationOptions.cs
> Remove init-only properties from pre-.NET 5 targets

- docs2/site/docs/migrations/migration7.md
- src/GraphQL.Tests/Bugs/BubbleUpTheNullToNextNullable.cs
- src/GraphQL.Tests/Types/ComplexGraphTypeTests.cs
- src/GraphQL.Tests/Types/NonNullGraphTypeTests.cs
- src/GraphQL/Types/Composite/ComplexGraphType.cs
Implemented within `ComplexGraphType<TSourceType>`
Applies to:
- `ObjectGraphType<TSourceType>`
- `InputObjectGraphType<TSourceType>`
- `AutoRegisteringObjectGraphType<TSourceType>`
- `AutoRegisteringInputObjectGraphType<TSourceType>`
> Prevent using graphtype as model

- src/GraphQL.Tests/Bugs/Bug1156.cs
- src/GraphQL.Tests/Bugs/Bug2279.cs
- src/GraphQL.Tests/Bugs/Bug3331.cs
- src/GraphQL.Tests/Bugs/Issue1927ResolvedTypeWithType.cs
- src/GraphQL.Tests/Types/Collections/SchemaTypesTests.cs
- src/GraphQL.Tests/Types/Collections/SchemaTypesTests.typechecking.cs
- src/GraphQL/Types/Collections/SchemaTypes.cs
This PR adds type integrity checks when a type is (accidentally) registered twice.
This fixes #3331. For example, in my case it was not applying the name conversion (camelCase) to the 2nd object causing runtime issues.
Example of an exception being thrown. This should give the developer some pointers to look for registration issues.
```
Type 'MyObjectGraphType' has field 'id', but this cannot be found on the new type. New type has:
- Id
- Name
Make sure to use the same type instances when registering the same type
```
Question: this PR causes 1 unit tests for a bug (Issue1927ResolvedTypeWithType, test_outputs) to fail. How would you like to deal with this?
> Add type integrity check when existing types are found

- src/GraphQL.Tests/Types/ComplexGraphTypeTests.cs
- src/GraphQL.Tests/Types/UnionGraphTypeTests.cs
- src/GraphQL/Types/GraphType.cs
A little help for #3351. I aligned the error text with one from `IsValidInterfaceFor` method.
> Expand error message in GraphType.Initialize

- src/GraphQL.Tests/TypeExtensionTests.cs
- src/GraphQL/Extensions/TypeExtensions.cs
Previously, an empty string would be returned, which would throw during `Name = typeof(TSource).GraphQLName();` before the name was altered via attributes.
> Fix GraphQLName for classes named Type and GraphType

- src/GraphQL.Tests/Bugs/Issue1004.cs
- src/GraphQL.Tests/Types/Collections/SchemaTypesTests.cs
- src/GraphQL/Introspection/__Field.cs
- src/GraphQL/Types/Collections/SchemaTypes.cs
On a large-ish GraphQL schema of mine producing the schema already quite a bit of time.
I've tracked down the culprit to the following code in __Field.cs which performs description inheritance (fills in empty field descriptions from corresponding interface fields, which was added in PR #1470 as a fix for issue #1004).
```
// We have to iterate over all schema types because FieldType has no reference to the GraphType to which it belongs.
foreach (var item in context.Schema.AllTypes.Dictionary)
{
if (item.Value is IComplexGraphType fieldOwner && fieldOwner.Fields.Contains(context.Source))
```
Looping over the whole schema is pretty inefficient, increasing with O(numberOfFieldsWithoutDescription * numberOfTypes * numberOfFields).
This PR solves that by keeping a dictionary of the fields' …
> Improve field description inheritance performance

- src/GraphQL.Tests/Bugs/Bug3415.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/Execution/IExecutionStrategy.cs
- src/GraphQL/ResolveFieldContext/IResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ReadonlyResolveFieldContext.cs
Demonstrates that accessing `SubFields` fails from within a field resolver of a field that is of a union graph type.
> Fix SubFields property for interfaces and unions

- docs2/site/docs/migrations/migration7.md
- src/GraphQL.ApiTests/net5/GraphQL.approved.txt
- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Execution/AbstractTypeTests.cs
- src/GraphQL.Tests/Types/AutoRegisteringInterfaceGraphTypeTests.cs
- src/GraphQL.Tests/Types/AutoRegisteringObjectGraphTypeTests.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/Types/Composite/AutoRegisteringInterfaceGraphType.cs
- src/GraphQL/Types/Composite/AutoRegisteringObjectGraphType.cs
- src/GraphQL/Types/Composite/AutoRegisteringOutputHelper.cs
Replaces #3414
This is a breaking change --- but (due to a bug) ONLY if the field that returns an interface type is not nullable.
> Fix check for non-resolved interface type

- src/GraphQL.Tests/Types/AutoRegisteringObservableTests.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/Resolvers/ObservableFromAsyncEnumerable.cs
- src/GraphQL/Resolvers/SourceStreamMethodResolver.cs
- src/GraphQL/Types/Composite/AutoRegisteringOutputHelper.cs
- src/GraphQL/Types/TypeInformation.cs
Enables IAsyncEnumerable subscription support for .NET Standard 2.0 projects for use with #3456 .
This PR targets #3456 currently.  If #3456 is merged then it will be updated to target master (7.3) or develop (8.0).
Besides the additional dependency, there are no breaking changes within this PR.
We can likely choose any version for the new `Microsoft.Bcl.AsyncInterfaces` dependency, as we only require the basic interface definitions.  We can also choose to remove the `System.Threading.Tasks.Extensions` dependency, as it is indirectly referenced by the `Microsoft.Bcl.AsyncInterfaces` dependency.  I left it in, just as Microsoft did with the `Microsoft.Extensions.DependencyInjection.Abstractions` 7.0.0 nuget package
> Add Microsoft.Bcl.AsyncInterfaces dependency for .NET Standard 2.0 projects

- src/GraphQL/GraphQL.csproj
With this change, the only dependency for .NET 5+ is `GraphQL-Parser`.
> Reduce dependencies for .NET 5+

- .github/workflows/format.yml
- .github/workflows/test-code.yml
- src/GraphQL.sln
- Faster build checks
- Allows to see formatting problems separate from test failures
- Same as server repo
> Separate formatting check

- src/GraphQL.Tests/Types/AutoRegisteringObjectGraphTypeTests.cs
- src/GraphQL/Types/Composite/AutoRegisteringOutputHelper.cs
Fix issue with inherited record equals method being added to output.
When auto-registering a record that inherits another record the inherited record's equals method was added to the output graph type.
This additionally created unwanted input graph types of the base record.
> Fix issue with inherited record equals method being added to output

- src/GraphQL.Tests/Types/ComplexGraphTypeTests.cs
- src/GraphQL.Tests/Utilities/GetGraphTypeFromTypeTests.cs
- src/GraphQL/Builders/FieldBuilder.cs
- src/GraphQL/Extensions/TypeExtensions.cs
- src/GraphQL/Types/Composite/ComplexGraphType.cs
Prevents using graph types as CLR types for `GetGraphTypeFromType` and indirectly `FieldBuilder` and `ArgumentBuilder`
Fixes:
- #3507
Replaces:
- #3509 
This change will cause an exception to be thrown at the exact line of code in error, rather than during schema validation.
> Graph types cannot be used as CLR types

- docs2/site/docs/getting-started/dependency-injection.md
If the items are registered in the DI container, then constructor injection can be preferred over explicit call to `GetRequiredService`.
> Get Query and Mutation via constructor injection

- .github/labeler.yml
- src/Tests.props
https://github.com/dotnet/project-system/blob/main/docs/up-to-date-check.md#copytooutputdirectory-always-vs-preservenewest
> Use PreserveNewest

- src/GraphQL.DataLoader.Tests/Types/QueryType.cs
- src/GraphQL.DataLoader/Extensions/DataLoaderExtensions.cs
Fixes poor design introduced in #3021.
The `Then` methods introduced in #3021 require that the input enumerable list has been iterated to work properly.  Although the xml comments describe this behavior, it is certainly not intuitive.  This was a bad design and should never have been a prerequisite for using these particular `Then` methods.  It's caused a 3-day outage in our servers due to this bad design.
This patch checks if the input list is an `IList` implementation (commonly an array or `List<T>`), indicating that the source list has been enumerated.  If it has not been, it does so via `ToList()`, which is correct and ** **required** ** for proper operation.
Note that another extension method already performs correct handling of lists, executing `LoadAsync` for each member and adding …
> Fix data loader Then method

- src/GraphQL.Tests/Complexity/ComplexityTestBase.cs
- src/GraphQL.Tests/Complexity/ComplexityValidationTests.cs
- src/GraphQL/Validation/Complexity/ComplexityAnalyzer.cs
- src/GraphQL/Validation/Errors/NoFragmentCyclesError.cs
- src/GraphQL/Validation/Rules.Custom/ComplexityValidationRule.cs
Fixes #3527.
There are 2 bugs in fact.
1. `ComplexityValidationRule` should run after all other standard rules. Before fix it was actually run (syncronously) **before** those rules that return non-null visitor. Note that @arguit wrote test with absolutely wrong schema, not StarWars.
2. `ComplexityValidationRule` indeed hangs in infinite while loop.
I successfully fixed the first. Also I added fast check to eliminate all possible problems with complexity analysis. Then I decided to fix the second. I "fixed" it but tests failed. It turned out that the code I added in `ComplexityAnalyzer.cs` is not enough. It was a naive approach. In fact, `NoFragmentCycles` rule should always be run if we use complexity analysis. First I thought to "force-inject" it into list of validation rules but then I …
> Fix of eternal loop in ComplexityAnalyzer in case of fragment cycles

- .github/workflows/build-artifacts-code.yml
- .github/workflows/publish-code.yml
See:
- https://github.com/dotnet/sdk/issues/15607
- https://github.com/dotnet/sdk/issues/30624
- https://github.com/dotnet/sdk/issues/30625
- https://github.com/dotnet/sdk/issues/30624#issuecomment-1432118204
The new error will be downgraded to a warning in the release next month.  Until then we can explicitly specify the output folder as shown in this PR.  Note that the `-o` option will not produce an error for `dotnet pack` at all after the release next month.
> CI fix for .NET SDK 7.0.200

- src/GraphQL/Builders/FieldBuilder.cs
See:
- #3568 
I'd consider this a bug with the design of the new field builder methods.
> Set FieldType.Resolver properly when calling a field builder's ResolveStream methods

- src/Directory.Build.targets
- src/GraphQL.Tests/Subscription/SubscriptionTests.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/Types/Collections/SchemaTypes.cs
- src/GraphQL/Types/Schema.cs
Also see #3213
Yesterday one of our team members found a bug when using field middleware and calling subscription.
Before fix:
```
Shouldly.ShouldAssertException : errors
should be null but was
[GraphQL.Execution.UnhandledError: Error trying to resolve field 'newMessageContent'.
---> System.InvalidOperationException: Expected to find property or method 'newMessageContent' on type 'String' but it does not exist.
at GraphQL.Resolvers.NameFieldResolver.CreateResolver(Type target, String name) in C:\_GITHUB_\graphql-dotnet\src\GraphQL\Resolvers\NameFieldResolver.cs:line 83
at GraphQL.Resolvers.NameFieldResolver.<>c.<Resolve>b__6_0(ValueTuple`2 t) in C:\_GITHUB_\graphql-dotnet\src\GraphQL\Resolvers\NameFieldResolver.cs:line 38
at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKe …
```
> Fix UnhandledError when resolving top-level subscription field

- docs2/site/docs/migrations/migration7.md
- src/GraphQL.StarWars/Types/CharacterInterface.cs
- src/GraphQL.Tests/Bugs/Bug1889.cs
- src/GraphQL.Tests/Initialization/SchemaInitializationTests.cs
- src/GraphQL.Tests/Types/AutoRegisteringInterfaceGraphTypeTests.cs
- src/GraphQL/Types/Collections/SchemaTypes.cs
- src/GraphQL/Types/Composite/AutoRegisteringOutputHelper.cs
- src/GraphQL/Types/Composite/ComplexGraphType.cs
- src/GraphQL/Types/Fields/FieldType.cs
- src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs
fixes #2994
also fixes #1176
@Shane32 I suggest to consider this as a "fix" for #1176. I do not believe that we will split `FieldType` for inputs and outputs or redesign API in some other way. At least I'm sure that it will be opened for years without any progress. Schema validation allows to find all invalid usages during initialization, i.e. early thought in runtime, not at compile time, so I think this is a good compromise and we do not need to break the whole design.
> Only root fields of subscriptions should set StreamResolver; only object output types should set Resolver

- docs2/site/docs/guides/dataloader.md
Noticed a missing `async` keyword on the `FetchAsync` method in `MyOrderItemsDataLoader` class, within the [DI-based data loaders](https://graphql-dotnet.github.io/docs/guides/dataloader/#di-based-data-loaders) Dataloader code example.
> add missing `async` modifier to method in dataloader code example

- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Execution/ResolveFieldContextTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/ResolveFieldContext/IResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContextExtensions.cs
Why does `IResolveFieldContext.InputExtensions` has `IReadOnlyDictionary<string, object?>` type instead of `Inputs`? Because of this I have to cast extensions
```
// actually context.InputExtensions is of type GraphQL.Inputs
if (context.InputExtensions is not IDictionary<string, object?> values || values.Count == 0)
return null;
```
> Add GetInputExtension method

- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL/Utilities/SchemaPrinter.cs
Allow more methods to be overrided. 
This is do to enable custom implementations of the SchemaPrinter the support custom print implementations for Scalars, InputObjects, Unions, Arguments and Enumerations.
> Make SchemaPrinter more flexible

- LICENSE.md
- src/Directory.Build.props
- src/Directory.Build.targets
- src/GraphQL/GraphQL.csproj
Hopefully then the license should appear in Visual Studio, similar to MS packages:
Right now it looks like this:
> Include license in package

- src/GraphQL/Extensions/GraphQLExtensions.cs
It should not parse into `decimal` because that is a floating-point type and could lose precision for large numbers.  `BigInteger` should be used for large integers.
This method is generally only used for schema printing, I think, and so should not effect typical use cases.
> Fix ParseInt for large integers

- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Validation/NoIntrospectionTests.cs
- src/GraphQL/Validation/Errors.Custom/NoIntrospectionError.cs
- src/GraphQL/Validation/Rules.Custom/NoIntrospectionValidationRule.cs
This seems to be an often-asked question, so this PR adds a validation rule for denying introspection queries to the codebase.
> Add custom validation rule for denying introspection queries

- .github/workflows/test-code.yml
This reverts commit 9c2971d370924345051e081d76a702346ec32b97.
Note: `codecov/codecov-action@v4` was removed and replaced with a beta tag.
> Revert "Bump codecov/codecov-action from 3 to 4 (#3711)"

- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.DataLoader.Tests/Types/OrderItemType.cs
- src/GraphQL.DataLoader.Tests/Types/QueryType.cs
- src/GraphQL.MicrosoftDI.Tests/ConnectionBuilderExtensionTests.cs
- src/GraphQL.StarWars/Types/DroidType.cs
- src/GraphQL.StarWars/Types/HumanType.cs
- src/GraphQL.Tests/AuthorizationTests.cs
- src/GraphQL.Tests/Builders/ConnectionBuilderTests.cs
- src/GraphQL.Tests/Types/ComplexGraphTypeTests.cs
- src/GraphQL/Builders/ConnectionBuilder.cs
- src/GraphQL/Builders/ConnectionBuilder_Typed.cs
- src/GraphQL/Builders/FieldBuilder.cs
- src/GraphQL/Types/Composite/ComplexGraphType.cs
Closes #3712 
A couple of questions.
1. There are the following [methods](https://github.com/graphql-dotnet/graphql-dotnet/blob/c2cc6671bf5eea6977f8865d436e2cbbe0659ca8/src/GraphQL/Builders/FieldBuilder.cs#L55)
```c#
public static FieldBuilder<TSourceType, TReturnType> Create(IGraphType type, string name = "default")
public static FieldBuilder<TSourceType, TReturnType> Create([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] Type? type = null, string name = "default")
```
After deprecating the `Name` the `"default"` value should be removed, but it will be a breaking change. Should I open an additional issue to do that in v8/9/whatever? Or should I deprecate it too and create an overload with the `name` as a first argument?
```c#
public static …
```
> Deprecate Name method

- src/GraphQL.ApiTests/net50/GraphQL.MicrosoftDI.approved.txt
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20/GraphQL.MicrosoftDI.approved.txt
- src/GraphQL.MicrosoftDI/ConnectionResolverBuilder.cs
- src/GraphQL.MicrosoftDI/ScopedConnectionBuilderExtensions.cs
- src/GraphQL/Builders/ConnectionBuilder.cs
- src/GraphQL/Builders/ConnectionBuilder_Typed.cs
As discussed [here](https://github.com/graphql-dotnet/graphql-dotnet/pull/3747#discussion_r1367714889) made `ConnectionBuilder` and `FieldBuilder` api more consistent
> ConnectionBuilder.Resolve* return builder instance

- docs2/site/docs/analyzers/GQL001_DefineTheNameInFieldMethod.md
- docs2/site/docs/analyzers/GQL002_NameMethodInvocationCanBeRemoved.md
- docs2/site/docs/analyzers/GQL003_DifferentNamesDefinedByFieldAndNameMethods.md
- docs2/site/docs/analyzers/Overview.md
- src/GraphQL.Analyzers.CodeFixes/FieldNameCodeFixProvider.cs
- src/GraphQL.Analyzers.Tests/FieldNameAnalyzerTests.cs
- src/GraphQL.Analyzers/Constants.cs
- src/GraphQL.Analyzers/Extensions.cs
- src/GraphQL.Analyzers/FieldBuilderAnalyzer.cs
- src/GraphQL.Analyzers/FieldNameAnalyzer.cs
- src/GraphQL.Analyzers/ResolverAnalyzer.cs
The `FieldNameAnalyzer` was extended to support `ConnectionBuilder.Name` in addition to `FieldBuilder.Name`.
The `ComplexGraphType.Connection` and `ConnectionBuilder<TSourceType>.Create` methods were tested on all the use cases the `ComplexGraphType.Field` was tested. The `ConnectionBuilder.Create` (non-generic builder class) has a single test but it should work the same way the `ConnectionBuilder<TSourceType>.Create` works.
> Rewrite the obsolete Name method on ConnectionBuilder

- docs2/site/docs/migrations/migration8.md
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Bugs/Bug1626.cs
- src/GraphQL.Tests/Bugs/Bug256NullableEnumTests.cs
- src/GraphQL.Tests/Bugs/Bug947.cs
- src/GraphQL.Tests/Bugs/Bug956.cs
- src/GraphQL.Tests/Builders/FieldBuilderTests.cs
- src/GraphQL.Tests/Execution/InputConversionTestsBase.cs
- src/GraphQL.Tests/Execution/ResolveFieldContextTests.cs
- src/GraphQL.Tests/NameFieldResolverTests.cs
- src/GraphQL.Tests/ObjectExtensions.cs
- src/GraphQL.Tests/ObjectExtensionsTest.cs
- src/GraphQL.Tests/Types/AutoRegisteringInputObjectGraphTypeTests.cs
- src/GraphQL.Tests/Types/AutoRegisteringObjectGraphTypeCachingTests.cs
- src/GraphQL.Tests/Types/AutoRegisteringObjectGraphTypeTests.cs
- src/GraphQL/Execution/DirectiveInfo.cs
- src/GraphQL/Extensions/ObjectExtensions.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContextExtensions.cs
Prior to making any planned changes to `ToObject`, I think it is necessary to require a reference to the input object graph type.  This will simplify the design and changes to `ToObject` in subsequent PRs.
> ObjectExtensions.ToObject requires mappedType

- docs2/site/docs/analyzers/GQL006_CanNotMatchInputFieldToTheSourceField.md
- docs2/site/docs/analyzers/GQL007_CanNotSetSourceField.md
- src/GraphQL.Analyzers.Tests/InputGraphTypeAnalyzerTests.cs
- src/GraphQL.Analyzers/Constants.cs
- src/GraphQL.Analyzers/Extensions.cs
- src/GraphQL.Analyzers/InputGraphTypeAnalyzer.cs
Fixes #3775 
It appears that it's possible to get overridden methods based on the semantic model without the source code. So the limitation `when the source code of one of the base types is not available` was removed.
> Ignore InputObjectGraphType analysis if type overrides ParseDictionary

- docs2/site/docs/analyzers/.vscode/settings.json
- docs2/site/docs/analyzers/GQL006_CanNotMatchInputFieldToTheSourceField.md
- docs2/site/docs/analyzers/GQL007_CanNotSetSourceField.md
- docs2/site/docs/analyzers/GQL010_CanNotResolveInputSourceTypeConstructor.md
- docs2/site/docs/analyzers/Overview.md
- src/GraphQL.Analyzers.Tests/InputGraphTypeAnalyzerTests.Constructors.cs
- src/GraphQL.Analyzers.Tests/InputGraphTypeAnalyzerTests.Fields.cs
- src/GraphQL.Analyzers/AnalyzerReleases.Unshipped.md
- src/GraphQL.Analyzers/Helpers/Constants.cs
- src/GraphQL.Analyzers/Helpers/DiagnosticIds.cs
- src/GraphQL.Analyzers/Helpers/HelpLinks.cs
- src/GraphQL.Analyzers/InputGraphTypeAnalyzer.Constructors.cs
- src/GraphQL.Analyzers/InputGraphTypeAnalyzer.Fields.cs
- src/GraphQL.Analyzers/InputGraphTypeAnalyzer.cs
- src/GraphQL.ApiTests/BomTests.cs
- src/GraphQL.sln
Closes #3774.
Notes:
- I made the `InputGraphTypeAnalyzerTests` partial and moved the fields validation into `.Fields` and constructor validation into `.Constructors`. Nothing changed in the fields validation logic.
- the analyzer diagnostic is reported also on `abstract` source types.
- the analyzer is skipped on an open generic source type
```c#
public class CustomInputObjectGraphType<TSource> : InputObjectGraphType<TSource>
where TSource : MySource
```
- the diagnostic also reported when multiple public constructors annotated with `[GraphQLConstructor]`
- there are no tests but I tested manually that everything works also with structs, records, and records with primary constructors
> Verify input source type constructors

- docs2/site/docs/migrations/migration8.md
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.Tests/Execution/InputConversionTestsBase.cs
- src/GraphQL.Tests/Types/AutoRegisteringInputObjectGraphTypeTests.cs
- src/GraphQL.sln
- src/GraphQL/Extensions/ObjectExtensions.cs
- src/GraphQL/Types/Composite/AutoRegisteringHelper.cs
- src/GraphQL/Types/Composite/AutoRegisteringInputObjectGraphType.cs
- src/GraphQL/Types/TypeInformation.cs
AutoRegisteringInputObjectGraphType includes read-only properties when the property name matches a parameter in the chosen constructor.
> AutoRegisteringInputObjectGraphType includes certain read-only properties

- src/Directory.Build.targets
See:
- https://github.com/dotnet/docs/blob/5423d3e2ca24642a82d32575ea1d17d18c3fd04f/docs/core/compatibility/sdk/8.0/trimming-unsupported-targetframework.md
> Configure trim analyzer only for .NET 6+ projects

- src/GraphQL.Tests/Types/AutoRegisteringObjectGraphTypeTests.cs
- src/GraphQL/Types/Composite/AutoRegisteringOutputHelper.cs
Aligns with changed behavior in #3782 .  This could be considered both a bug fix and a breaking change.  Only public properties were intended to be registered, but a public properties having a private getter was incorrectly registered also.  This change fixes that so only public properties with a public getter will be registered.
> Ensure only public properties are registered in AutoRegisteringObjectGraphType

- src/GraphQL.Analyzers.Tests/InputGraphTypeAnalyzerTests.Fields.cs
- src/GraphQL.Analyzers/Helpers/Constants.cs
- src/GraphQL.Analyzers/InputGraphTypeAnalyzer.Fields.cs
> InputGraphTypeAnalyzer choose constructor by the same rules used in runtime

- src/GraphQL.ApiTests/GraphQL.DataLoader.approved.txt
- src/GraphQL.DataLoader/DataLoaderContextAccessor.cs
- src/GraphQL.DataLoader/DataLoaderDocumentListener.cs
- src/GraphQL.DataLoader/IDataLoaderContextAccessor.cs
As discussed in #3777, this PR changes the null annotations for `IDataLoaderContextAccessor.Context` to be non-null. This supports the nullability contract when the property is used correctly (e.g., inside of a document execution) and when the `DataLoaderDocumentListener` is registered
> Make IDataLoaderContextAccessor.Context non-null

- src/GraphQL.MemoryCache/MemoryDocumentCache.cs
- src/GraphQL.Tests/Caching/MemoryCacheTests.cs
MemoryDocumentCache was essentially useless, not passing on cached documents to the document executer, nor storing parsed documents and saving them in the cache.  Broke during 7.0 transition to `IConfigureExecution` in #3272 .  Added tests to ensure the cache's ExecuteAsync method works correctly in the future.
> Fix document caching and add tests

- src/GraphQL.Analyzers.CodeFixes/FieldBuilderCodeFixProvider.cs
- src/GraphQL.Analyzers.Tests/FieldBuilderAnalyzerTests.cs
This fixes the line break after the last argument mentioned [here](https://github.com/graphql-dotnet/graphql-dotnet/pull/3824#issuecomment-1856104581).
Additionally, it tries to keep the code comments during the rewrite. There are still a few cases when the comment can be lost. For example, in the following code, the comments `// a` and `/* b */` will be lost:
```c#
Field<StringGraphType>(
// a
/* b /* "name" /* c */, // d
...
```
I hope folks will forgive me for a little work to restore them manually 🙄
Also, it sometimes adds a line break before the comments that shouldn't appear. I checked the altered code returned from the `docEditor.GetChangedDocument();`, and it looks correct but breaks somewhere deep in Roslyn infra.
> Fix FieldBuilderCodeFixProvider formatting and try preserve code comments

- src/GraphQL.Analyzers.CodeFixes/GraphQL.Analyzers.CodeFixes.csproj
- src/GraphQL.Analyzers/GraphQL.Analyzers.csproj
Fixes #3829.
Note, in the test project I still use v4.6.0 to allow the use of newer language features such as file-scoped namespaces in the analyzed source.
> Downgrade Microsoft.CodeAnalysis packages to v3.11.0 to support older compilers

- src/GraphQL.Tests/Instrumentation/OpenTelemetryTests.cs
- src/GraphQL/Telemetry/GraphQLTelemetryOptions.cs
- src/GraphQL/Telemetry/GraphQLTelemetryProvider.cs
> Update the `GraphQLTelemetryOptions.Filter` delegate to not create any downstream traces when `false`

- docs2/site/docs/getting-started/transport.md
- docs2/site/sitemap.yml
My proposition for `GraphQL.Transport` namespace docs page
> Add transport docs page, update sitemap

- src/GraphQL.Tests/Subscription/SubscriptionExecutionStrategyTests.cs
- src/GraphQL.Tests/Utilities/SchemaBuilderTests.cs
- src/GraphQL/Utilities/SchemaBuilder.cs
- src/GraphQL/Utilities/TypeSettings.cs
- src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs
Fixes #3580 
Adds schema validation to ensure that `StreamResolver` is set for fields of root subscription types.  This is a non-breaking change because without the validation, attempting to resolve these fields would fail at runtime.
Trying to write a fix for #3580 I found two bugs in the schema-first SchemaBuilder (as far as I can tell).
- `Include` does not include configurations via `ForAll`
- Subscriptions don't work properly when the `schema` definition is listed after the subscription definition
> Schema builder fixes; add schema validation of subscription fields

- src/GraphQL.Tests/Subscription/SubscriptionExecutionStrategyTests.cs
- src/GraphQL.Tests/Subscription/SubscriptionSchema.cs
- src/GraphQL.Tests/Subscription/SubscriptionTests.cs
- src/GraphQL/Resolvers/ObservableAdapter.cs
- src/GraphQL/Resolvers/SourceStreamMethodResolver.cs
- src/GraphQL/Resolvers/SourceStreamResolver.cs
The hard part was updating all the tests...
> Support subscriptions of value types

- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL/Attributes/DirectiveAttribute.cs
Samples and tests in PR #3885
This new directive mirrors the existing MetadataAttribute which allows adding arbitrary metadata to type-first schemas.
> Add DirectiveAttribute

- docs2/site/docs/migrations/migration8.md
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Utilities/Visitors/PatternMatchingVisitorTests.cs
- src/GraphQL/Attributes/DirectiveAttribute.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/Types/Directives/Custom/PatternMatchingDirective.cs
- src/GraphQL/Utilities/Visitors/Custom/PatternMatchingVisitor.cs
- src/GraphQL/Validation/Rules.Custom/InputFieldsAndArgumentsOfCorrectLength.cs
This PR includes a new/better sample for directive-based validation, which may be useful.  Then I noticed that we were missing `DirectiveAttribute` for applying directives to type-first schemas.  So I added that in #3886 .
> Add PatternMatchingDirective and PatternMatchingVisitor sample

- src/GraphQL.Tests/Types/AutoRegisteringObjectGraphTypeTests.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContextExtensions.cs
- src/GraphQL/Types/Composite/AutoRegisteringHelper.cs
- Most of TryGetArgument logic moved to TryGetArgumentExact
- GetArgumentInternal now calls TryGetArgumentExact as argument names do not need to pass through name conversion since `QueryArgument.Name` at runtime will contain the converted name.
- TryGetArgumentExact has shortcut logic when the value is null or can be directly coerced to the target type
> GetArgument improvements

- docs2/site/docs/migrations/migration8.md
- src/GraphQL.ApiTests/GraphQL.MemoryCache.approved.txt
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.MemoryCache/MemoryCacheGraphQLBuilderExtensions.cs
- src/GraphQL.Tests/Types/AutoRegisteringInterfaceGraphTypeTests.cs
- src/GraphQL/Extensions/GraphQLBuilderExtensions.cs
- src/GraphQL/Extensions/TypeExtensions.cs
- src/GraphQL/Telemetry/GraphQLTelemetryProvider.cs
- src/GraphQL/Types/Composite/AutoRegisteringInterfaceGraphType.cs
- src/GraphQL/Types/Composite/ObjectGraphTypeExtensions.cs
- src/GraphQL/Validation/IVariableVisitor.cs
- src/GraphQL/Validation/ValidationContext.cs
- src/GraphQL/Validation/Variable.cs
- src/GraphQL/Validation/VariableUsage.cs
The deprecated methods removed in this PR, I believe, should be removed in v9 due to these reasons:
- Some `Add...` IGraphQLBuilder methods were replaced by `Use...` methods.  (1) there is an important distinction between `Add` and `Use`, and (2) changes are very easy to fix and all consolidated in the user's startup file
- `IsConcrete` has no useful purpose; it is functionally identical to `!type.IsAbstract`
- Telemetry provider is very new and now is a good time to change `StartActivityAsync` back to `StartActivity` (which is necessary since otherwise it would not be compatible with `AsyncLocal` internals)
- Validation code is all changing anyway
> Remove some deprecated methods

- docs2/site/docs/getting-started/query-validation.md
- src/GraphQL.Tests/Execution/ExecutionHelperTests.cs
- src/GraphQL.Tests/Types/InputObjectGraphTypeTests.cs
- src/GraphQL/Execution/ExecutionHelper.cs
- src/GraphQL/Validation/ValidationContext.cs
- src/GraphQL/Validation/ValidationError.cs
This PR lets `.Validate( ... )` code throw an `ExecutionError` or `ValidationError` without wrapping it within `InvalidValueError`.
Users are encouraged to throw any exception they desire for default wrapping, but (similar to the rest of the library), throwing an `ExecutionError` will pass the error through to the result unchanged.
Also related bug fixes:
- fix location for errors due to validation delegates
- support validation delegates for input object fields within variables
Added more tests
> Support throwing ValidationError from validation delegates, bug fixes

- docs2/site/docs/guides/dataloader.md
This should clear up some of the confusion between `GetOrAddBatchLoader` and `GetOrAddCollectionBatchLoader`.
Fixes #1375
> Update docs for DataLoader `GetOrAdd*Loader`

- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL/Attributes/MapAutoClrTypeAttribute.cs
- src/GraphQL/Types/Collections/AutoRegisteringGraphTypeMappingProvider.cs
Allows users to selectively map CLR types to auto-registering graph types.
> Add MapAutoClrTypeAttribute

- docs2/site/docs/migrations/migration8.md
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Utilities/Visitors/IsPrivateTests.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/Types/Composite/ObjectGraphType.cs
- src/GraphQL/Types/Fields/FieldType.cs
- src/GraphQL/Types/Fields/IFieldType.cs
- src/GraphQL/Types/GraphQLTypeReference.cs
- src/GraphQL/Types/GraphType.cs
- src/GraphQL/Types/IGraphType.cs
- src/GraphQL/Types/Schema.cs
- src/GraphQL/Utilities/SchemaBuilder.cs
- src/GraphQL/Utilities/TypeConfig.cs
- src/GraphQL/Utilities/Visitors/RemovePrivateTypesAndFieldsVisitor.cs
- src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs
These are prerequisites for GraphQL Federation support in #3921 .  This PR targets v8.
Allows schema visitors to set `IGraphType.IsPrivate` or `IFieldType.IsPrivate` to remove a graph type or field from the schema after initialization.  Introspection queries cannot see these graph types or fields, and requests cannot reference them.  This is the only viable solution currently because `SchemaTypes` builds a read-only list during initialization, and similarly the fields cannot be removed from graph types.
For schema-first schemas, skips `IsTypeOf` checks, while allowing to set `IsTypeOf` for other scenarios.
> Add IsPrivate and SkipTypeCheck properties to IGraphType / IFieldType

- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL/Attributes/GraphQLAttribute.cs
- src/GraphQL/Types/Composite/AutoRegisteringHelper.cs
- src/GraphQL/Types/Composite/AutoRegisteringInputObjectGraphType.cs
- src/GraphQL/Types/Composite/AutoRegisteringInterfaceGraphType.cs
- src/GraphQL/Types/Composite/AutoRegisteringObjectGraphType.cs
Prerequisite for GraphQL Federation in #3921 .  Added to v7.9 as this is not a breaking change.  Will add to v8 release notes in a separate PR that targets `develop`.
> Add another Modify overload to GraphQLAttribute

- docs2/site/docs/migrations/migration8.md
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL/Builders/ConnectionBuilder.cs
- src/GraphQL/Builders/ConnectionBuilder_Typed.cs
- src/GraphQL/Builders/FieldBuilder.cs
- src/GraphQL/Types/Fields/IFieldMetadataWriter.cs
- src/GraphQL/Types/Fields/IFieldType.cs
- src/GraphQL/Types/IMetadataWriter.cs
Note: `IFieldMetadataReader` is not added because this would only apply to `IFieldType`.  Extension methods designed for reading field metadata can scope to `IFieldType`, which inherits `IMetadataReader` for using other metadata-reading extension methods.
I did not see any existing extension methods to update with the `IFieldMetadataWriter` constraint.  Most of the methods that use `IMetadataWriter` are authorization methods which will apply to both schemas / objects / fields.
> Add IFieldMetadataWriter

- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL/Types/Composite/ComplexGraphType.cs
Fixes
- #1290
@Shane32 do you know if new methods can cause binary compatibility issues? The new overloads hide the old overload with both optional parameters. Should I target the `develop` branch instead?
> Obsolete Field method receiving expression and optional nullable and type arguments

- docs2/site/docs/migrations/migration8.md
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Utilities/LinkedSchemaTests.AppliedDirectivesAreProperlyRenamed.approved.txt
- src/GraphQL.Tests/Utilities/LinkedSchemaTests.AppliedDirectivesAreProperlyRenamedForAllLocations.approved.txt
- src/GraphQL.Tests/Utilities/LinkedSchemaTests.cs
- src/GraphQL/Builders/FieldBuilder.cs
- src/GraphQL/Extensions/SchemaExtensions.cs
- src/GraphQL/Federation/Extensions/FederationFieldMetadataExtensions.cs
- src/GraphQL/Federation/Extensions/FederationInterfaceMetadataExtensions.cs
- src/GraphQL/Federation/Extensions/FederationMetadataExtensions.cs
- src/GraphQL/Federation/Extensions/FederationObjectMetadataExtensions.cs
- src/GraphQL/Federation/FederationHelper.cs
- src/GraphQL/Types/Directives/AppliedDirective.cs
- src/GraphQL/Types/Schema.cs
- src/GraphQL/Utilities/Visitors/RenameImportedDirectivesVisitor.cs
Now that schemas can be linked, the next step is to make it so that directives that are imported get automatically renamed properly.  This PR adds `FromSchemaUrl` to `AppliedDirective` to allow specifying the schema url that the directive is imported from.  During schema initiailization, any directive that has a `FromSchemaUrl` that matches an `@link` directive will get the proper alias applied to it.  By design, if no match, it is unaffected.  All Federation directives have been updated.
> Allow applied directives to be imported from another schema

- src/GraphQL/Execution/ExecutionContext.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
The `IResolveFieldContext` instance and dictionary are heavily used and so currently use `Interlocked.Exchange` to reuse a cached instance.  The instance is cached per `ExecutionContext` so that concurrent executions each have their own shared field.  This enhances the concept so that it is per thread rather than per execution.  Performance shows nearly the same results with existing test suite (which execute only synchronous fields), but the code is better organized.
Before:
| Method        | UseCaching | Mean       | Error     | StdDev    | Gen0   | Gen1   | Allocated |
|-------------- |----------- |-----------:|----------:|----------:|-------:|-------:|----------:|
| Introspection | False      | 425.171 us | 8.1294 us | 9.6774 us | 9.7656 | 2.9297 | 187.21 KB |
| Hero          | False …
> Use ThreadStatic for cached fields

- docs2/site/docs/migrations/migration8.md
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Validation/ValidationContextTests.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/Validation/ValidationContext.GetRecursivelyReferencedFragments.cs
- src/GraphQL/Validation/ValidationContext.cs
See:
- #3980 
Notes:
- duplicates `ShouldIncludeNode` logic; ideally this code should be consolidated in a separate PR
> Update GetRecursivelyReferencedFragments to allow retrieving only used fragments

- src/GraphQL.SystemTextJson/GraphQL.SystemTextJson.csproj
System.Text.Json < 8.0.4 have all been marked as vulnerable due to https://github.com/advisories/GHSA-hh2w-p6rv-4g7w which relates to calling `DeserializeAsyncEnumerable`.  However, the notice at https://github.com/dotnet/announcements/issues/315 states that this vulnerability only applies to .NET 7.0 and newer, so it is likely that System.Text.Json 4.7.2 has been incorrectly marked as vulnerable.  In fact, `DeserializeAsyncEnumerable` is not even present within System.Text.Json 4.7.2.
This PR ignores the warning (which is treated as an error) so that the project will build.
We should remove the `NoWarn` tag once MS fixes the vulnerability flag on the nuget package
See discussion here:
- https://github.com/dotnet/runtime/issues/104619
> Ignore NU1903 for System.Text.Json 4.7.2

- docs2/site/docs/getting-started/dependency-injection.md
- docs2/site/docs/migrations/migration8.md
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Complexity/LegacyComplexityBasicTests.cs
- src/GraphQL.Tests/Complexity/LegacyComplexityMetaDataTests.cs
- src/GraphQL.Tests/Complexity/LegacyComplexityTestBase.cs
- src/GraphQL.Tests/Complexity/LegacyComplexityTests.cs
- src/GraphQL.Tests/Complexity/LegacyComplexityTestsWithLimits.cs
- src/GraphQL.Tests/Complexity/LegacyComplexityValidationTests.cs
- src/GraphQL.Tests/DI/GraphQLBuilderExtensionTests.cs
- src/GraphQL/Builders/FieldBuilder.cs
- src/GraphQL/Extensions/GraphQLBuilderExtensions.cs
- src/GraphQL/Validation/Complexity/ComplexityAnalayzerMetadataExtensions.cs
- src/GraphQL/Validation/Complexity/LegacyAnalysisContext.cs
- src/GraphQL/Validation/Complexity/LegacyComplexityConfiguration.cs
- src/GraphQL/Validation/Complexity/LegacyComplexityResult.cs
- src/GraphQL/Validation/Complexity/LegacyComplexityVisitor.cs
- src/GraphQL/Validation/Complexity/LegacyFragmentComplexity.cs
- src/GraphQL/Validation/Rules.Custom/LegacyComplexityValidationRule.cs
- src/GraphQL/Validation/ValidationContext.GetRecursivelyReferencedFragments.cs
Prep towards #3989 
- Rename `ComplexityValidationRule` to `LegacyComplexityValidationRule` and mark as obsolete
- Rename `ComplexityConfiguration` to `LegacyComplexityConfiguration` and mark as obsolete
- Rename `AddComplexityAnalyzer` to `AddLegacyComplexityAnalyzer` and mark as obsolete
- Prefix supporting classes and tests with `Legacy`
- Change type condition on `WithComplexityImpact` to `IFieldMetadataWriter`
- Mark `ShouldIncludeNode` as public
- Add migration note
Shouldn't be any changes other than the few changes listed above.
The goal here is to continue to support the existing "v7" complexity analyzer logic throughout the lifetime of v8, removing it in favor of the new analyzer in v9.  Since the calculations of the v7 analyzer are drastically different than the v8 analyzer, …
> Rename ComplexityAnalyzer to LegacyComplexityAnalyzer and mark as obsolete

- docs2/site/docs/migrations/migration8.md
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Bugs/Bug1769.cs
- src/GraphQL.Tests/DI/GraphQLBuilderExtensionTests.cs
- src/GraphQL.Tests/Execution/DocumentExecuterTests.cs
- src/GraphQL.Tests/Instrumentation/OpenTelemetryTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/ExecutionContext.cs
- src/GraphQL/Execution/IExecutionContext.cs
- src/GraphQL/Execution/UnhandledExceptionContext.cs
- src/GraphQL/Extensions/GraphQLBuilderExtensions.cs
In certain cases, such as when an exception was thrown during schema initialization, there was no `ExecutionContext` available, and so both the `Context` and `FieldContext` properties were null, preventing access to any relevant information about the request that caused the failure, and also preventing access to the `RequestServices` property to pull logging services from the DI service provider.
In the past a workaround was implemented by setting the delegate during the execution configuration chain, getting a reference to the options class in the process.  With the newly added property, this is no longer necessary, so the workaround overload has been marked as deprecated.
While the situations where this is applicable were rare, now due to the feature listed below, adding this property …
> Unhandled exception processing enhancements

- src/GraphQL.SystemTextJson/GraphQL.SystemTextJson.csproj
Patch has been fixed; STJ 4.7.2 is no longer marked as vulnerable
> Revert "Ignore NU1903 for System.Text.Json 4.7.2 (#3984)"

- docs2/site/docs/migrations/migration8.md
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.NewtonsoftJson/ExecutionResultJsonConverter.cs
- src/GraphQL.SystemTextJson/ExecutionResultJsonConverter.cs
- src/GraphQL.Tests/Serialization/ExecutionResultTests.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/Execution/Nodes/ArrayExecutionNode.cs
- src/GraphQL/Extensions/EnumerableExtensions.cs
- src/GraphQL/Types/Scalars/BigIntGraphType.cs
- src/GraphQL/Types/Scalars/BooleanGraphType.cs
- src/GraphQL/Types/Scalars/ByteGraphType.cs
- src/GraphQL/Types/Scalars/ComplexScalarGraphType.cs
- src/GraphQL/Types/Scalars/DecimalGraphType.cs
- src/GraphQL/Types/Scalars/FloatGraphType.cs
- src/GraphQL/Types/Scalars/GuidGraphType.cs
- src/GraphQL/Types/Scalars/HalfGraphType.cs
- src/GraphQL/Types/Scalars/IdGraphType.cs
- src/GraphQL/Types/Scalars/IntGraphType.cs
- src/GraphQL/Types/Scalars/LongGraphType.cs
- src/GraphQL/Types/Scalars/SByteGraphType.cs
- src/GraphQL/Types/Scalars/ScalarGraphType.cs
- src/GraphQL/Types/Scalars/ShortGraphType.cs
- src/GraphQL/Types/Scalars/StringGraphType.cs
- src/GraphQL/Types/Scalars/UIntGraphType.cs
- src/GraphQL/Types/Scalars/ULongGraphType.cs
- src/GraphQL/Types/Scalars/UShortGraphType.cs
This change makes it so that when serializing a list of intrinsic types, such as `int[]` for `ListGraphType<IntGraphType>`, the scalar can serialize the entire list at once.  This eliminates at least two allocations per element and it should be much faster to boot. Of course the use case is narrow, but is certainly advantageous if you want to return a large list of metrics or similar values out of GraphQL.  Note that no changes are made for input types.
Given this type-first schema, where each field returns 100 elements:
```cs
public class MyQuery
{
public static int[] Ints { get; } = Enumerable.Range(1, 100).ToArray();
public static string[] Strings { get; } = Enumerable.Range(1, 100).Select(x => x.ToString()).ToArray();
public static Guid[] Guids { get; } = Enumerable.Range(1, …
```
> Optimize scalar lists

- docs2/site/docs/migrations/migration8.md
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Complexity/ComplexityTests.cs
- src/GraphQL.Tests/Utilities/Visitors/PatternMatchingVisitorTests.cs
- src/GraphQL/Attributes/ComplexityAttribute.cs
- src/GraphQL/Attributes/DirectiveAttribute.cs
- src/GraphQL/Validation/Complexity/IFieldComplexityAnalyzer.cs
All type-first attributes are in the `GraphQL` namespace for ease of use.  Two attributes are in the wrong (`GraphQL.Attributes`) namespace:
- `ComplexityAttribute`, not yet released
- `DirectiveAttribute`, released in 7.8
> Move new attributes to correct namespace

- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL/Attributes/GraphQLAttribute.cs
- src/GraphQL/Types/Composite/AutoRegisteringHelper.cs
- src/GraphQL/Types/Composite/AutoRegisteringOutputHelper.cs
- src/GraphQL/Types/Scalars/Enumeration/EnumerationGraphType.cs
Allows for inspecting the source type when modifying graph types, or inspecting the source argument when modifying query arguments.
Prerequisite to supporting `[GraphQLInterface]` via attribute extensibility 'plugins'.
> Extend attribute usage

- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL/Attributes/GraphQLAttribute.cs
- src/GraphQL/Types/Composite/AutoRegisteringHelper.cs
This additional `Modify` overload for GraphQLAttribute was added in #3952 targeting 7.9 as a prerequisite for federation changes in 8.0.  I think the order of arguments should be modified so that the overloads for field modification appear together - e.g. when typing `override` and looking at the intellisense popup.  This is not a breaking change as neither 7.9 nor 8.0 have been released yet.
With this change:
```
// modifies the graph type
public virtual void Modify(GraphQL.Types.IGraphType graphType) { }
public virtual void Modify(GraphQL.Types.IGraphType graphType, System.Type sourceType) { }
// modifies the field type
public virtual void Modify(GraphQL.Types.FieldType fieldType, bool isInputType) { }
public virtual void Modify(GraphQL.Types.FieldType fieldType, bool isInputType, …
```
> Reorder attribute method arguments

- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Initialization/SchemaInitializationTestBase.cs
- src/GraphQL.Tests/Initialization/SchemaInitializationTests.cs
- src/GraphQL/Types/Schema.cs
- src/GraphQL/Utilities/Visitors/AppliedDirectivesValidationVisitor.cs
- src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs
Closes #3875 
Note that until the schema passes basic validation, the applied directives' validation is not run.  And there are a few exceptions that are thrown outside of either validation class.  But for the most part, the validation occurs within those two schema visitors.
> Aggregate schema initialization errors

- docs2/site/docs/migrations/migration8.md
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.MicrosoftDI/ScopedResolveConnectionContextAdapter.cs
- src/GraphQL.MicrosoftDI/ScopedResolveFieldContextAdapter.cs
- src/GraphQL.Tests/Execution/Directives/DirectivesTests.cs
- src/GraphQL/Extensions/ExecutionContextExtensions.cs
- src/GraphQL/Federation/Attributes/FederationResolverAttribute.FederationNonStaticResolver.cs
- src/GraphQL/Federation/Attributes/FederationResolverAttribute.FederationStaticResolver.cs
- src/GraphQL/ResolveFieldContext/IResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ReadonlyResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContextAdapter.cs
- src/GraphQL/Resolvers/ObservableFromAsyncEnumerable.cs
With the new variable parsing in #3424 , the `ExecutionHelper.GetArguments` signature has changed, and it is not preferred to use that method anymore since all the arguments have already been parsed -- it's essentially an internal detail now.  Because of this, code that synthesizes an `IResolveFieldContext` for child fields within a resolver, or any similar code which needs to examine arguments of child fields, needs modification.  This PR adds `IResolveFieldContext.ExecutionContext` so that code can easily pull already-parsed argument values for any part of the document.
> Add IResolveFieldContext.ExecutionContext

- src/GraphQL.Analyzers.Tests/GraphQLExtensionsTests.cs
- src/GraphQL.Analyzers/Helpers/GraphQLExtensions.cs
Unlike `FieldAndNameMethodsCalled_NotGraphQLBuilder_NoDiagnostics`, this test is not coupled to any analyzer, so it's not affected by changes or possible removal of the analyzers.
> Add IsGraphQLSymbol tests

- docs2/site/docs/migrations/migration8.md
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Validation/FieldArgumentsAreValidRuleTests.cs
- src/GraphQL.Tests/Validation/ValidationSchema.cs
- src/GraphQL.Tests/Validation/ValidationTestBase.cs
- src/GraphQL/Builders/FieldBuilder.cs
- src/GraphQL/Types/Fields/FieldType.cs
- src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs
- src/GraphQL/Validation/DocumentValidator.cs
- src/GraphQL/Validation/FieldArgumentsValidationContext.cs
- src/GraphQL/Validation/Rules.Custom/FieldArgumentsAreValidRule.cs
Closes #4046 
Provides a way to parse/validate multiple field arguments together, similar to how ParseDictionary can be used to parse/validate multiple input object fields into the returning object.
> Add validation for field arguments

- src/GraphQL.Tests/Attributes/ParserAttributeTests.cs
- src/GraphQL.Tests/Attributes/ValidateArgumentsAttributeTests.cs
- src/GraphQL.Tests/Attributes/ValidatorAttributeTests.cs
- src/GraphQL/Attributes/ParserAttribute.cs
- src/GraphQL/Attributes/ValidateArgumentsAttribute.cs
- src/GraphQL/Attributes/ValidatorAttribute.cs
Allow Parser, Validator and ValidateArguments attributes to define private method names when the type argument is the same as the type where the attribute is applied.
> Allow private methods in Parser/Validator/ValidateArguments attributes 

- docs2/site/docs/migrations/migration8.md
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Attributes/DefaultAstValueAttributeTests.cs
- src/GraphQL/Attributes/DefaultAstValueAttribute.cs
- src/GraphQL/Types/Schema.cs
This attribute sets the default value of an input object's field or an output type's field argument to a `GraphQLValue` instance parsed from the provided string.  Already there is functionality within the schema initialization code to create an instance of the correct object type from the `GraphQLValue` instance and apply it during schema initialization.
> Add DefaultAstValueAttribute to set default values of complex objects in type-first schemas

- .git-blame-ignore-revs
The `.git-blame-ignore-revs` file is used in Git to specify a list of commits that should be ignored when running the `git blame` command.
> Add .git-blame-ignore-revs to improve git blame

- .git-blame-ignore-revs
As I am looking at the history changes, I also noticed this hash that should also be ignore.
> Update .git-blame-ignore-revs to exclude #1776

- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL/Types/Composite/ListGraphType.cs
- src/GraphQL/Types/Composite/NonNullGraphType.cs
> Mark NonNullGraphType<T> and ListGraphType<T> constructors as obsolete

- src/GraphQL.Tests/Bugs/Bug4083.cs
- src/GraphQL.Tests/Bugs/Issue4060.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/ExecutionContext.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/Validation/ValidationContext.cs
Fixes queries such as these:
```graphql
query heroQuery($id: Int!) {
...fragment1
...fragment2
}
fragment fragment1 on Query {
hero(id: $id) {
id
}
}
fragment fragment2 on Query {
hero(id: $id) {
name
}
}
```
Unfortunately this fix is not compatible with the patch described in #4060 - but it makes it no worse either.  See changes to `Issue4060.cs` tests and below notes.
> Fix argument parsing for merged selection sets

- docs2/site/docs/migrations/migration8.md
Changed in https://github.com/graphql-dotnet/graphql-dotnet/pull/3761 ; I can't remember why.
We can consider reverting behavior, or altering behavior so that `SchemaTypes` inspects all types a second time to ensure that `ResolvedType` is set properly, or some such thing.  It's not a bad thing to have `Initialize` occur prior to initialization, but for certain scenarios, such as perhaps the `_Entity` type of GraphQL Federation, one would want the schema fully initialized prior to `Initialize` being called.  Just depends on the use case.
> Add initialization migration note

- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Utilities/Visitors/TransitiveInterfaceVisitorTests.cs
- src/GraphQL/Types/Schema.cs
- src/GraphQL/Utilities/Visitors/TransitiveInterfaceVisitor.cs
There is no schema validation rule to validate that transitively implemented interfaces are directly implemented by all implementing types.  There are two approaches to fix the problem, both of which are available to us in version 8:
- This would be considered a new feature, widening the supported requests, not narrowing
- Easier to use / more C#-like interface implementation pattern
- Resolvers can only execute against a concrete object type, so no problems there
- Would change the introspection query (for affected schemas)
- Within minor version bumps, we allow changes that better enforce the graphql specification, even if doing so "breaks" an existing schema
- Requires the developer to directly reference all transitively-referenced interfaces
- This would break any implementation that …
> Auto-add transitively implemented interfaces to object and interface types

- src/GraphQL/GlobalSwitches.cs
This default value was changed for v8 but the comment not updated.  (See [migration notes.](https://graphql-dotnet.github.io/docs/migrations/migration8/))
> Fix xml comment on InferFieldNullabilityFromNRTAnnotations

- docs2/site/docs/getting-started/dependency-injection.md
This is the only way that I could get no errors using this example I would get the following error
`Cannot implicitly convert type 'System.Threading.Tasks.Task<System.Collections.Generic.List<RSINET.Core.DataModels.Pattern>>' to 'System.Threading.Tasks.Task<object?>' `
> Update DI sample

- samples/GraphQL.AotCompilationSample.CodeFirst/GraphQL.AotCompilationSample.CodeFirst.csproj
- samples/GraphQL.AotCompilationSample.CodeFirst/Program.cs
- samples/GraphQL.AotCompilationSample.TypeFirst/GraphQL.AotCompilationSample.TypeFirst.csproj
- samples/GraphQL.AotCompilationSample.TypeFirst/Program.cs
- src/GraphQL.ApiTests/net50/GraphQL.MicrosoftDI.approved.txt
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.MicrosoftDI/MicrosoftDIGraphQLBuilderExtensions.cs
- src/GraphQL/Extensions/GraphQLBuilderExtensions.cs
- src/GraphQL/Extensions/SchemaExtensions.cs
The AOT samples previously written for .NET 7 do not work properly for .NET 8 due to changes in the NativeAOT compiler and trim analysis.  .NET 8 also places additional restrictions on the MS DI service provider and JSON serializer, requiring additional changes.  This PR implements the necessary changes and updates the samples to work under .NET 8.
Note that implementation of the `Microsoft.Extensions.DependencyInjection.VerifyOpenGenericServiceTrimmability` runtime configuration switch would provide for a better experience, but I cannot figure out how to get it to work via the csproj, either with a MSBuild property or via `RuntimeHostConfigurationOption`.
See:
- https://github.com/dotnet/runtime/blob/v8.0.0/docs/workflow/trimming/feature-switches.md
> Bump NativeAOT samples to .NET 8; fix more attributes

- .github/workflows/test-code.yml
Apollo Router 1.60 does not support federation v1 supergraphs
> Lock federation 1 supergraph testing to Apollo Router 1.59

- docs2/site/docs/migrations/migration8.md
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Types/InputObjectGraphTypeTests.cs
- src/GraphQL/Extensions/FieldExtensions.cs
- src/GraphQL/Extensions/ObjectExtensions.cs
- src/GraphQL/Types/Composite/ComplexGraphType.cs
- src/GraphQL/Types/Composite/InputObjectGraphType.cs
- src/GraphQL/Utilities/SchemaPrinter.cs
Allows the developer to exclude specific fields from the graph from being mapped to the CLR type automatically.  The developer must override ParseDictionary to apply the input to the CLR object.  Note that IsValidDefault and ToAST methods also skip these fields, and if necessary, the developer should override those methods as well.
See discussion:
- https://github.com/graphql-dotnet/graphql-dotnet/discussions/4123
Added doc below:
---
A new extension method, `NoClrMapping`, has been introduced to give you fine-grained control over how input object fields are mapped to CLR types. In many scenarios, your input types may include fields that are computed or require custom processing before being set on your CLR model. For example, you might have a CLR type with a single `FullName` property …
> Add NoClrMapping option for input fields

- docs2/site/docs/migrations/migration8.md
- src/GraphQL.ApiTests/GraphQL.MemoryCache.approved.txt
- src/GraphQL.MemoryCache/MemoryDocumentCache.cs
- src/GraphQL.MemoryCache/MemoryDocumentCacheOptions.cs
- src/GraphQL.Tests/Caching/MemoryCacheTests.cs
This fix/change prevents the document cache from matching on a query previously cached for one schema when the same query is requested for another schema.
See:
- #4121
Added docs:
---
Document caching now supports unique cache keys for applications using multiple or dynamic schemas. The cache key has been enhanced to include an extra property computed by the new `AdditionalCacheKeySelector` delegate. By default, this delegate distinguishes between schema-first and code-first implementations by returning the schema instance for schema-first and dynamic schemas (those that are direct implementations of `Schema`), and the schema type for code-first and type-first schemas (schemas that derive from `Schema`). This change ensures that cached documents are uniquely identified even when multiple …
> Make memory cache unique per schema

- src/GraphQL.Tests/Types/AutoRegisteringInputObjectGraphTypeTests.cs
- src/GraphQL/Extensions/ObjectExtensions.Compiled.cs
- src/GraphQL/Extensions/ObjectExtensions.cs
- src/GraphQL/Types/Composite/AutoRegisteringHelper.cs
Currently `AutoRegisteringInputObjectGraphType` cannot deserialize to a struct that has no explicit constructor.  This patch fixes the logic so if no explicitly defined constructors are found, the deserialization logic will use the implicit constructor.  This would be natural for code such as this, which was previously unsupported due to no explicitly defined constructors:
```cs
public struct MyStruct
{
public int Id { get; set; }
public string Name { get; set; }
}
```
This change does not affect any existing schemas, and as such is considered a bugfix.
See:
- #4129
> Allow implicit struct constructors

- docs2/site/docs/analyzers/overview.md
The information provided on the Overview page wasn't very useful. Replaced it with a list of available analyzers.
> Include a list of analyzers on the Overview page

- Directory.Build.props
- samples/GraphQL.Federation.SchemaFirst.Sample1/MyFederatedResolver.cs
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Federation/EntityResolverTests.cs
- src/GraphQL.Tests/Federation/InterfaceEntityTests.cs
- src/GraphQL.Tests/Federation/MediaEntityTests.cs
- src/GraphQL/Extensions/GraphQLExtensions.cs
- src/GraphQL/Federation/Attributes/FederationResolverAttribute.FederationNonStaticResolver.cs
- src/GraphQL/Federation/Attributes/FederationResolverAttribute.FederationStaticResolver.cs
- src/GraphQL/Federation/Attributes/KeyAttribute.cs
- src/GraphQL/Federation/Extensions/FederationGraphTypeExtensions.cs
- src/GraphQL/Federation/Resolvers/EntityResolver.cs
- src/GraphQL/Federation/Resolvers/FederationResolver.cs
- src/GraphQL/Federation/Resolvers/FederationResolverBase.cs
- src/GraphQL/Federation/Resolvers/IFederationResolver.cs
- src/GraphQL/Federation/Resolvers/Representation.cs
- src/GraphQL/Resolvers/MemberResolver.cs
- src/GraphQL/Types/Composite/AutoRegisteringInterfaceGraphType.cs
- src/GraphQL/Types/Composite/AutoRegisteringOutputHelper.cs
- src/GraphQL/Types/Composite/InterfaceGraphType.cs
- src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs
This allows for resolving interfaces within GraphQL federation.  Unfortunately it requires breaking changes.  While possible, it does not seem practical to implement the required functionality as non-breaking changes.
The biggest breaking change is to `IFederationResolver` which now uses `IComplexGraphType` instead of `IObjectGraphType`.  This will break custom implementations of the resolver as seen in Sample1, either if the interface is directly implemented, or if they derive from `FederationResolverBase`.
Extension methods to configure the schema have not changed, so it is possible or even likely that most federation schemas will not break with these changes.
> Support federation interface resolution

- docs2/site/docs/migrations/migration9.md
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL/Utilities/Visitors/ParseLinkVisitor.cs
(Duplicate of extension method in SchemaExtensions)
Fixes #4107
> Remove ParseLinkVisitor.Run

- docs2/site/docs/migrations/migration9.md
- src/GraphQL.Tests/Types/AutoRegisteringInterfaceGraphTypeTests.cs
- src/GraphQL.Tests/Types/AutoRegisteringObjectGraphTypeTests.cs
- src/GraphQL/Types/Composite/AutoRegisteringHelper.cs
> Remove async suffix from ValueTask and IAsyncEnumerable

- docs2/site/docs/migrations/migration8.md
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Utilities/Visitors/DeprecatedTypeReferenceVisitorTests.cs
- src/GraphQL.Tests/Validation/DeprecatedElementsValidationRuleTests.cs
- src/GraphQL/Utilities/Visitors/Custom/DeprecatedTypeReferenceVisitor.cs
- src/GraphQL/Validation/Rules.Custom/DeprecatedElementsValidationRule.cs
Two new classes have been added to help manage deprecated schema elements more effectively:
[`DeprecatedTypeReferenceVisitor`](src/GraphQL/Utilities/Visitors/Custom/DeprecatedTypeReferenceVisitor.cs) and
[`DeprecatedElementsValidationRule`](src/GraphQL/Validation/Rules.Custom/DeprecatedElementsValidationRule.cs).
These classes work together to provide comprehensive deprecation management at both the schema and query validation levels.
The [`DeprecatedTypeReferenceVisitor`](src/GraphQL/Utilities/Visitors/Custom/DeprecatedTypeReferenceVisitor.cs) is a schema visitor that identifies non-deprecated fields that directly reference deprecated types during schema initialization. This helps maintain schema consistency by flagging potential issues where deprecated types are still being referenced …
> Add QOL validation rule and schema visitor to detect use of deprecated elements

- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL/Extensions/SchemaExtensions.cs
- src/GraphQL/Federation/Types/FederationPrintOptions.cs
- src/GraphQL/Utilities/PrintOptions.cs
- src/GraphQL/Utilities/Visitors/RemoveImportedTypesVisitor.cs
Changes `{ _service { sdl } }` printing to only exclude federation types and directives.
This is a behavioral change, but considered a bug fix.
> Update federation printing
