- src/GraphQL.GraphiQL/Controllers/GraphQLController.cs
- src/GraphQL.Tests/QueryTestBase.cs
- src/GraphQL.Tests/StarWars/StarWarsData.cs
- src/GraphQL.Tests/StarWars/StarWarsQuery.cs
- src/GraphQL/EnumerableExtensions.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Types/FieldType.cs
- src/GraphQL/Types/GraphType.cs
Hey, here's a first take of supporting asynchronous field resolution. I chose to keep the synchronous method in place and async support beside it because I believe most use cases end up requiring both. I'm happy to add tests and examples of use, but I wanted to check if the contribution is welcome, and what was thought of the approach first.
> Async field resolution support

- README.md
- src/GraphQL.Tests/Execution/MutationTests.cs
- src/GraphQL.Tests/GraphQL.Tests.csproj
- src/GraphQL.Tests/QueryTestBase.cs
- src/GraphQL/Types/ResolveFieldContext.cs
These tests prove that basic mutations work.
> Add tests to verify that mutations work.  #9

- package.json
- src/GraphQL.Tests/Execution/InputConversionTests.cs
- src/GraphQL.Tests/Execution/MutationTests.cs
- src/GraphQL.Tests/Execution/VariablesTests.cs
- src/GraphQL.Tests/GraphQL.Tests.csproj
- src/GraphQL.Tests/QueryTestBase.cs
- src/GraphQL.Tests/Types/SchemaTests.cs
- src/GraphQL/EnumerableExtensions.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/Inputs.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/Language/VariableType.cs
- src/GraphQL/Language/Variables.cs
- src/GraphQL/ObjectExtensions.cs
- src/GraphQL/StringExtensions.cs
- src/GraphQL/Types/GraphType.cs
- src/GraphQL/Types/GraphTypesLookup.cs
- test-local.ps1
* Fixed some issues with coercing Argument variables.
* Fixed some issues with coercing list objects.
* Added extensions to convert from a Dictionary to Object.
> A start of input objects. #12

- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/ExecutionContext.cs
- src/GraphQL/Types/ResolveFieldContext.cs
> Add missing fields to ResolveFieldContext.

- README.md
- src/GraphQL.Tests/Execution/UnionInterfaceTests.cs
- src/GraphQL.Tests/GraphQL.Tests.csproj
- src/GraphQL.Tests/StarWars/StarWarsIntrospectionTests.cs
- src/GraphQL/EnumerableExtensions.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/ResolveFieldResult.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/Introspection/__Type.cs
- src/GraphQL/TypeExtensions.cs
- src/GraphQL/Types/GraphQLAbstractType.cs
- src/GraphQL/Types/GraphType.cs
- src/GraphQL/Types/GraphTypesLookup.cs
- src/GraphQL/Types/InterfaceGraphType.cs
- src/GraphQL/Types/UnionGraphType.cs
Tests cases taken from [here](https://github.com/graphql/graphql-js/blob/f9a287754898faf850101045f7d63000ea1b2159/src/execution/__tests__/union-interface.js).
See #11
> Union support.

- README.md
- src/GraphQL.Tests/Execution/UnionInterfaceTests.cs
- src/GraphQL.Tests/StarWars/CharacterInterface.cs
- src/GraphQL.Tests/StarWars/DroidType.cs
- src/GraphQL.Tests/StarWars/HumanType.cs
- src/GraphQL.Tests/Types/SchemaTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Introspection/__Type.cs
- src/GraphQL/Types/GraphQLAbstractType.cs
- src/GraphQL/Types/GraphTypesLookup.cs
- src/GraphQL/Types/InterfaceGraphType.cs
- src/GraphQL/Types/ObjectGraphType.cs
- src/GraphQL/Types/Schema.cs
- src/GraphQL/Types/UnionGraphType.cs
* IsTypeOf allows you to replace usages of ResolveType
> Add IsTypeOf

- src/GraphQL.Tests/Types/SchemaTests.cs
- src/GraphQL/Types/GraphTypesLookup.cs
- src/GraphQL/Types/Schema.cs
> Provide a way to register additional types.

- src/GraphQL.GraphiQL/App_Start/WebApiConfig.cs
- src/GraphQL.GraphiQL/Bootstrapper.cs
- src/GraphQL.GraphiQL/Controllers/GraphQLController.cs
- src/GraphQL.GraphiQL/GraphQL.GraphiQL.csproj
- src/GraphQL.GraphiQL/SimpleContainerDependencyResolver.cs
- src/GraphQL.GraphiQL/Web.config
- src/GraphQL.Tests/Execution/Cancellation/CancellationTests.cs
- src/GraphQL.Tests/Execution/VariablesTests.cs
- src/GraphQL.Tests/QueryTestBase.cs
- src/GraphQL.Tests/SimpleContainer.cs
- src/GraphQL/Execution/DocumentExecuter.cs
* Attempt to catch all errors instead of letting them propagate
* Updated GraphiQL sample to use DocumentWriter.
* Setup GraphiQL example to use built-in DI.
> Updates for error handling, GraphiQL sample

- README.md
- src/GraphQL.Tests/Validation/ArgumentsOfCorrectTypeTests.cs
- src/GraphQL.Tests/Validation/ScalarLeafTests.cs
- src/GraphQL.Tests/Validation/ValidationTestBase.cs
- src/GraphQL/GraphQLExtensions.cs
- src/GraphQL/Types/FloatGraphType.cs
- src/GraphQL/Utilities/AstPrinter.cs
> Finish tests for ArgumentOfCorrectType validation

- README.md
- src/GraphQL.Tests/Validation/ScalarLeafTests.cs
- src/GraphQL/Validation/Rules/ScalarLeafs.cs
- src/GraphQL/Validation/ValidationContext.cs
> Finish ScalarLeaf tests

- README.md
- src/GraphQL.Tests/Execution/VariablesTests.cs
- src/GraphQL.Tests/GraphQL.Tests.csproj
- src/GraphQL.Tests/Validation/LoneAnonymousOperationTests.cs
- src/GraphQL.Tests/Validation/UniqueOperationNamesTests.cs
- src/GraphQL.Tests/Validation/ValidationErrorAssertion.cs
- src/GraphQL.Tests/Validation/ValidationTestBase.cs
- src/GraphQL.Tests/Validation/ValidationTestConfig.cs
- src/GraphQL.Tests/Validation/VariablesInAllowedPositionTests.cs
- src/GraphQL/EnumerableExtensions.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/GraphQLExtensions.cs
- src/GraphQL/Language/Field.cs
- src/GraphQL/Language/FragmentDefinition.cs
- src/GraphQL/Language/IHaveSelectionSet.cs
- src/GraphQL/Language/Operation.cs
- src/GraphQL/Types/GraphQLAbstractType.cs
- src/GraphQL/Validation/DocumentValidator.cs
- src/GraphQL/Validation/NodeVisitorMatchFuncListener.cs
- src/GraphQL/Validation/Rules/LoneAnonymousOperation.cs
- src/GraphQL/Validation/Rules/UniqueOperationNames.cs
- src/GraphQL/Validation/Rules/VariablesInAllowedPosition.cs
- src/GraphQL/Validation/TypeInfo.cs
- src/GraphQL/Validation/ValidationContext.cs
* Tests for UniqueOperationNames
* Tests for LoneAnonymousOperation
* Failing tests for VariablesInAllowedPosition
#10
> Tests + VariablesInAllowedPosition Rule

- src/GraphQL.StarWars/Types/EpisodeEnum.cs
- src/GraphQL.Tests/Builders/FieldBuilderTests.cs
- src/GraphQL/Builders/FieldBuilder.cs
> Update GetArgument<T> to use Argument<T>

- README.md
- src/GraphQL.Tests/Execution/ResolveFieldContextTests.cs
- src/GraphQL.Tests/Execution/VariablesTests.cs
- src/GraphQL.Tests/GraphQL.Tests.csproj
- src/GraphQL.Tests/Validation/NoUndefinedVariablesTests.cs
- src/GraphQL.Tests/Validation/ValidationTestBase.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/Validation/DocumentValidator.cs
- src/GraphQL/Validation/EnterLeaveListener.cs
- src/GraphQL/Validation/Rules/ArgumentsOfCorrectType.cs
- src/GraphQL/Validation/Rules/LoneAnonymousOperation.cs
- src/GraphQL/Validation/Rules/NoUndefinedVariables.cs
- src/GraphQL/Validation/Rules/ScalarLeafs.cs
- src/GraphQL/Validation/Rules/UniqueOperationNames.cs
- src/GraphQL/Validation/Rules/VariablesInAllowedPosition.cs
- src/GraphQL/Validation/ValidationContext.cs
- src/GraphQL/Validation/ValidationError.cs
> Add NoUndefinedVariables rule.

- README.md
- src/GraphQL.Tests/GraphQL.Tests.csproj
- src/GraphQL.Tests/Utilities/StringUtilsTests.cs
- src/GraphQL.Tests/Validation/KnownTypeNamesTests.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/Utilities/StringUtils.cs
- src/GraphQL/Validation/DocumentValidator.cs
- src/GraphQL/Validation/Rules/KnownTypeNames.cs
* Re-order validation rules based on presidence
* Add StringUtils which includes a QuotedOrList and a SuggestionList
which is based on string similarity of a given misspelled input and
possible matching options.
> KnownTypeNames validation rule

- src/GraphQL.Tests/Bugs/Bug118SpacesInTypeNameTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
> Fix validation check for non-null Input values

- src/GraphQL.Tests/GraphQL.Tests.csproj
- src/GraphQL.Tests/Validation/DefaultValuesOfCorrectTypeTests.cs
- src/GraphQL.Tests/Validation/ValidationTestBase.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/Utilities/StringUtils.cs
- src/GraphQL/Validation/DocumentValidator.cs
- src/GraphQL/Validation/Rules/DefaultValuesOfCorrectType.cs
> Default values of correct type validation rule

- README.md
- src/GraphQL.Tests/GraphQL.Tests.csproj
- src/GraphQL.Tests/Validation/KnownArgumentNamesTests.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/Invariant.cs
- src/GraphQL/Language/Argument.cs
- src/GraphQL/Validation/DocumentValidator.cs
- src/GraphQL/Validation/Rules/KnownArgumentNames.cs
- src/GraphQL/Validation/Rules/VariablesInAllowedPosition.cs
- src/GraphQL/Validation/TypeInfo.cs
- src/GraphQL/Validation/ValidationContext.cs
> add Known argument names validation rule

- src/GraphQL.Tests/Language/ParserTests.cs
- src/GraphQL.Tests/Language/ShowDownTests.cs
- src/GraphQL/Language/GraphQLParser.cs
- src/GraphQL/Language/Parse.Optional.cs
- src/GraphQL/Language/Parse.Primitives.cs
- src/GraphQL/Language/Parse.Regex.cs
- src/GraphQL/Language/Parse.cs
- src/GraphQL/Language/Position.cs
- src/GraphQL/Language/Result.cs
Should provide a bit of a perf bump, not familiar with sprache, but it would seem to me regex's wouldn't be super performant for a lexer
> extract out regexes

- README.md
- src/GraphQL.Tests/GraphQL.Tests.csproj
- src/GraphQL.Tests/Validation/NoUnusedVariablesTests.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/Validation/DocumentValidator.cs
- src/GraphQL/Validation/Rules/NoUnusedVariables.cs
> Add no unused variables validation rule

- README.md
- src/GraphQL.Tests/GraphQL.Tests.csproj
- src/GraphQL.Tests/Validation/UniqueVariableNamesTests.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/Validation/DocumentValidator.cs
- src/GraphQL/Validation/Rules/UniqueVariableNames.cs
> Add unique variable names validation rule

- README.md
- src/GraphQL.Tests/GraphQL.Tests.csproj
- src/GraphQL.Tests/Validation/UniqueArgumentNamesTests.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/Validation/DocumentValidator.cs
- src/GraphQL/Validation/Rules/UniqueArgumentNames.cs
> Add unique argument names validation rule

- src/GraphQL/Types/DateGraphType.cs
> Specifying culture in DateGraphType.

- README.md
- src/GraphQL.Tests/GraphQL.Tests.csproj
- src/GraphQL.Tests/Validation/KnownFragmentNamesTests.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/Validation/DocumentValidator.cs
- src/GraphQL/Validation/Rules/KnownFragmentNames.cs
> Added known fragment names validation rule

- README.md
- src/GraphQL.Tests/GraphQL.Tests.csproj
- src/GraphQL.Tests/Validation/KnownDirectivesTests.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/Validation/DocumentValidator.cs
- src/GraphQL/Validation/Rules/KnownDirectives.cs
> Add known directives validation rule

- README.md
- src/GraphQL.Tests/GraphQL.Tests.csproj
- src/GraphQL.Tests/Validation/PossibleFragmentSpreadsTests.cs
- src/GraphQL.Tests/Validation/ValidationSchema.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/GraphQLExtensions.cs
- src/GraphQL/Types/GraphQLAbstractType.cs
- src/GraphQL/Validation/DocumentValidator.cs
- src/GraphQL/Validation/Rules/PossibleFragmentSpreads.cs
> Add possible fragment spreads validation rule

- README.md
- src/GraphQL.GraphiQL/GraphQL.GraphiQL.csproj
- src/GraphQL.Tests/Execution/UnionInterfaceTests.cs
- src/GraphQL.Tests/GraphQL.Tests.csproj
- src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs
- src/GraphQL.Tests/Validation/FieldsOnCorrectTypeTests.cs
- src/GraphQL.Tests/Validation/ValidationSchema.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/LightweightCache.cs
- src/GraphQL/Types/GraphType.cs
- src/GraphQL/Validation/DocumentValidator.cs
- src/GraphQL/Validation/Rules/FieldsOnCorrectType.cs
- src/GraphQL/Validation/Rules/KnownArgumentNames.cs
- src/GraphQL/Validation/TypeInfo.cs
> Add fields on correct type validation rule

- README.md
- src/GraphQL.Tests/GraphQL.Tests.csproj
- src/GraphQL.Tests/Validation/FragmentsOnCompositeTypesTests.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/GraphQLExtensions.cs
- src/GraphQL/Validation/DocumentValidator.cs
- src/GraphQL/Validation/Rules/FragmentsOnCompositeTypes.cs
> Add fragments on composite type validation rule

- src/GraphQL.Tests/Builders/ConnectionBuilderTests.cs
- src/GraphQL.Tests/Builders/FieldBuilderTests.cs
- src/GraphQL/Builders/ConnectionBuilder.cs
- src/GraphQL/Builders/FieldBuilder.cs
adds deprecation reason method to the builders
> Add DeprecationReason to Field builders

- src/GraphQL/Builders/ConnectionBuilder.cs
- src/GraphQL/Types/GraphType.cs
- src/GraphQL/Types/IGraphType.cs
- src/GraphQL/Types/Relay/ConnectionType.cs
- src/GraphQL/Types/Relay/EdgeType.cs
> Relax relay type restriction

- README.md
This helps avoid missing assembly errors.
> docs(readme): Add note to build solution

- src/GraphQL.Tests/Utilities/TypeExtensionsTests.cs
- src/GraphQL/TypeExtensions.cs
Trying to register a decimal field using a property expression currently results in an ArgumentOutOfRange exception.
> Support decimal -> DecimalGraphType

- src/GraphQL.Tests/QueryTestBase.cs
- src/GraphQL/Builders/FieldBuilder.cs
- src/GraphQL/Introspection/SchemaMetaFieldType.cs
- src/GraphQL/Types/BooleanGraphType.cs
- src/GraphQL/Types/ComplexGraphType.cs
- src/GraphQL/Types/DateGraphType.cs
- src/GraphQL/Types/FloatGraphType.cs
- src/GraphQL/Types/IGraphType.cs
- src/GraphQL/Types/IdGraphType.cs
- src/GraphQL/Types/InputObjectGraphType.cs
- src/GraphQL/Types/IntGraphType.cs
- src/GraphQL/Types/ScalarGraphType.cs
- src/GraphQL/Types/UnionGraphType.cs
- src/GraphQL/Validation/DebugNodeVisitor.cs
- src/GraphQL/Validation/DocumentValidator.cs
- src/GraphQL/Validation/INodeVisitor.cs
- src/GraphQL/Validation/Rules/DefaultValuesOfCorrectType.cs
- src/GraphQL/Validation/Rules/KnownArgumentNames.cs
- src/GraphQL/Validation/Rules/KnownTypeNames.cs
- src/GraphQL/Validation/Rules/LoneAnonymousOperation.cs
- src/GraphQL/Validation/Rules/NoUndefinedVariables.cs
- src/GraphQL/Validation/Rules/ScalarLeafs.cs
- src/GraphQL/Validation/Rules/UniqueInputFieldNames.cs
- src/GraphQL/Validation/Rules/UniqueOperationNames.cs
- src/GraphQL/Validation/Rules/VariablesAreInputTypes.cs
* **Add**: Added setters for `IGraphType` (needed by the Conventions library)
* **Add**: Non-generic method for adding type to `UnionGraphType`
* **Fix**: Validation rule threw on undefined argument type name
> Updates for interfacing with Conventions

- src/GraphQL.Tests/Types/EnumGraphTypeTests.cs
- src/GraphQL/Types/EnumerationGraphType.cs
- src/GraphQL/Utilities/StringUtils.cs
Not sure if this falls into convention territory, but I almost always want to do something like this.
> Auto populate values from an existing Enum

- src/GraphQL.GraphiQL/GraphQL.GraphiQL.csproj
- src/GraphQL.Tests/Types/ComplexGraphTypeTests.cs
- src/GraphQL/TypeExtensions.cs
- src/GraphQL/Types/ComplexGraphType.cs
Adds a few more descriptive errors
> better errors

- src/GraphQL.Tests/Execution/MutationTests.cs
- src/GraphQL.Tests/Introspection/SchemaIntrospectionTests.cs
- src/GraphQL.Tests/Types/GraphTypesLookupTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Types/GraphTypesLookup.cs
> Catch faulty tasks and rethrow exception on field resolution (in DocumentExecutor)

- README.md
- docs/getting-started.md
- docs/learn.md
I want to make these into a website eventually.
> Some initial docs

- src/GraphQL.Tests/Execution/RegisteredInstanceTests.cs
- src/GraphQL/Types/GraphTypesLookup.cs
* Also attempt to fix other field instance registration
Fixes #237 
Fixes #241
> Fix Union instance registration

- src/GraphQL.Tests/Execution/RegisteredInstanceTests.cs
- src/GraphQL/Types/GraphTypesLookup.cs
> Fix list/non-null instance registration

- src/GraphQL.Tests/Bugs/Bug256NullableEnumTests.cs
- src/GraphQL/ObjectExtensions.cs
> Fix nullable enums

- src/GraphQL.Tests/Execution/VariablesTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/InvalidValueException.cs
Adds some more detil to these errors. I've found it fairly frustrating to debug mutation inputs with the existing ones :)
> Input errors

- src/GraphQL.Tests/BasicQueryTestBase.cs
- src/GraphQL.Tests/Conversion/FieldNameConverterTests.cs
- src/GraphQL.Tests/Execution/RegisteredInstanceTests.cs
- src/GraphQL.Tests/Execution/UnionInterfaceTests.cs
- src/GraphQL.Tests/QueryTestBase.cs
- src/GraphQL.Tests/Types/ComplexGraphTypeTests.cs
- src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs
- src/GraphQL/Conversion/IFieldNameConverter.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/ExecutionOptions.cs
- src/GraphQL/Http/DocumentWriter.cs
- src/GraphQL/StringExtensions.cs
- src/GraphQL/Types/ComplexGraphType.cs
- src/GraphQL/Types/GraphTypesLookup.cs
- src/GraphQL/Types/Schema.cs
> Spike on supporting multi-cased fields and aliases

- src/GraphQL.Tests/Execution/MutationTests.cs
- src/GraphQL/ObjectExtensions.cs
Hi there,
I just created some tests for Datetime mutations along with a fix for issue #286 
Please review and let me know if anything
@lngr : can you please check if this resolves your issue?
CC: @cstlaurent
Thanks,
mat
> fixed issue #286 - UTC Dates in Mutation Input fields are broken

- src/GraphQL.Tests/Types/ComplexGraphTypeTests.cs
- src/GraphQL.Tests/Utilities/TypeExtensionsTests.cs
- src/GraphQL/TypeExtensions.cs
> List<> types supported in Field(x => x.MyList) syntax

- src/GraphQL.Tests/Instrumentation/FieldMiddlewareBuilderTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Types/ResolveFieldContext.cs
I, and others (#281), need to communicate more specific errors than the generic "Resolution failed..."
> Added possibility for field middlewares to add errors.

- src/GraphQL.GraphiQLCore/GraphQL.GraphiQLCore.csproj
- src/GraphQL.GraphiQLCore/GraphQLMiddleware.cs
- src/GraphQL.GraphiQLCore/GraphQLRequest.cs
- src/GraphQL.GraphiQLCore/GraphQLSettings.cs
- src/GraphQL.GraphiQLCore/Program.cs
- src/GraphQL.GraphiQLCore/Properties/launchSettings.json
- src/GraphQL.GraphiQLCore/Startup.cs
- src/GraphQL.sln
> Add a .NET Core middleware example

- release-notes.md
> Removing release-notes.md

- src/GraphQL.Tests/Errors/ErrorLocationTests.cs
- src/GraphQL.Tests/QueryTestBase.cs
- src/GraphQL/Execution/ExecutionErrors.cs
- src/GraphQL/Execution/ExecutionResultJsonConverter.cs
> Add test for catching errors in FieldAsync

- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/ExecutionOptions.cs
- src/GraphQL/Execution/ExecutionResult.cs
- src/GraphQL/Execution/ExecutionResultJsonConverter.cs
added support for ExposeExceptions as discussed in #279
> added support for ExposeExceptions

- src/GraphQL.Tests/Errors/ErrorLocationTests.cs
- src/GraphQL.Tests/Execution/RegisteredInstanceTests.cs
- src/GraphQL.Tests/Subscription/SubscriptionTests.cs
- src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs
- src/GraphQL/EnumerableExtensions.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/ExecutionError.cs
- src/GraphQL/Execution/ExecutionResultJsonConverter.cs
- src/GraphQL/Instrumentation/Metrics.cs
- src/GraphQL/Subscription/SubscriptionExecuter.cs
- src/GraphQL/Types/IGraphType.cs
- src/GraphQL/Types/ResolveFieldContext.cs
- src/GraphQL/Utilities/SchemaPrinter.cs
Fix a number of issues in the [2.0 milestone](https://github.com/graphql-dotnet/graphql-dotnet/milestone/2)
> 2.0 Issue Fixes

- src/GraphQL.Tests/Execution/AstFromValueTests.cs
- src/GraphQL.Tests/Execution/Performance/ThreadPerformanceTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/GraphQLExtensions.cs
- src/GraphQL/Language/AST/IValue.cs
- src/GraphQL/Language/AST/IntValue.cs
- src/GraphQL/Language/AST/NullValue.cs
- src/GraphQL/Language/AST/Variable.cs
- src/GraphQL/Types/IAstFromValueConverter.cs
- src/GraphQL/Types/Schema.cs
Some additional updates for #458
> Cleanup values

- src/GraphQL.Tests/Utilities/SchemaBuilderExecutionTests.cs
- src/GraphQL/Resolvers/MethodModelBinderResolver.cs
* Add ability to include UserContext
Fixes #455
> Fix index issues in MethodModelBinderResolver

- src/GraphQL/Subscription/SubscriptionExecuter.cs
Wrap resolve result value data into dictionary
> 485 - wrap resolve result data

- src/GraphQL.Tests/Validation/UniqueDirectivesPerLocationTests.cs
- src/GraphQL/Validation/Rules/UniqueDirectivesPerLocation.cs
- src/GraphQL/Validation/Rules/UniqueFragmentNames.cs
> Unique Directive Per Location Rule

- src/GraphQL.Tests/Utilities/SchemaBuilderTests.cs
- src/GraphQL/Utilities/SchemaBuilder.cs
> Add @deprecated support

- src/GraphQL/TypeExtensions.cs
- src/GraphQL/Utilities/TypeConfig.cs
Attempting to address #487 by allowing TypeConfig to resolve properties and not just methods.
> Allow TypeConfig to resolve properties in addition to methods

- src/GraphQL/ObjectExtensions.cs
> Fix Typo in GetProperyValue method name

- docs/src/dataloader.md
- docs/src/index.md
- docs/src/layout.htm
- docs/src/learn.md
- src/GraphQL/DataLoader/DataLoaderContext.cs
- src/GraphQL/DataLoader/DataLoaderContextExtensions.cs
- src/GraphQL/DataLoader/DataLoaderDocumentListener.cs
- src/GraphQL/DataLoader/IDataLoader.cs
- src/GraphQL/DataLoader/IDataLoaderContextAccessor.cs
Finally adding DataLoader documentation for #560.
> Add documentation for the DataLoader implementation

- src/GraphQL.DataLoader.Tests/BatchDataLoaderTests.cs
- src/GraphQL.DataLoader.Tests/CollectionBatchLoaderTests.cs
- src/GraphQL.DataLoader.Tests/SimpleDataLoaderTests.cs
- src/GraphQL.DataLoader.Tests/Stores/OrdersStore.cs
- src/GraphQL.DataLoader.Tests/Stores/UsersStore.cs
- src/GraphQL/DataLoader/BatchDataLoader.cs
- src/GraphQL/DataLoader/CollectionBatchDataLoader.cs
- src/GraphQL/DataLoader/DataLoaderBase.cs
This pull request fixes issue #571 and improves exception handling/bubbling in the DataLoaders.
> DataLoader fixes

- appveyor.yml
install node before npm
should fix https://github.com/graphql-dotnet/graphql-dotnet/issues/643
> fix appveyor install order

- src/GraphQL/TypeExtensions.cs
- src/GraphQL/Types/QueryArgument.cs
- tools/tasks/compile.js
> Use IGraphType interface with QueryArgument

- src/GraphQL.Tests/ObjectExtensionsTest.cs
- src/GraphQL/ObjectExtensions.cs
Issue page: https://github.com/graphql-dotnet/graphql-dotnet/issues/404
> Support for arrays conversions #404

- src/GraphQL.Tests/Builders/ConnectionBuilderTests.cs
- src/GraphQL/Builders/ConnectionBuilder.cs
Added an async field resolver to the connection builder with a unit test.
> Add ConnectionBuilder.ResolveAsync

- src/GraphQL/Execution/ExecutionError.cs
- src/GraphQL/Execution/ExecutionResultJsonConverter.cs
> default data property in ExecutionError to empty dictionary

- src/GraphQL/Validation/Complexity/ComplexityAnalyzer.cs
Related to #696 .
CC: @joemcbride
> #696 reset counter

- src/GraphQL.Tests/Utilities/AstPrinterTests.cs
- src/GraphQL/Utilities/AstPrinter.cs
Adds support for inline fragments in AstPrinter.
> FIX_ast-printer-inline-fragments

- src/GraphQL.Tests/Execution/AstFromValueTests.cs
- src/GraphQL.Tests/Types/UriGraphTypeTests.cs
- src/GraphQL/GraphQLExtensions.cs
- src/GraphQL/Language/AST/IntValue.cs
- src/GraphQL/Types/UriGraphType.cs
- src/GraphQL/Utilities/AstPrinter.cs
- src/GraphQL/ValueConverter.cs
Add support to urigraphtype
Fixes: #472
CC: @joemcbride
> #472 add UriGraphType

- src/GraphQL/GraphQL.csproj
> remove Reflection.TypeExtensions from netstandard2

- src/GraphQL.StarWars/GraphQL.StarWars.csproj
- src/GraphQL.Tests/Types/DateGraphTypeTests.cs
- src/GraphQL/Types/DateGraphType.cs
> Fix issue with Date as variable

- src/GraphQL.Tests/Execution/VariablesTests.cs
- src/GraphQL/Execution/ExecutionHelper.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/GraphQLExtensions.cs
- src/GraphQL/Introspection/__Type.cs
- src/GraphQL/ObjectExtensions.cs
- src/GraphQL/StringExtensions.cs
- src/GraphQL/Types/EnumerationGraphType.cs
- src/GraphQL/Types/FloatGraphType.cs
- src/GraphQL/Types/GraphTypesLookup.cs
- src/GraphQL/Types/IdGraphType.cs
- src/GraphQL/Validation/Complexity/ComplexityAnalyzer.cs
i like the new c# feature of pattern matching. https://docs.microsoft.com/en-us/dotnet/csharp/pattern-matching
so i did a PR :)  feel free to close if this is not your preference
> use pattern matching

- src/GraphQL.Tests/Execution/RepeatedSubfieldsIntegrationTests.cs
- src/GraphQL.Tests/Execution/RepeatedSubfieldsTest.cs
- src/GraphQL/Execution/ExecutionHelper.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/Language/AST/Field.cs
- src/GraphQL/Language/AST/Fields.cs
- src/GraphQL/Language/AST/SelectionSet.cs
> Repeated Subfields

- src/GraphQL.Tests/Conversion/FieldNameConverterTests.cs
- src/GraphQL/Types/GraphTypesLookup.cs
- src/GraphQL/Types/QueryArguments.cs
- src/GraphQL/Utilities/FieldValidator.cs
> Convert argument names on initialize

- src/GraphQL.Tests/Bugs/Bug68NonNullEnumGraphTypeTests.cs
- src/GraphQL.Tests/Bugs/NullableInputListTests.cs
- src/GraphQL.Tests/Errors/ErrorCodeTests.cs
- src/GraphQL.Tests/Errors/ErrorExtensionsTests.cs
- src/GraphQL.Tests/Errors/ErrorLocationTests.cs
- src/GraphQL.Tests/Errors/UnhandledExceptionTests.cs
- src/GraphQL.Tests/Types/SchemaTests.cs
- src/GraphQL.Tests/Utilities/SchemaBuilderTestBase.cs
- src/GraphQL.Tests/Validation/KnownDirectivesTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/ExecutionContext.cs
- src/GraphQL/Execution/ExecutionOptions.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
> Add flag for throwing on unhandled exceptions

- docs2/site/docs/guides/migration.md
> Fix spelling mistake in migration.md

- src/GraphQL.DataLoader.Tests/DataLoaderSubscriptionTest.cs
- src/GraphQL.DataLoader.Tests/DataLoaderTestSchema.cs
- src/GraphQL.DataLoader.Tests/QueryTestBase.cs
- src/GraphQL.DataLoader.Tests/Stores/IOrdersStore.cs
- src/GraphQL.DataLoader.Tests/Types/SubscriptionType.cs
- src/GraphQL/Execution/SubscriptionExecutionStrategy.cs
This should resolve graphql-dotnet/server#162
> Notify listeners during subscription execution

- README.md
- appveyor.yml
- package.json
- src/GraphQL.DataLoader.Tests/GraphQL.DataLoader.Tests.csproj
- src/GraphQL.Harness.Tests/SystemTestBase.cs
- src/GraphQL.Harness/GraphQLMiddleware.cs
- src/GraphQL.Harness/GraphQLSettings.cs
- src/GraphQL.Harness/Startup.cs
- src/GraphQL.Harness/appsettings.Testing.json
- src/GraphQL.Harness/appsettings.json
- src/GraphQL.StarWars/Types/DroidType.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/ExecutionResultJsonConverter.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/Instrumentation/ApolloTrace.cs
- src/GraphQL/Instrumentation/ApolloTracingExtensions.cs
- src/GraphQL/Instrumentation/InstrumentFieldsMiddleware.cs
- tools/tasks/dotnetPack.js
> Await metrics middleware, fix time converter

- src/GraphQL.Tests/Types/GuidGraphTypeTests.cs
- src/GraphQL.Tests/Types/ShortGraphTypeTests.cs
- src/GraphQL.Tests/Types/UIntGraphTypeTests.cs
- src/GraphQL.Tests/Types/ULongGraphTypeTests.cs
- src/GraphQL.Tests/Types/UShortGraphTypeTests.cs
- src/GraphQL/Language/AST/ValueNodes/GuidValue.cs
- src/GraphQL/Language/AST/ValueNodes/ShortValue.cs
- src/GraphQL/Language/AST/ValueNodes/UIntValue.cs
- src/GraphQL/Language/AST/ValueNodes/ULongValue.cs
- src/GraphQL/Language/AST/ValueNodes/UShortValue.cs
- src/GraphQL/Types/GuidGraphType.cs
- src/GraphQL/Types/ShortGraphType.cs
- src/GraphQL/Types/UIntGraphType.cs
- src/GraphQL/Types/ULongGraphType.cs
- src/GraphQL/Types/UShortGraphType.cs
- src/GraphQL/ValueConverter.cs
Enhancement:- #741
- Added ScalarGraphType for following types
- Added test cases.
> 741 more scalar types

- src/GraphQL/Http/DocumentWriter.cs
- src/GraphQL/Http/PooledByteResult.cs
As per comment in #927, marking the unused methods/classed as obsolete.
> Marked the no longer used methods as obsolete.

- src/GraphQL.Tests/Execution/MutationTests.cs
- src/GraphQL/Types/GuidGraphType.cs
Added conversion from string value to guid in GuidGraphType ParseLiteral
> Convert from StringValue in GuidGraphType

- README.md
> add myget feed

- src/GraphQL.Tests/Types/ComplexGraphTypeTests.cs
- src/GraphQL/TypeExtensions.cs
- src/GraphQL/Types/ComplexGraphType.cs
Otherwise you get a null reference exception.
> Improve error message when type is missing

- docs2/site/docs/getting-started/introduction.md
The previous example on the same page is a complete program that can be pasted to Program.cs and compile and run. This example contains only code snippets that can not be blindly pasted. Having examples on the same page following two different styles is confusing.
> Making the examples consistent

- docs2/site/docs/guides/links.md
I just finished writing an article on cursor based pagination and connections using this library.
Figured it might be useful :)
> Add link to article on cursor based pagination and connections to links

- src/GraphQL.Harness/Startup.cs
- src/GraphQL/Types/GraphTypesLookup.cs
> remove the requiremnent for connection types to be in the container

- src/GraphQL.Harness.Tests/GraphQLExpectations.cs
- src/GraphQL.Harness.Tests/SuccessResultAssertion.cs
- src/GraphQL.Harness.Tests/SystemTestBase.cs
- src/GraphQL.Harness/GraphQLMiddleware.cs
- src/GraphQL.Harness/Startup.cs
- src/GraphQL.Tests/Execution/VariablesTests.cs
- src/GraphQL.Tests/Introspection/IntrospectionResult.cs
- src/GraphQL.Tests/Language/ShowDownTests.cs
- src/GraphQL.Tests/Utilities/SchemaBuilderExecutionTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/ExecutionResultJsonConverter.cs
- src/GraphQL/Http/DocumentWriter.cs
- src/GraphQL/Http/HttpResponseStreamWriter.cs
- src/GraphQL/Instrumentation/PerfRecord.cs
- src/GraphQL/Introspection/__TypeKind.cs
- src/GraphQL/Reflection/ReflectionHelper.cs
- src/GraphQL/Resolvers/AsyncEventStreamResolver.cs
- src/GraphQL/Resolvers/EventStreamResolver.cs
- src/GraphQL/Resolvers/FuncFieldResolver.cs
- src/GraphQL/Types/GraphTypesLookup.cs
- src/GraphQL/Types/InputObjectGraphType.cs
- src/GraphQL/Types/TypeExtensions.cs
- src/GraphQL/Utilities/AstPrinter.cs
- src/GraphQL/Utilities/SchemaBuilder.cs
- src/GraphQL/Utilities/TypeConfig.cs
- src/GraphQL/Validation/Rules/NoUndefinedVariables.cs
- src/GraphQL/Validation/Rules/ScalarLeafs.cs
- src/GraphQL/Validation/Rules/SingleRootFieldSubscriptions.cs
- tools/tasks/test.dotnet.js
fixes #1049 
also fixes BasicTests.hero
> Default null handling

- README.md
- src/GraphQL.Tests/Validation/OverlappingFieldsCanBeMergedTest.cs
- src/GraphQL.Tests/Validation/ResultTypeValidationSchema.cs
- src/GraphQL.Tests/Validation/ValidationTestBase.cs
- src/GraphQL.Tests/Validation/ValidationTestConfig.cs
- src/GraphQL/Types/GraphType.cs
- src/GraphQL/Types/ListGraphType.cs
- src/GraphQL/Types/NonNullGraphType.cs
- src/GraphQL/Validation/Rules/OverlappingFieldsCanBeMerged.cs
> 160 add overlapping fields can be merged validation rule

- src/GraphQL.Tests/Types/ComplexGraphTypeTests.cs
- src/GraphQL/Builders/FieldBuilder.cs
- src/GraphQL/GraphQLExtensions.cs
- src/GraphQL/Types/ComplexGraphType.cs
- src/GraphQL/Types/EnumerationGraphType.cs
> System.ComponentModel attributes support

- src/GraphQL/Introspection/TypeKind.cs
- src/GraphQL/Introspection/TypeMetaFieldType.cs
- src/GraphQL/Introspection/__Directive.cs
- src/GraphQL/Introspection/__EnumValue.cs
- src/GraphQL/Introspection/__Field.cs
- src/GraphQL/Introspection/__InputValue.cs
- src/GraphQL/Introspection/__Type.cs
- src/GraphQL/Introspection/__TypeKind.cs
- src/GraphQL/Types/DirectiveGraphType.cs
- src/GraphQL/Types/GraphQLTypeReference.cs
> EnumerationGraphType -> EnumerationGraphType<TEnum>

- src/GraphQL.Tests/Types/ComplexGraphTypeTests.cs
- src/GraphQL/Types/AutoRegisteringObjectGraphType.cs
> AutoRegisteringObjectGraphType customization

- src/GraphQL.Tests/Files/PetAfterAll.graphql
- src/GraphQL.Tests/Files/PetBeforeAll.graphql
- src/GraphQL.Tests/GraphQL.Tests.csproj
- src/GraphQL.Tests/Types/SchemaTests.cs
- src/GraphQL.Tests/Utilities/SchemaBuilderExecutionTests.cs
- src/GraphQL.Tests/Utilities/SchemaBuilderTestBase.cs
- src/GraphQL/StringExtensions.cs
- src/GraphQL/Types/Schema.cs
- src/GraphQL/Utilities/SchemaBuilder.cs
- src/GraphQL/Utilities/TypeSettings.cs
> GraphQLTypeReference for union possible types

- src/GraphQL.Tests/Types/ComplexGraphTypeTests.cs
- src/GraphQL.Tests/Utilities/TypeExtensionsTests.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/TypeExtensions.cs
- src/GraphQL/Types/AutoRegisteringObjectGraphType.cs
- src/GraphQL/Utilities/GraphTypeTypeRegistry.cs
> AutoRegisteringObjectGraphType improvement

- src/GraphQL.Tests/Bugs/CamelCaseArgumentTest.cs
- src/GraphQL.Tests/Utilities/SchemaBuilderExecutionTests.cs
- src/GraphQL/Types/ResolveFieldContext.cs
Not sure if it needs to support field resolve not in schema context.
> #925 Convert argument name to camelCase

- src/Directory.Build.props
- src/GraphQL.DataLoader.Tests/GraphQL.DataLoader.Tests.csproj
- src/GraphQL/GraphQL.csproj
> add Directory.Build.props with LangVersion latest

- src/GraphQL.Tests/Types/ComplexGraphTypeTests.cs
- src/GraphQL/Types/EnumerationGraphType.cs
> Add DeprecationReason from ObsoleteAttribute for EnumerationGraphType

- src/GraphQL.Tests/Bugs/ArrayOfArrayTest.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
> Support for array of arrays (int[][])

- src/GraphQL/Utilities/StringUtils.cs
Special handling of boundary cases.
> String allocations small optimization

- src/GraphQL.Tests/Builders/ConnectionBuilderTests.cs
- src/GraphQL/Builders/ConnectionBuilder.cs
- src/GraphQL/TypeExtensions.cs
- src/GraphQL/Types/ComplexGraphType.cs
- src/GraphQL/Types/GraphTypesLookup.cs
- src/GraphQL/Types/Relay/ConnectionType.cs
- src/GraphQL/Types/Relay/DataObjects/Connection.cs
- src/GraphQL/Types/Relay/DataObjects/Edge.cs
- src/GraphQL/Types/Relay/EdgeType.cs
Adds support for user-defined Edge and Connection types so custom properties can be added to them as needed.
Addresses #1093 
Builds on #1066
> feat: support user-defined Edge and Connection types

- src/GraphQL.sln
> remove global.json from sln

- src/GraphQL.Tests/Builders/ConnectionBuilderTests.cs
- src/GraphQL/Builders/ConnectionBuilder.cs
- src/GraphQL/TypeExtensions.cs
- src/GraphQL/Types/ComplexGraphType.cs
- src/GraphQL/Types/GraphTypesLookup.cs
- src/GraphQL/Types/Relay/ConnectionType.cs
- src/GraphQL/Types/Relay/DataObjects/Connection.cs
- src/GraphQL/Types/Relay/DataObjects/Edge.cs
- src/GraphQL/Types/Relay/EdgeType.cs
Adds support for user-defined Edge and Connection types so custom properties can be added to them as needed.
Addresses #1093
Builds on #1066 and includes it's cleanup of unnecessary type params.
> User-defined Edge and Connection Types.

- src/GraphQL.Tests/Bugs/Bug252ExecutorAppliesFIeldBuilderOnce.cs
- src/GraphQL.Tests/Bugs/Bug256NullableEnumTests.cs
- src/GraphQL.Tests/Bugs/CamelCaseArgumentTest.cs
- src/GraphQL.Tests/Conversion/FieldNameConverterTests.cs
- src/GraphQL.Tests/Execution/ExecutionListenerTests.cs
- src/GraphQL.Tests/Execution/RegisteredInstanceTests.cs
- src/GraphQL.Tests/Execution/RepeatedSubfieldsIntegrationTests.cs
- src/GraphQL.Tests/Execution/RepeatedSubfieldsTest.cs
- src/GraphQL.Tests/Execution/ResolveFieldContextTests.cs
- src/GraphQL.Tests/Instrumentation/FieldMiddlewareBuilderTests.cs
- src/GraphQL.Tests/StarWars/StarWarsBasicQueryTests.cs
- src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs
@joemcbride this is a preference of mine. i think it makes the code more readable. thoughts?
> use object initializers

- src/GraphQL.Tests/Bugs/Issue1127.cs
- src/GraphQL/Execution/ExecutionHelper.cs
- src/GraphQL/Language/AST/Arguments.cs
- src/GraphQL/Types/QueryArgument.cs
> Set defaults to argument properties

- docs2/site/docs/getting-started/graphiql.md
`The this ASP.NET Core sample p...` doesn't make sense so I removed the initial `The`.
> Fixed grammar of the documentation

- package.json
- src/GraphQL.Harness/Startup.cs
- src/GraphQL.StarWars/StarWarsSchema.cs
- src/GraphQL.Tests/Execution/Performance/ListPerformanceTests.cs
- src/GraphQL.Tests/Execution/Performance/ThreadPerformanceTests.cs
- src/GraphQL.Tests/Execution/UnionInterfaceTests.cs
- src/GraphQL.Tests/ServiceProviderExtensions.cs
- src/GraphQL.Tests/StarWars/StarWarsTestBase.cs
- src/GraphQL.Tests/Utilities/SchemaBuilderTests.cs
- src/GraphQL.Tests/Utilities/SchemaVisitorTests.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/IDependencyResolver.cs
- src/GraphQL/Reflection/AccessorFieldResolver.cs
- src/GraphQL/Resolvers/AsyncEventStreamResolver.cs
- src/GraphQL/Resolvers/EventStreamResolver.cs
- src/GraphQL/Types/EnumerationGraphType.cs
- src/GraphQL/Types/Schema.cs
- src/GraphQL/Utilities/DeprecatedDirectiveVisistor.cs
- src/GraphQL/Utilities/DirectiveVisitorSelector.cs
- src/GraphQL/Utilities/ISchemaNodeVisitor.cs
- src/GraphQL/Utilities/IVisitorSelector.cs
- src/GraphQL/Utilities/SchemaBuilder.cs
- src/GraphQL/Utilities/SchemaBuilderExtensions.cs
- src/GraphQL/Utilities/SchemaDirectiveVisitor.cs
- src/GraphQL/Utilities/ServiceProviderExtensions.cs
- src/GraphQL/Utilities/SyncToAsyncResolverAdapter.cs
- src/GraphQL/Utilities/TypeConfig.cs
- yarn.lock
```csharp
var schema = Schema.For(@"
type Query {
hello: String @upper
}
",
_ =>
{
_.RegisterDirectiveVisitor<UppercaseDirectiveVisitor>("upper");
});
var json = schema.Execute(_ =>
{
_.Query = "{ hello }";
_.Root = new { Hello = "Hello World!" };
});
public class UppercaseDirectiveVisitor : SchemaDirectiveVisitor
{
public override void VisitField(FieldType field)
{
var inner = field.Resolver ?? new NameFieldResolver();
field.Resolver = new FuncFieldResolver<object>(context =>
{
var result = inner.Resolve(context);
if (result is string str)
{
return str.ToUpperInvariant();
}
return result;
});
}
}
```
> Support custom directives in Schema First

- src/GraphQL.Tests/Types/ComplexGraphTypeTests.cs
- src/GraphQL/TypeExtensions.cs
> Handle enums for AutoRegisteringObjectGraphType

- src/GraphQL.Harness/GraphQLMiddleware.cs
- src/GraphQL.Harness/GraphQLSettings.cs
- src/GraphQL.Harness/Startup.cs
- src/GraphQL.Harness/appsettings.Testing.json
- src/GraphQL.Harness/appsettings.json
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/ExecutionOptions.cs
- src/GraphQL/Introspection/ISchemaFilter.cs
- src/GraphQL/Introspection/SchemaMetaFieldType.cs
- src/GraphQL/Introspection/__Field.cs
- src/GraphQL/Introspection/__Type.cs
- src/GraphQL/TaskExtensions.cs
- src/GraphQL/Types/FieldType.cs
- src/GraphQL/Types/QueryArgument.cs
- src/GraphQL/Types/Schema.cs
Example usage:
https://gist.github.com/joemcbride/87a5761161748263115f591f4543b6e4
> Add the ability to filter an introspection query

- src/GraphQL.Tests/Bugs/Bug947.cs
- src/GraphQL/ObjectExtensions.cs
- src/GraphQL/TypeExtensions.cs
- src/GraphQL/Types/ResolveFieldContext.cs
- src/GraphQL/ValueConverter.cs
> Change GetArgument<T> 

- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/Types/ObjectGraphType.cs
> Check collections for null elements in setters

- src/GraphQL.Tests/Types/ComplexGraphTypeTests.cs
- src/GraphQL/Types/AutoRegisteringObjectGraphType.cs
> Set AutoRegisteringObjectGraphType.Name

- src/GraphQL.Tests/Instrumentation/FieldMiddlewareBuilderTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Instrumentation/ApolloTrace.cs
- src/GraphQL/Instrumentation/ApolloTracingExtensions.cs
- src/GraphQL/Instrumentation/Metrics.cs
- src/GraphQL/Instrumentation/PerfRecord.cs
- src/GraphQL/Instrumentation/Stats.cs
- src/GraphQL/Instrumentation/ValueStopwatch.cs
fixed #944
struct ValueStopWatch instead of Stopwatch in Metrics, Marker -> struct
move StatsReport, TypeStat etc to separate file
> Metrics improvements

- src/GraphQL.Tests/Bugs/Bug1205VeryLongInt.cs
> New test to check very long IntGraphType

- .editorconfig
- .gitignore
- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.approved.txt
- src/GraphQL.Tests/Utilities/SchemaBuilderExecutionTests.cs
- src/GraphQL/Http/DocumentWriter.cs
- src/GraphQL/SchemaExtensions.cs
- src/GraphQL/Utilities/TypeConfig.cs
> Do not require all scalar fields to be defined

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.approved.txt
- src/GraphQL/Types/QueryArguments.cs
- src/GraphQL/Utilities/DeprecatedDirectiveVisitor.cs
- src/GraphQL/Utilities/DirectiveVisitorSelector.cs
- src/GraphQL/Utilities/Federation/FederatedSchemaBuilder.cs
- src/GraphQL/Utilities/SchemaBuilder.cs
Removed the remaining usage. Fixed a bug and formatting. Relates to #1311 .
> Remove dependency resolver

- src/GraphQL/Execution/ExecutionStrategy.cs
> Better error message for IsTypeOf

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.approved.txt
- src/GraphQL/Abstractions/IHasUserContext.cs
- src/GraphQL/Execution/ExecutionContext.cs
- src/GraphQL/Execution/ExecutionOptions.cs
- src/GraphQL/Execution/IProvideUserContext.cs
- src/GraphQL/Types/ResolveFieldContext.cs
- src/GraphQL/Validation/ValidationContext.cs
Makes it easier to write custom extension methods for the usercontext
> Added IHasUserContext abstraction

- src/GraphQL/Resolvers/NameFieldResolver.cs
This pull request fixes CreatePropertyDelegate method when used on runtime created proxies (for example when using NHibernate).
When a proxy is passed as target argument to CreatePropertyDelegate the following exception is thrown:
```Cannot bind to the target method because its signature is not compatible with that of the delegate type.```
The side effect of this change might be a little faster excecution of the delegate - https://www.palmmedia.de/Blog/2012/2/4/reflection-vs-compiled-expressions-vs-delegates-performance-comparison
> NameFieldResolver - CreatePropertyDelegate fix for proxies

- src/GraphQL.Tests/Bugs/Issue1354.cs
- src/GraphQL.Tests/QueryTestBase.cs
- src/GraphQL.Tests/Types/BooleanGraphTypeTests.cs
- src/GraphQL.Tests/Utilities/SchemaVisitorTests.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/Instrumentation/FieldMiddlewareBuilder.cs
- src/GraphQL/Instrumentation/MiddlewareResolver.cs
- src/GraphQL/Resolvers/NameFieldResolver.cs
- src/GraphQL/Utilities/ISchemaNodeVisitor.cs
tests for #1330
close #1354 
NameFieldResolver does not allocate
remove all Reflection from NameFieldResolver
netcoreapp30 exception message fix
> NameFieldResolver tuning

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.approved.txt
- src/GraphQL.ApiTests/GraphQL.ApiTests.csproj
- src/GraphQL.DataLoader.Tests/GraphQL.DataLoader.Tests.csproj
- src/GraphQL.Harness.Tests/GraphQL.Harness.Tests.csproj
- src/GraphQL.Tests/GraphQL.Tests.csproj
- src/GraphQL.Tests/Types/ComplexGraphTypeTests.cs
- src/GraphQL.Tests/Types/ObjectGraphTypeTests.cs
- src/GraphQL/Types/AutoRegisteringObjectGraphType.cs
- src/GraphQL/Types/GraphType.cs
- src/GraphQL/Utilities/GraphTypeTypeRegistry.cs
> Add AutoRegisteringInputObjectGraphType

- src/GraphQL.Tests/Bugs/Issue1354.cs
- src/GraphQL.Tests/NameFieldResolverTests.cs
- src/GraphQL/Resolvers/NameFieldResolver.cs
It seemed to me that it would not hurt to add this feature.
> NameFieldResolver can call methods

- docs2/site/docs/getting-started/directives.md
- src/GraphQL/GraphQL.csproj
leading pipe fix for unions and directives
> bump parser

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.approved.txt
- src/GraphQL/Resolvers/NameFieldResolver.cs
See #1378 
Note that the ApiApprovalTests need to be updated.  I assume this is something you'd manage.
> Change NameFieldResolver to public

- src/GraphQL.Tests/Bugs/BubbleUpTheNullToNextNullable.cs
- src/GraphQL/Execution/ExecutionNode.cs
> Fix for exception in [Type!]! resolver

- src/GraphQL.DataLoader.Tests/SimpleDataLoaderTests.cs
it was intermittently failing for me
> increase Operation_Can_Be_Cancelled Delay

- docs2/site/docs/guides/schema-generation.md
I've created this project that we use heavily at my company to simply declare queries and mutations.
> Add a new project to declare query in one line

- src/GraphQL.Tests/NameFieldResolverTests.cs
- src/GraphQL.Tests/TypeExtensionsTests.cs
- src/GraphQL.Tests/Types/EnumGraphTypeTests.cs
- src/GraphQL.Tests/Utilities/FederatedSchemaBuilderTests.cs
- src/GraphQL.Tests/Utilities/GetGraphTypeFromTypeTests.cs
Hello, while trying to figure out how everything works did tried to implement few tests based on coverage results
> some minor tests added

- src/GraphQL.Tests/Utilities/SchemaBuilderExecutionTests.cs
- src/GraphQL/Types/GraphTypesLookup.cs
* The references will be resolved later in the process
fixes #1430
> Skip over references with Unions

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.approved.txt
- src/GraphQL.Tests/Types/ComplexGraphTypeTests.cs
- src/GraphQL.Tests/Types/InputObjectGraphTypeTests.cs
- src/GraphQL/GraphQLExtensions.cs
- src/GraphQL/Types/ComplexGraphType.cs
- src/GraphQL/Types/InputObjectGraphType.cs
> Prevent use ObjectGraphType as property of InputObjectGraphType and vice versa

- src/GraphQL.Tests/Types/SchemaTests.cs
- src/GraphQL/Types/GraphType.cs
- src/GraphQL/Types/GraphTypesLookup.cs
> Stackoverflow check

- src/GraphQL/GraphQL.csproj
> bump parser version

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.approved.txt
- src/GraphQL/Instrumentation/FieldResolverBuilderExtensions.cs
Simple performance enhancement to existing code.
> Change middleware Use to type-check and compile ahead of time

- src/GraphQL/Utilities/ServiceProviderExtensions.cs
> Note about GetRequiredService

- src/GraphQL.Tests/Bugs/Issue1004.cs
- src/GraphQL/Introspection/__Field.cs
- src/GraphQL/Types/GraphTypesLookup.cs
> Field description can be taken from the interface field

- src/GraphQL/GraphQL.csproj
AssemblyName and PackageId are inherited from the csproj file name
> remove redundant props

- src/GraphQL/GraphQL.csproj
> move to embedded icon

- src/GraphQL.Tests/Utilities/SchemaBuilderExecutionTests.cs
- src/GraphQL/Reflection/ReflectionHelper.cs
> support type hierachy of usercontext type

- src/GraphQL/GraphQL.csproj
> move to PackageLicenseExpression

- .editorconfig
> [WIP] add editorconfig rules

- src/Directory.Build.props
- src/GraphQL.Dummy/GraphQL.Dummy.csproj
- src/GraphQL.StarWars/GraphQL.StarWars.csproj
- src/GraphQL/GraphQL.csproj
- tools/tasks/dotnetPack.js
Fix for https://github.com/graphql-dotnet/graphql-dotnet/pull/1448#issuecomment-571757415
> prepare to pack all packable projects in solution

- src/GraphQL.Tests/Utilities/SchemaBuilderExecutionTests.cs
- src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs
The .editorconfig helped me find these cases.
> Add test checks

- src/GraphQL.Tests/Introspection/SchemaIntrospectionTests.cs
- src/GraphQL.Tests/Utilities/SchemaBuilderExecutionTests.cs
- src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs
- src/GraphQL/DI/FuncServiceProvider.cs
- src/GraphQL/Instrumentation/ValueStopwatch.cs
- src/GraphQL/Language/AST/ValueNodes/BigIntValue.cs
- src/GraphQL/Language/AST/ValueNodes/BooleanValue.cs
- src/GraphQL/Language/AST/ValueNodes/ByteValue.cs
- src/GraphQL/Language/AST/ValueNodes/DateTimeOffsetValue.cs
- src/GraphQL/Language/AST/ValueNodes/DateTimeValue.cs
- src/GraphQL/Language/AST/ValueNodes/DecimalValue.cs
- src/GraphQL/Language/AST/ValueNodes/FloatValue.cs
- src/GraphQL/Language/AST/ValueNodes/GuidValue.cs
- src/GraphQL/Language/AST/ValueNodes/IntValue.cs
- src/GraphQL/Language/AST/ValueNodes/ListValue.cs
- src/GraphQL/Language/AST/ValueNodes/LongValue.cs
- src/GraphQL/Language/AST/ValueNodes/SByteValue.cs
- src/GraphQL/Language/AST/ValueNodes/ShortValue.cs
- src/GraphQL/Language/AST/ValueNodes/StringValue.cs
- src/GraphQL/Language/AST/ValueNodes/TimeSpanValue.cs
- src/GraphQL/Language/AST/ValueNodes/UIntValue.cs
- src/GraphQL/Language/AST/ValueNodes/ULongValue.cs
- src/GraphQL/Language/AST/ValueNodes/UShortValue.cs
- src/GraphQL/Language/AST/ValueNodes/UriValue.cs
- src/GraphQL/Utilities/Federation/AnyScalarGraphType.cs
- src/GraphQL/Utilities/Federation/AnyValue.cs
I started applying the rules from .editorconfig . I hope that gradually we will come to a common opinion about which set of rules should be used.
> Block body for ctors

- docs2/site/docs/getting-started/unions.md
- src/GraphQL.Tests/Execution/UnionInterfaceTests.cs
- src/GraphQL.sln
> Add union docs

- docs2/site/docs/getting-started/graphiql.md
> Add GraphiQL docs

- src/GraphQL.Benchmarks/ExecutionBenchmark.cs
- src/GraphQL.Benchmarks/GraphQL.Benchmarks.Reference.md
- src/GraphQL.Benchmarks/GraphQL.Benchmarks.csproj
- src/GraphQL.Benchmarks/Program.cs
- src/GraphQL.sln
Adds initial support for BenchmarkDotNet
> Benchmarks initial support [WIP]

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.NewtonsoftJson.approved.txt
- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL.ApiTests/GraphQL.ApiTests.csproj
Also in the new version the sorting conditions have changed.
> upgrade publicapigenerator to 10.0.1

- docs2/site/docs/getting-started/errors.md
DO NOT MERGE THIS BEFORE #1448 and #1449 
fixes #1292
> Note about json converter

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.NewtonsoftJson.approved.txt
- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.SystemTextJson.approved.txt
- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL.NewtonsoftJson/DocumentWriter.cs
- src/GraphQL.SystemTextJson/DocumentWriter.cs
- src/GraphQL/IDocumentWriter.cs
@benmccallum We completely forgot about canceling async IO.
> Add cancellationToken to IDocumentWriter.WriteAsync

- src/GraphQL.Harness/GraphQLMiddleware.cs
> fix deserialization in Harness

- src/GraphQL/Execution/IDocumentExecuter.cs
See 'files changed' for suggested change
> Add xml comments to IDocumentExecuter

- src/GraphQL/Execution/IExecutionStrategy.cs
See 'files changed' for suggested changes
> Add xml comments to IExecutionStrategy

- src/GraphQL/Execution/IDocumentBuilder.cs
See 'files changed' for suggested change
> Add xml comments to IDocumentBuilder

- src/GraphQL/Execution/ExecutionOptions.cs
- src/GraphQL/Execution/IDocumentExecuter.cs
Also fixed note in IDocumentExexuter
> Add xml comments to ExecutionOptions

- src/GraphQL/ResolveFieldContextExtensions.cs
- src/GraphQL/Types/IResolveFieldContext.cs
- src/GraphQL/Types/ResolveFieldContext.cs
Contains very short summaries of the field's purposes.  Comments are appreciated.
> Add xml comments to IResolveFieldContext

- src/GraphQL/Resolvers/AsyncFieldResolver.cs
- src/GraphQL/Resolvers/ExpressionFieldResolver.cs
- src/GraphQL/Resolvers/FuncFieldResolver.cs
- src/GraphQL/Resolvers/IFieldResolver.cs
- src/GraphQL/Resolvers/NameFieldResolver.cs
> Add xml comments to field resolvers

- src/GraphQL/Language/AST/ValueNodes/ListValue.cs
- src/GraphQL/Language/CoreToVanillaConverter.cs
- src/GraphQL/Utilities/SchemaBuilder.cs
> ArgumentNullException fix

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL.Tests/Bugs/Bug256NullableEnumTests.cs
- src/GraphQL.Tests/Bugs/Bug947.cs
- src/GraphQL.Tests/Bugs/Bug956.cs
- src/GraphQL.Tests/Bugs/ScalarsInputTest.cs
- src/GraphQL/Conversion/ValueConverter.cs
- src/GraphQL/ObjectExtensions.cs
> More conversions

- README.md
- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL.ApiTests/GraphQL.ApiTests.csproj
- src/GraphQL.DataLoader.Tests/GraphQL.DataLoader.Tests.csproj
- src/GraphQL.Harness.Tests/GraphQL.Harness.Tests.csproj
- src/GraphQL.Harness/GraphQL.Harness.csproj
- src/GraphQL.Harness/Program.cs
- src/GraphQL.Harness/Startup.cs
- src/Tests.props
- update README with myget badge and more info about preview builds, add links to IDEs
- update dependencies for tests
- add Altair and Voyager
> Upgrade repo

- docs2/site/docs/getting-started/field-middleware.md
- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL.Tests/Instrumentation/FieldMiddlewareBuilderTests.cs
- src/GraphQL/Instrumentation/FieldMiddlewareBuilderExtensions.cs
> Remove pattern-based middleware

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL.Tests/Execution/ResolveFieldContextTests.cs
- src/GraphQL/Execution/ExecutionContext.cs
- src/GraphQL/Execution/ExecutionResultExtensions.cs
- src/GraphQL/Execution/IExecutionContext.cs
- src/GraphQL/Execution/SubscriptionExecutionStrategy.cs
- src/GraphQL/ResolveFieldContext/IResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ReadonlyResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContextAdapter.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContextExtensions.cs
fixes #1606 
@BenjaBobs take a look. Are you comfortable with such an API?
> Expose Extensions

- src/GraphQL.Tests/Bugs/Bug1626.cs
- src/GraphQL.sln
- src/GraphQL/ObjectExtensions.cs
> Fix AmbiguousMatchException for GetArgument

- src/GraphQL.Tests/Bugs/Issue1082.cs
- src/GraphQL/Utilities/GraphTypeTypeRegistry.cs
> DateTime <-> DateTimeGraphType mapping

- src/GraphQL.NewtonsoftJson/ExecutionResultJsonConverter.cs
- src/GraphQL.SystemTextJson/ExecutionResultJsonConverter.cs
- src/GraphQL.Tests/DocumentWriterTests.cs
> Serialize any errors first

- src/GraphQL/Utilities/Federation/FederatedSchemaPrinter.cs
> Fixed federated directive printer when printing extended type.

- .editorconfig
- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL.NewtonsoftJson/ExecutionResultJsonConverter.cs
- src/GraphQL.SystemTextJson/ExecutionResultJsonConverter.cs
- src/GraphQL.Tests/Bugs/Bug1652.cs
- src/GraphQL/EnumerableExtensions.cs
- src/GraphQL/Execution/ExecutionError.cs
> ExecutionError.Data handles object keys

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL.Tests/Complexity/ComplexityTestBase.cs
- src/GraphQL/Validation/Complexity/ComplexityAnalyzer.cs
- src/GraphQL/Validation/Complexity/ComplexityConfiguration.cs
> Move maxRecursionCount to options

- src/GraphQL.SystemTextJson/GraphQL.SystemTextJson.csproj
- src/GraphQL.SystemTextJson/JsonConverterBigInteger.cs
- src/GraphQL.SystemTextJson/ObjectDictionaryConverter.cs
fixes #1661 
@benmccallum I also removed netcoreapp3.1 target since it is not required.
> Add netstandard2.0 target for GraphQL.SystemTextJson

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL.Tests/Types/AutoRegisteringGraphTypeTests.cs
- src/GraphQL/Types/Composite/AutoRegisteringObjectGraphType.cs
> Add default ctors to AutoRegistering[Input]ObjectGraphType

- src/GraphQL.Tests/Bugs/ScalarsInputTest.cs
- src/GraphQL/Language/CoreToVanillaConverter.cs
- src/GraphQL/Utilities/AstPrinter.cs
> Decimal precision fix

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL/Utilities/SchemaPrinter.cs
> Remove IDisposable from SchemaPrinter

- docs2/site/docs/getting-started/dependency-injection.md
Relating to #1326, adding some information on using Scoped Services in GraphQL. 
Hopefully will help someone out there without needing to go through GitHub issues.
> Docs - Adding Scoped Services to dependency-injection.md

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL/Types/Composite/ListGraphType.cs
- src/GraphQL/Types/Composite/NonNullGraphType.cs
- src/GraphQL/Types/Fields/FieldType.cs
- src/GraphQL/Types/IHaveDefaultValue.cs
- src/GraphQL/Types/IProvideResolvedType.cs
I think its pretty self-explainatory
> Added IProvideResolvedType

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL/Utilities/Federation/FederatedSchemaPrinter.cs
- src/GraphQL/Utilities/SchemaPrinter.cs
> Add description to input object fields

- src/GraphQL/Utilities/SchemaPrinter.cs
> Add support for lists in default values

- docs2/site/docs/getting-started/query-organization.md
Addressing a question raised as issue #1761 .. just clarifying the steps needed to support using the query organisation.
> Clarification on the changes to queries when organisation is used.

- src/GraphQL/Execution/ExecutionHelper.cs
See code; it's an obvious mistake on my part.  This flaw is breaking tests within PR #1786
> Bug fix for wrapping InvalidValueException with itself

- src/GraphQL.Tests/Bugs/Bug1715.cs
- src/GraphQL/Types/Schema.cs
> Add checks for Schema.RegisterXXX methods

- src/GraphQL.NewtonsoftJson/DocumentWriter.cs
- src/GraphQL.SystemTextJson/DocumentWriter.cs
- src/GraphQL/IDocumentWriter.cs
Added some basic xml comments to the `IDocumentWriter` interface and the constructors of the applicable classes.
> Add xml comments to DocumentWriter

- src/Directory.Build.props
- src/GraphQL.Tests/GraphQL.Tests.csproj
Starting with version 3.0, consumers will finally see the documentation in their IDE :)
> Export xmldoc to nuget

- src/GraphQL.Tests/Bugs/Bug781UnobservedTasks.cs
> Add test for #781

- src/GraphQL.ApiTests/ApiApprovalTests.PublicApi.GraphQL.approved.txt
- src/GraphQL.Tests/Bugs/Bug1699InvalidEnum.cs
- src/GraphQL.Tests/Validation/DefaultValuesOfCorrectTypeTests.cs
- src/GraphQL/Execution/ExecutionHelper.cs
- src/GraphQL/Validation/Errors/DefaultValuesOfCorrectTypeError.cs
- src/GraphQL/Validation/Rules/DefaultValuesOfCorrectType.cs
Fixes #1818 
* Validation rule does not disallow default values for required variables
> Fix DefaultValuesOfCorrectType validation rule

- docs2/site/docs/guides/migration3.md
Add some more upgrade notes regarding `IResolveFieldContext` and `ExecutionStrategy` changes
> More upgrade notes

- appveyor.yml
- package.json
- src/Directory.Build.props
This is for the `develop` branch
> Bump version of develop branch to 4.0.0

- docs2/site/docs/getting-started/authorization.md
Closes #1848 
@sungam3r Can you check this? You know more about authorization and `IValidationRule` than me.
> Docs: Update authorization.md code sample

- src/Directory.Build.props
Change version numbers to 4.0.0-preview.build
> Change preview version number

- src/GraphQL.Tests/Bugs/Bug1889.cs
- src/GraphQL.Tests/Bugs/Bug1889_Nullability.cs
- src/GraphQL/GraphQLExtensions.cs
> fix check for interface covariance

- .github/workflows/wipcheck.yml
See #1901 
Note: checks should fail until removing the text "WIP" in the title of this PR.
@sungam3r Try it and see.
> Add check for [wip] in PR title

- src/GraphQL.Tests/Bugs/Bug1831.cs
- src/GraphQL/Execution/DocumentExecuter.cs
> Prevent variable parsing errors from masking validation errors

- src/GraphQL.sln
To make it easier to work from the VS.
> add solution folders

- .github/workflows/build-artifacts-code.yml
- .github/workflows/pr-tests-code.yml
- .github/workflows/wipcheck.yml
- src/Tests.props
> DOTNET_SKIP_FIRST_TIME_EXPERIENCE

- .github/workflows/build-artifacts-code.yml
- .github/workflows/publish-code.yml
> Fix GitHub Action scripts to push all nuget packages

- .editorconfig
- .github/labeler.yml
- .github/workflows/label.yml
- src/GraphQL.Harness.Tests/ScenarioExtensions.cs
- src/GraphQL.sln
Partially automates the labeling process.
> Add labeler

- docs2/site/docs/getting-started/introduction.md
See #1843 and https://github.com/graphql/graphql.github.io/pull/914
> Fix 'hello world' sample

- .github/workflows/publish-code.yml
I did some testing.  Pretty sure this is the only change necessary.  Hope so, anyway!
> Fix release workflow

- src/GraphQL.Tests/Utilities/FederatedSchemaBuilderTests.cs
- src/GraphQL/Utilities/Federation/FederatedSchemaBuilder.cs
When using a federated schema, a query such as
```graphql
query ($_representations: [_Any!]!) {
_entities(representations: $_representations) {
__typename
...on User {
id
}
}
}
```
including both the automatically added `__typename` and the query-requested `__typename` field, 
would throw a `NullReferenceException` in [GraphQL.Language.AST.SelectionSet.Merge](https://github.com/graphql-dotnet/graphql-dotnet/blob/5ef04659ec58e2589ed579917e07056a1eb423b8/src/GraphQL/Language/AST/SelectionSet.cs#L39) because the added `__typename` `Field` has a null `SelectionSet`. This scenario can be avoided by ensuring that we don't add the `__typename` field if it is already present in the selection set, as the comment suggested. Tests are added to `FederatedSchemaBuilderTests` to ensure that these …
> federation: check for existing __typename when modifying selection set

- src/GraphQL/Conversion/ValueConverter.cs
- src/GraphQL/DataLoader/DataLoaderContextAccessor.cs
- src/GraphQL/DataLoader/DataLoaderContextExtensions.cs
- src/GraphQL/DataLoader/DataLoaderDocumentListener.cs
- src/GraphQL/DataLoader/DataLoaderExtensions.cs
- src/GraphQL/Execution/ErrorInfoProvider.cs
- src/GraphQL/Execution/ExecutionError.cs
- src/GraphQL/Execution/ExecutionOptions.cs
See #1857
Mostly putting finishing touches on namespaces/classes already nearly complete.
- src/GraphQL/Conversion/ValueConverter.cs 
- src/GraphQL/DataLoader/DataLoaderContextAccessor.cs 
- src/GraphQL/DataLoader/DataLoaderContextExtensions.cs 
- src/GraphQL/DataLoader/DataLoaderDocumentListener.cs 
- src/GraphQL/DataLoader/DataLoaderExtensions.cs 
- src/GraphQL/Execution/ErrorInfoProvider.cs 
- src/GraphQL/Execution/ExecutionError.cs 
- src/GraphQL/Execution/ExecutionOptions.cs
> Add some xml docs

- src/GraphQL.Tests/Utilities/SchemaBuilderExecutionTests.cs
- src/GraphQL/Execution/ExecutionHelper.cs
- src/GraphQL/Reflection/IAccessor.cs
- src/GraphQL/Reflection/SingleMethodAccessor.cs
- src/GraphQL/Reflection/SinglePropertyAccessor.cs
- src/GraphQL/Resolvers/NameFieldResolver.cs
Relates to #1988 and #1155 .
@Shane32 I added tests for both method and property accessors.
> Retain stack trace and unwrap exception for SinglePropertyAccessor + add tests for #1155

- src/GraphQL/Resolvers/DelegateFieldModelBinderResolver.cs
See #2005 and #1988 
Also added xml comments - see #1857
> Retain stack trace and unwrap exception for DelegateFieldModelBinderResolver

- docs2/site/docs/getting-started/relay.md
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/ExecutionContext.cs
- src/GraphQL/Execution/ExecutionResult.cs
- src/GraphQL/Execution/GraphQLDocumentBuilder.cs
- src/GraphQL/Instrumentation/FieldMiddlewareBuilder.cs
- src/GraphQL/Instrumentation/FieldMiddlewareDelegate.cs
- src/GraphQL/Instrumentation/IFieldMiddleware.cs
- src/GraphQL/ResolveFieldContext/IResolveConnectionContext.cs
- src/GraphQL/ResolveFieldContext/IResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ReadonlyResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ResolveConnectionContext.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContextExtensions.cs
- src/GraphQL/Resolvers/AsyncFieldResolver.cs
- src/GraphQL/Resolvers/ExpressionFieldResolver.cs
- src/GraphQL/Resolvers/FieldResolverExtensions.cs
- src/GraphQL/Resolvers/FuncFieldResolver.cs
- src/GraphQL/Resolvers/IFieldResolver.cs
- src/GraphQL/Resolvers/NameFieldResolver.cs
- src/GraphQL/Types/Composite/AutoRegisteringObjectGraphType.cs
- src/GraphQL/Types/ISchema.cs
See #1857 
Mostly putting finishing touches on namespaces/classes already nearly complete.
* src/GraphQL/Execution/DocumentExecuter.cs 
* src/GraphQL/Execution/ExecutionContext.cs 
* src/GraphQL/Execution/ExecutionResult.cs 
* src/GraphQL/Execution/GraphQLDocumentBuilder.cs 
* src/GraphQL/Instrumentation/FieldMiddlewareBuilder.cs 
* src/GraphQL/Instrumentation/FieldMiddlewareDelegate.cs 
* src/GraphQL/Instrumentation/IFieldMiddleware.cs 
* src/GraphQL/ResolveFieldContext/IResolveConnectionContext.cs 
* src/GraphQL/ResolveFieldContext/IResolveFieldContext.cs 
* src/GraphQL/ResolveFieldContext/ReadonlyResolveFieldContext.cs 
* src/GraphQL/ResolveFieldContext/ResolveConnectionContext.cs 
* src/GraphQL/ResolveFieldContext/ResolveFieldContext.cs 
* …
> Add xml comments

- README.md
- docs2/site/docs/migrations/migration3.md
- src/GraphQL.sln
> Add migration docs

- src/Directory.Build.props
- src/GraphQL/Types/Fields/FieldType.cs
See #2019. Thi PR fixes second place.
> Fix schema first issue - custom scalar with default value as GraphQLTypeReference!

- src/Directory.Build.props
https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#enablenetanalyzers
> Add built-in analyzers

- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL/Execution/DocumentExecuter.cs
> Change DocumentExecuter.ExecuteAsync to virtual

- src/GraphQL.DataLoader.Tests/DataLoaderQueryTests.cs
- src/GraphQL.DataLoader.Tests/Types/QueryType.cs
- src/GraphQL/Execution/ExecutionNode.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
> Handle IDataLoaderResult properly within list graph types

- src/GraphQL/Execution/ExecutionNode.cs
> Add ExecutionNode constructor xml comments

- docs2/site/docs/migrations/migration4.md
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL/Instrumentation/ApolloTrace.cs
- src/GraphQL/Instrumentation/ApolloTracingExtensions.cs
See #2078 
Waiting for #2078 to be merged; then the xml comments will be further updated in this PR.
> Updates to Apollo tracing

- src/Directory.Build.props
- src/GraphQL/Types/Relay/ConnectionType.cs
While not exactly a breaking change, this can potentially change the schema, possibly breaking tests for users of the library.
Should this be included in the next major or minor revision?
> Update description for ConnectionType's edges field

- src/GraphQL/Execution/ExecutionHelper.cs
@sungam3r Perhaps you can help with the two methods marked TODO. Or I can remove the xml comment for those methods and we can revisit later.
> Add xml comments to ExecutionHelper

- src/GraphQL/Validation/Rules/VariablesAreInputTypes.cs
> Eliminate GraphTypeFromType call

- src/Directory.Build.props
- src/GraphQL.NewtonsoftJson/GraphQL.NewtonsoftJson.csproj
- src/GraphQL.SystemTextJson/GraphQL.SystemTextJson.csproj
- src/GraphQL/GraphQL.csproj
See https://github.com/graphql-dotnet/graphql-dotnet/runs/1646025982?check_suite_focus=true
> Unify icon

- src/GraphQL/Execution/ExecutionHelper.cs
see https://github.com/github/codeql/issues/4907
> Fix lgtm warning

- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL/DocumentWriterExtensions.cs
- src/GraphQL/EnumerableExtensions.cs
- src/GraphQL/Execution/DocumentExecutionListener.cs
- src/GraphQL/Execution/ExecutionNode.cs
- src/GraphQL/Execution/IExecutionContext.cs
- src/GraphQL/Execution/InputsExtensions.cs
- src/GraphQL/Execution/UnhandledExceptionContext.cs
- src/GraphQL/Language/AST/ISelection.cs
- src/GraphQL/ObjectExtensions.cs
- src/GraphQL/SchemaExtensions.cs
- src/GraphQL/StringExtensions.cs
- src/GraphQL/TypeExtensions.cs
- src/GraphQL/Types/Composite/InputObjectGraphType.cs
Some unused methods have been marked obsolete.
> More xml comments

- src/Directory.Build.props
- src/GraphQL.Benchmarks/Benchmarks/DeserializationBenchmark.cs
- src/GraphQL.Benchmarks/Benchmarks/ExecutionBenchmark.cs
- src/GraphQL.Benchmarks/Benchmarks/SerializationBenchmark.cs
- src/GraphQL.Benchmarks/GraphQL.Benchmarks.csproj
- src/GraphQL.Benchmarks/IntrospectionResult.cs
- src/GraphQL.Benchmarks/IntrospectionResult.json
- src/GraphQL.Benchmarks/Program.cs
- src/GraphQL.Benchmarks/SchemaIntrospection.cs
> Benchmark updates

- src/GraphQL/Utilities/SchemaBuilder.cs
> Bring back TypeExtensions.As calls

- src/GraphQL.ApiTests/GraphQL.SystemReactive.approved.txt
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.SystemReactive/SubscriptionDocumentExecuter.cs
- src/GraphQL.SystemReactive/SubscriptionExecutionStrategy.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/ParallelExecutionStrategy.cs
- src/GraphQL/Execution/SerialExecutionStrategy.cs
``` ini
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.14393.3986 (1607/AnniversaryUpdate/Redstone1)
Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
Frequency=3515611 Hz, Resolution=284.4456 ns, Timer=TSC
.NET Core SDK=5.0.102
[Host]     : .NET Core 3.1.11 (CoreCLR 4.700.20.56602, CoreFX 4.700.20.56604), X64 RyuJIT
DefaultJob : .NET Core 3.1.11 (CoreCLR 4.700.20.56602, CoreFX 4.700.20.56604), X64 RyuJIT
```
before
|        Method | UseCaching |         Mean |      Error |     StdDev |    Gen 0 |   Gen 1 | Gen 2 | Allocated |
|-------------- |----------- |-------------:|-----------:|-----------:|---------:|--------:|------:|----------:|
| **Introspection** |      **False** | **1,123.941 μs** | **12.4247 μs** | **11.0142 μs** | **105.4688** | **35.1563** | …
> Static strategy instances

- src/GraphQL.Benchmarks/Benchmarks/DetailedBenchmark.cs
Adds stage: DeserializeVars
```
|        Method |           Stage |             Mean |          Error |         StdDev |    Gen 0 |    Gen 1 | Gen 2 | Allocated |
|-------------- |---------------- |-----------------:|---------------:|---------------:|---------:|---------:|------:|----------:|
| Introspection |           Build | 5,433,452.031 ns | 18,541.4741 ns | 17,343.7064 ns | 414.0625 | 132.8125 |     - | 2626413 B |
| Introspection |           Parse |    17,797.519 ns |    164.6261 ns |    153.9913 ns |   1.8921 |   0.0610 |     - |   11920 B |
| Introspection |         Convert |     9,463.905 ns |     43.2809 ns |     40.4850 ns |   2.6550 |   0.1373 |     - |   16696 B |
| Introspection |        Validate |   179,113.175 ns |    636.5009 ns |    595.3833 ns |   1.7090 |        - | …
```
> Add deserialize-variables stage to benchmarks

- docs2/site/docs/migrations/migration4.md
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL/Types/IProvideMetadata.cs
- src/GraphQL/Utilities/MetadataProvider.cs
Replaces #2222 
|        Method | Stage |     Mean |     Error |    StdDev |    Gen 0 |    Gen 1 | Gen 2 | Allocated |
|-------------- |------ |---------:|----------:|----------:|---------:|---------:|------:|----------:|
| Before | Build | 5.447 ms | 0.0169 ms | 0.0150 ms | 414.0625 | 132.8125 |     - |   2.51 MB |
| After | Build | 5.453 ms | 0.0411 ms | 0.0365 ms | 390.6250 | 78.1250 |     - |   2.37 MB |
Changes pulled from #1451
> Lazy load Metadata property

- src/GraphQL.Benchmarks/Benchmarks/DetailedBenchmark.cs
- src/GraphQL.Benchmarks/Benchmarks/VariableBenchmark.cs
- src/GraphQL.StarWars/Types/CharacterInterface.cs
- src/GraphQL.StarWars/Types/DroidType.cs
- src/GraphQL.StarWars/Types/HumanType.cs
- src/GraphQL/Introspection/__Directive.cs
- src/GraphQL/Introspection/__EnumValue.cs
- src/GraphQL/Introspection/__Field.cs
- src/GraphQL/Introspection/__Type.cs
- src/GraphQL/Resolvers/ExpressionFieldResolver.cs
- src/GraphQL/Types/Composite/ComplexGraphType.cs
This is done following an investigation for #1451.
> Eliminate ExpressionFieldResolver

- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.Benchmarks.Merge/BenchmarkResult.cs
- src/GraphQL.Benchmarks.Merge/GraphQL.Benchmarks.Merge.csproj
- src/GraphQL.Benchmarks.Merge/Table.cs
- src/GraphQL.Benchmarks/Benchmarks/DetailedBenchmark.cs
- src/GraphQL.Harness/Startup.cs
- src/GraphQL.Tests/Bugs/Bug252ExecutorAppliesFIeldBuilderOnce.cs
- src/GraphQL.Tests/StarWars/StarWarsIntrospectionTests.cs
- src/GraphQL/AuthorizationExtensions.cs
- src/GraphQL/GraphQLExtensions.cs
- src/GraphQL/Introspection/__Type.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContextExtensions.cs
- src/GraphQL/Types/Collections/SchemaDirectives.cs
- src/GraphQL/Types/DirectiveGraphType.cs
- src/GraphQL/Types/Fields/FieldType.cs
- src/GraphQL/Types/Schema.cs
- src/GraphQL/Utilities/SchemaBuilder.cs
- src/GraphQL/Utilities/SchemaDirectiveVisitor.cs
Small fixes from #1451 not related to #1451 directly.
> Small fixes

- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.Tests/Utilities/NameValidatorTests.cs
- src/GraphQL/Types/Collections/SchemaTypes.cs
- src/GraphQL/Types/Composite/ComplexGraphType.cs
- src/GraphQL/Types/Fields/FieldType.cs
- src/GraphQL/Utilities/NameValidator.cs
> Fix name validator test

- src/GraphQL/Utilities/SchemaPrinter.cs
ArgumentOutOfRangeException with understandable message instead of NRE.
> SchemaPrinter fix for unknown enumeration value

- src/GraphQL.Tests/Bugs/Issue1874.cs
@sungam3r we can merge this, or not.  Just wanted to check that this worked the way I thought it did.
> Demo: Base64 conversion of byte arrays

- .github/workflows/test-code.yml
- src/GraphQL.MemoryCache/MemoryDocumentCacheOptions.cs
- src/GraphQL/DI/DefaultServiceProvider.cs
- src/GraphQL/DI/FuncServiceProvider.cs
- src/GraphQL/DataLoader/DataLoaderBase.cs
- src/GraphQL/Execution/ArgumentValue.cs
- src/GraphQL/Execution/ErrorInfoProviderOptions.cs
- src/GraphQL/Execution/ExecutionHelper.cs
- src/GraphQL/Execution/ExecutionOptions.cs
- src/GraphQL/Execution/ExecutionResult.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/Execution/Nodes/ExecutionNode.cs
- src/GraphQL/Execution/Nodes/NullExecutionNode.cs
- src/GraphQL/GraphQLExtensions.cs
- src/GraphQL/ObjectExtensions.cs
- src/GraphQL/Reflection/IAccessor.cs
- src/GraphQL/Resolvers/AsyncFieldResolver.cs
- src/GraphQL/Resolvers/IFieldResolver.cs
- src/GraphQL/Types/Composite/ComplexGraphType.cs
- src/GraphQL/Types/Composite/NonNullGraphType.cs
- src/GraphQL/Types/ISchema.cs
- src/GraphQL/Types/Scalars/EnumerationGraphType.cs
- src/GraphQL/Types/Scalars/ScalarGraphType.cs
- src/GraphQL/Validation/Rules/PossibleFragmentSpreads.cs
- src/GraphQL/Validation/TypeInfo.cs
See https://github.com/dotnet/format/issues/957 and https://github.com/dotnet/format/issues/955
> Update dotnet-format + langword in xml comments

- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL/GraphQLMetadataAttribute.cs
Fixes https://github.com/graphql-dotnet/server/issues/505
> Fix AttributeUsage on GraphQLAttribute

- docs2/site/docs/getting-started/metrics.md
> A little note about traces

- docs2/site/docs/migrations/migration4.md
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.Tests/Types/ComplexGraphTypeTests.cs
- src/GraphQL.Tests/Types/ListGraphTypeTests.cs
- src/GraphQL.Tests/Types/NonNullGraphTypeTests.cs
- src/GraphQL.Tests/Utilities/SchemaBuilderTests.cs
- src/GraphQL/Instrumentation/InstrumentFieldsMiddleware.cs
- src/GraphQL/TypeExtensions.cs
- src/GraphQL/Types/Composite/ListGraphType.cs
- src/GraphQL/Types/Composite/NonNullGraphType.cs
- src/GraphQL/Types/Directives/DirectiveGraphType.cs
- src/GraphQL/Types/IGraphType.cs
- src/GraphQL/Types/Scalars/EnumerationGraphType.cs
- src/GraphQL/Types/TypeExtensions.cs
- src/GraphQL/Utilities/AstPrinter.cs
- src/GraphQL/Utilities/Federation/FederatedSchemaPrinter.cs
- src/GraphQL/Utilities/SchemaPrinter.cs
- src/GraphQL/Validation/Errors/ArgumentsOfCorrectTypeError.cs
- src/GraphQL/Validation/Errors/DefaultValuesOfCorrectTypeError.cs
- src/GraphQL/Validation/Errors/FragmentsOnCompositeTypesError.cs
- src/GraphQL/Validation/Errors/KnownArgumentNamesError.cs
- src/GraphQL/Validation/Errors/PossibleFragmentSpreadsError.cs
- src/GraphQL/Validation/Errors/ProvidedNonNullArgumentsError.cs
- src/GraphQL/Validation/Errors/ScalarLeafsError.cs
- src/GraphQL/Validation/Errors/VariablesAreInputTypesError.cs
- src/GraphQL/Validation/Errors/VariablesInAllowedPositionError.cs
- src/GraphQL/Validation/Rules/KnownDirectives.cs
- src/GraphQL/Validation/Rules/VariablesAreInputTypes.cs
- src/GraphQL/Validation/ValidationContext.cs
> Type names are easier to get

- docs2/site/docs/migrations/migration4.md
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL/Types/ISchema.cs
- src/GraphQL/Types/Schema.cs
> Add ISchema.ValueConverters

- docs2/site/docs/migrations/migration4.md
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.Tests/StarWars/StarWarsSubFieldsTest.cs
- src/GraphQL/Execution/ExecutionHelper.cs
- src/GraphQL/Language/AST/Fields.cs
> Include fragment fields in context.SubFields

- src/GraphQL.Tests/Bugs/Bug1046.cs
- src/GraphQL.Tests/Bugs/Bug1156.cs
- src/GraphQL.Tests/Bugs/Bug2279.cs
- src/GraphQL/Types/Collections/SchemaTypes.cs
> Ignore duplicates in SchemaTypes.SetGraphType

- src/GraphQL.Tests/Complexity/ComplexityBasicTests.cs
- src/GraphQL.Tests/Complexity/ComplexityTestBase.cs
- src/GraphQL.Tests/Complexity/ComplexityTests.cs
- src/GraphQL.Tests/Complexity/ComplexityTestsWithLimits.cs
- src/GraphQL.Tests/Complexity/ComplexityValidationTests.cs
> New complexity tests

- docs2/site/docs/migrations/migration3.md
> Fix 2.x -> 3.0 migration document

- src/GraphQL.Tests/Bugs/Issue1837.cs
- src/GraphQL/GraphQLExtensions.cs
- src/GraphQL/Types/Collections/SchemaTypes.cs
- src/GraphQL/Types/Composite/ComplexGraphType.cs
- src/GraphQL/Types/Fields/FieldType.cs
- src/GraphQL/Types/QueryArgument.cs
> Fix for GraphQLExtensions.GetNamedType/IsInputType/IsOutputType

- src/GraphQL.Tests/Execution/ResolveFieldContextTests.cs
- src/GraphQL/Execution/ExecutionErrors.cs
- src/GraphQL/Execution/ExecutionResult.cs
fixes #2105 
Not all methods are synchronized. I didn't bother making the iterators synchronized.
> ExecutionErrors thread safe

- docs2/site/docs/getting-started/directives.md
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.Tests/Utilities/Visitors/DescriptionDirectiveVisitor.cs
- src/GraphQL.Tests/Utilities/Visitors/UppercaseDirectiveVisitor.cs
- src/GraphQL/SchemaExtensions.cs
- src/GraphQL/Utilities/Visitors/AppliedDirectivesValidationVisitor.cs
- src/GraphQL/Utilities/Visitors/BaseSchemaNodeVisitor.cs
- src/GraphQL/Utilities/Visitors/DeprecatedDirectiveVisitor.cs
- src/GraphQL/Utilities/Visitors/ISchemaNodeVisitor.cs
- src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs
> Rename ISchemaNodeVisitor methods, add additional checks

- src/GraphQL.Tests/Validation/ArgumentsOfCorrectTypeTests.cs
> Add tests for ArgumentsOfCorrectType

- src/GraphQL.Tests/Extensions/GraphQLExtensionsTests.cs
- src/GraphQL/GraphQLExtensions.cs
fixes #2334
also fixes behavior for non-null graph types in `ToAST`
> Fix IsValidDefault for single-item list + add tests

- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL/Utilities/FieldConfig.cs
- src/GraphQL/Utilities/SchemaBuilder.cs
> Add FieldConfig.DefaultValue

- docs2/site/docs/migrations/migration4.md
> Add migration notes for cleanup

- src/GraphQL.Tests/Files/JSON/HumanInputIntrospectionResult.json
- src/GraphQL.Tests/StarWars/StarWarsIntrospectionTests.cs
> Add test for #2233

- docs2/site/docs/getting-started/directives.md
- docs2/site/docs/getting-started/field-middleware.md
> Fix documentation links

- docs2/site/docs/migrations/migration4.md
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.Tests/Utilities/SchemaBuilderTests.cs
- src/GraphQL/Utilities/ArgumentConfig.cs
- src/GraphQL/Utilities/FieldConfig.cs
- src/GraphQL/Utilities/SchemaBuilder.cs
- src/GraphQL/Utilities/TypeConfig.cs
- src/GraphQL/Utilities/TypeSettings.cs
> Add ArgumentConfig and FieldConfig.ArgumentFor

- src/GraphQL.Tests/Bugs/Issue2387.cs
- src/GraphQL.Tests/Bugs/Issue2387_OverrideBuiltInScalars.cs
- src/GraphQL/Types/Collections/SchemaTypes.cs
- src/GraphQL/Types/TypeCollectionContext.cs
Includes tests for both code-first and schema-first.
> Allow overriding built-in scalar graph type

- docs2/site/docs/getting-started/schema-types.md
> Add type mapping documentation

- docs2/site/docs/migrations/migration4.md
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.StarWars/IoC/SimpleContainer.cs
- src/GraphQL.Tests/Bugs/Issue2387_OverrideBuiltInScalars.Alt.cs
- src/GraphQL.Tests/Bugs/Issue2392_OverrideBuiltInScalars_Alt.cs
- src/GraphQL.Tests/MsDiContainer.cs
- src/GraphQL.Tests/QueryTestBase.cs
- src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/SchemaExtensions.cs
- src/GraphQL/Types/Collections/SchemaDirectives.cs
- src/GraphQL/Types/Directives/DirectiveGraphType.cs
- src/GraphQL/Types/IProvideResolvedType.cs
- src/GraphQL/Types/ISchema.cs
- src/GraphQL/Types/Scalars/ScalarGraphType.cs
- src/GraphQL/Types/Schema.cs
- src/GraphQL/Utilities/Visitors/DeprecatedDirectiveVisitor.cs
Alternative to #2388. See https://github.com/graphql-dotnet/graphql-dotnet/pull/2388#issuecomment-797649109
> Replace scalar after schema initialization

- docs2/site/docs/getting-started/directives.md
- src/GraphQL.Tests/Files/JSON/AppliedDirectivesResult.json
- src/GraphQL.Tests/Introspection/AppliedDirectivesTests.cs
- src/GraphQL.Tests/Utilities/SchemaBuilderTests.cs
- src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs
- src/GraphQL/Introspection/__AppliedDirective.cs
- src/GraphQL/Introspection/__DirectiveArgument.cs
- src/GraphQL/Introspection/__InputValue.cs
- src/GraphQL/Types/Directives/AppliedDirective.cs
- src/GraphQL/Types/Directives/DirectiveArgument.cs
- src/GraphQL/Utilities/Visitors/AppliedDirectivesValidationVisitor.cs
Inspired by https://github.com/graphql-java/graphql-java/pull/2221#issuecomment-799582628 and further discussion.
> Directives cleanup

- docs2/site/docs/getting-started/custom-scalars.md
To align with ` return $"{vector3.X},{vector3.Y},{vector3.Z}";` and
```
var vector3Parts = vector3InputString.Split(',');
var x = float.Parse(vector3Parts[0]);
```
> Format scalar docs

- src/Directory.Build.props
- src/GraphQL.Tests/Types/FieldRegistrationTests.cs
- src/GraphQL.Tests/Types/SchemaTests.cs
- src/GraphQL/Types/Collections/SchemaTypes.cs
- src/GraphQL/Types/Fields/FieldType.cs
Fixes #2415 
@sungam3r I would like to merge this asap.
> Fix to SchemaTypes.RebuildType

- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.Tests/Types/ComplexGraphTypeTests.cs
- src/GraphQL/GlobalSwitches.cs
- src/GraphQL/TypeExtensions.cs
I'm not sure how this got set to false.  This should be fixed **_immediately_**.
> Delete UseRuntimeTypeMappings property

- .github/workflows/build-artifacts-code.yml
- .github/workflows/test-code.yml
- README.md
- docs2/site/docs/migrations/v0_11_0.md
- src/GraphQL.Benchmarks/GraphQL.Benchmarks.csproj
- src/GraphQL.Tests/Bugs/Bug1773.cs
- src/GraphQL/Execution/ExecutionOptions.cs
- src/GraphQL/Types/Scalars/ScalarGraphType.cs
> Disable MSVS Nuget feed on Windows build

- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL/MemoryExtensions.cs
- src/GraphQL/ObjectExtensions.cs
- src/GraphQL/SchemaExtensions.cs
- src/GraphQL/StringExtensions.cs
- src/GraphQL/TaskExtensions.cs
- src/GraphQL/TypeExtensions.cs
- src/GraphQL/VariableName.cs
> Apply NRT annotations on extensions

- docs2/site/docs/getting-started/global-switches.md
- docs2/site/sitemap.yml
- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.NewtonsoftJson/SchemaExtensions.cs
- src/GraphQL.SystemTextJson/SchemaExtensions.cs
- src/GraphQL.Tests/Bugs/Bug_nested_type_names_dont_conflict.cs
- src/GraphQL.sln
- src/GraphQL/GlobalSwitches.cs
- src/GraphQL/Types/GraphType.cs
> Introduce GlobalSwitches.UseDeclaringTypeNames

- src/Directory.Build.props
- src/GraphQL.Tests/Initialization/SchemaInitializationTests.cs
- src/GraphQL/Types/Composite/ObjectGraphTypeExtensions.cs
- src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs
> Add additional checks to SchemaValidationVisitor

- docs2/site/docs/migrations/migration4.md
> Update migration notes for ExecutionResult.Data

- docs2/site/docs/guides/dataloader.md
Describes how to create a data loader using OOP, and how to create a data loader with a global cache.
> Add more to data loader guide

- .github/workflows/build-artifacts-code.yml
- .github/workflows/publish-code.yml
- .github/workflows/test-code.yml
> Revert CI patch

- docs2/site/docs/getting-started/errors.md
- docs2/site/docs/guides/serialization.md
- docs2/site/sitemap.yml
> Serialization docs

- docs2/site/docs/getting-started/directives.md
> Update directives doc links

- docs2/site/docs/guides/document-caching.md
> Fix incorrect caching nuget package link

- docs2/site/docs/getting-started/relay.md
Fixes, https://github.com/graphql-dotnet/graphql-dotnet/issues/2593 @Shane32
> update relay doc

- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs
- src/GraphQL/Utilities/SchemaPrinter.cs
- src/GraphQL/Utilities/SchemaPrinterOptions.cs
> Allow schema printer to print descriptions according to 2018 GraphQL spec

- src/GraphQL.Tests/Utilities/SchemaBuilderTests.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/Utilities/SchemaBuilder.cs
> Schema builder parse descriptions

- src/GraphQL.Tests/Execution/SerialExecutionStrategyTests.cs
- src/GraphQL/Execution/SerialExecutionStrategy.cs
> Fix execution order of data loader nodes with serial execution strategy

- src/GraphQL.Tests/Bugs/Bug2635.cs
- src/GraphQL/Execution/ParallelExecutionStrategy.cs
- src/GraphQL/Execution/SerialExecutionStrategy.cs
> Ensure that all tasks are awaited before execution strategy ends

- src/GraphQL.Tests/Bugs/Issue1837.cs
- src/GraphQL.Tests/Initialization/SchemaInitializationTests.cs
- src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs
- src/GraphQL/Validation/ValidationContext.cs
> SchemaValidationVisitor now checks that ResolvedType was specified for Lists and NonNulls

- .github/dependabot.yml
- .github/labeler.yml
Already tested on SteroidsDI and other repos.
> Enable dependabot for github-actions

- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs
- src/GraphQL/Utilities/SchemaPrinter.cs
> Fix SchemaPrinter bug printing null lists

- src/GraphQL.ApiTests/GraphQL.approved.txt
- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.Tests/Utilities/SchemaBuilderTests.cs
- src/GraphQL/Types/Schema.cs
> Fix for 2695 - Schema.For does not always decode default values correctly

- docs2/site/docs/migrations/migration5.md
- src/GraphQL.ApiTests/GraphQL.MemoryCache.approved.txt
- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.MemoryCache/MemoryDocumentCache.cs
- src/GraphQL.Tests/Caching/DefaultCacheTests.cs
- src/GraphQL.Tests/Caching/MemoryCacheTests.cs
- src/GraphQL.Tests/Utilities/SchemaBuilderExecutionTests.cs
- src/GraphQL/Caching/DefaultDocumentCache.cs
- src/GraphQL/Caching/IDocumentCache.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/GraphQL.csproj
Hi, I redesigned the `IDocumentCache` with async getter and setter methods since I want to create a document cache implementation myself with `IDistributedCache` which has async APIs.
> Makes IDocumentCache asynchronous.

- src/GraphQL.MicrosoftDI.Tests/SelfActivatingServiceProviderTests.cs
- src/GraphQL.MicrosoftDI/GraphQLBuilder.cs
- src/GraphQL.MicrosoftDI/SelfActivatingServiceProvider.cs
- src/GraphQL.StarWars/IoC/SimpleContainer.cs
- src/GraphQL.Tests/DI/DefaultServiceProviderTests.cs
- src/GraphQL/DI/DefaultServiceProvider.cs
- src/GraphQL/DI/IConfigureSchema.cs
- src/GraphQL/DI/IGraphQLBuilder.cs
See review comments by @sungam3r on:
- #2571
> Suggested changes to IGraphQLBuilder

- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL/ConstrainedArray.cs
- src/GraphQL/Execution/ExecutionError.cs
- src/GraphQL/Introspection/ISchemaComparer.cs
- src/GraphQL/Language/AST/SourceLocation.cs
- src/GraphQL/Types/GraphQLTypeReference.cs
- src/GraphQL/Types/GraphType.cs
- src/GraphQL/Utilities/SchemaPrinter.cs
- src/GraphQL/Validation/Rules/NoUnusedFragments.cs
See check annotations here https://github.com/graphql-dotnet/graphql-dotnet/pull/2785/files
> Fix check annotations

- docs2/site/docs/migrations/migration5.md
Closes #2763 
Not much to do here... ???
> IDocumentCache migration docs for v5

- src/GraphQL/Execution/ParallelExecutionStrategy.cs
- src/GraphQL/Execution/SerialExecutionStrategy.cs
> Eliminate empty catch

- src/GraphQL.Tests/Bugs/Bug_nested_type_names_dont_conflict.cs
- src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs
- src/GraphQL/GraphQL.csproj
> Use System.Runtime.CompilerServices.Unsafe only for netstandard2.1

- docs2/site/docs/migrations/migration5.md
- src/GraphQL.ApiTests/GraphQL.MicrosoftDI.approved.txt
- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.DataLoader.Tests/GraphQLBuilderTests.cs
- src/GraphQL.DataLoader/GraphQLBuilderExtensions.cs
- src/GraphQL.MemoryCache/GraphQLBuilderExtensions.cs
- src/GraphQL.MicrosoftDI.Tests/GraphQLBuilderTests.cs
- src/GraphQL.MicrosoftDI/GraphQLBuilder.cs
- src/GraphQL.MicrosoftDI/GraphQLBuilderExtensions.cs
- src/GraphQL.NewtonsoftJson/GraphQLBuilderExtensions.cs
- src/GraphQL.SystemTextJson/GraphQLBuilderExtensions.cs
- src/GraphQL.Tests/DI/GraphQLBuilderBaseTests.cs
- src/GraphQL.Tests/DI/GraphQLBuilderTests.cs
- src/GraphQL/DI/GraphQLBuilderBase.cs
- src/GraphQL/DI/IGraphQLBuilder.cs
- src/GraphQL/DI/IServiceRegister.cs
- src/GraphQL/GraphQLBuilderExtensions.cs
> Split IGraphQLBuilder to IServiceRegister

- docs2/site/docs/migrations/migration5.md
- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Extensions/GraphQLExtensionsTests.cs
- src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs
- src/GraphQL/GraphQLExtensions.cs
- src/GraphQL/Types/Collections/SchemaTypes.cs
> Rename BuildNamedType into BuildGraphQLType

- src/GraphQL/Execution/DocumentExecuter.cs
> Allow query to be not specified

- src/GraphQL/Types/Composite/AutoRegisteringHelper.cs
- src/GraphQL/Types/Composite/AutoRegisteringInputObjectGraphType.cs
> Refactor existing classes to separate files

- docs2/site/docs/migrations/migration5.md
- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL/Annotations/IsExternalInit.cs
- src/GraphQL/Validation/BasicVisitor.cs
- src/GraphQL/Validation/DocumentValidator.cs
- src/GraphQL/Validation/Rules/5.7 - Directives/1+2. KnownDirectivesInAllowedLocations.cs
- src/GraphQL/Validation/Rules/5.8 - Variables/1. UniqueVariableNames.cs
- src/GraphQL/Validation/Rules/5.8 - Variables/2. VariablesAreInputTypes.cs
- src/GraphQL/Validation/Rules/5.8 - Variables/3. NoUndefinedVariables.cs
- src/GraphQL/Validation/Rules/5.8 - Variables/4. NoUnusedVariables.cs
- src/GraphQL/Validation/Rules/5.8 - Variables/5. VariablesInAllowedPosition.cs
- src/GraphQL/Validation/Rules/KnownFragmentNames.cs
- src/GraphQL/Validation/Rules/NoFragmentCycles.cs
- src/GraphQL/Validation/Rules/NoUnusedFragments.cs
- src/GraphQL/Validation/Rules/OverlappingFieldsCanBeMerged.cs
- src/GraphQL/Validation/Rules/PossibleFragmentSpreads.cs
- src/GraphQL/Validation/Rules/SingleRootFieldSubscriptions.cs
- src/GraphQL/Validation/TypeInfo.cs
- src/GraphQL/Validation/ValidationContext.GetRecursivelyReferencedFragments.cs
- src/GraphQL/Validation/ValidationContext.GetVariables.cs
- src/GraphQL/Validation/ValidationContext.cs
- src/GraphQL/Validation/ValidationOptions.cs
Further optimizations after parser v8:
Ref from #2863:
> Tune validation rules

- src/GraphQL.ApiTests/GraphQL.ApiTests.csproj
- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
Rel: https://github.com/PublicApiGenerator/PublicApiGenerator/issues/233
Thanks to @stakx
> Fix approval signatures

- docs2/site/docs/migrations/migration5.md
- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Types/EnumGraphTypeTests.cs
- src/GraphQL/GraphQLAttribute.cs
- src/GraphQL/GraphQLMetadataAttribute.cs
- src/GraphQL/IgnoreAttribute.cs
- src/GraphQL/MetadataAttribute.cs
- src/GraphQL/NameAttribute.cs
- src/GraphQL/Types/Scalars/EnumerationGraphType.cs
@sungam3r You may wish to review or incorporate this during your enum rework
> EnumerationGraphType supports GraphQLAttributes

- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Types/EnumGraphTypeTests.cs
- src/GraphQL/Types/Scalars/Enumeration/EnumerationGraphType.cs
> Allow parsing enum variable by native .NET type

- .github/workflows/label.yml
> Fix labeler

- docs2/site/docs/migrations/migration5.md
- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.MicrosoftDI/ScopedResolveConnectionContextAdapter.cs
- src/GraphQL.MicrosoftDI/ScopedResolveFieldContextAdapter.cs
- src/GraphQL.SystemReactive/SubscriptionExecutionStrategy.cs
- src/GraphQL.Tests/Bugs/Issue1981.cs
- src/GraphQL/Execution/DirectiveInfo.cs
- src/GraphQL/Execution/ExecutionHelper.cs
- src/GraphQL/ResolveFieldContext/IResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ReadonlyResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContext.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContextAdapter.cs
- src/GraphQL/ResolveFieldContext/ResolveFieldContextExtensions.cs
fixes #1981 
Suddenly, it was quite simple to add support for directives.
> Introduce IResolveFieldContext.Directives

- docs2/site/docs/getting-started/dependency-injection.md
- docs2/site/docs/migrations/migration5.md
- src/GraphQL.ApiTests/GraphQL.SystemReactive.approved.txt
- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.SystemReactive/GraphQLBuilderExtensions.cs
- src/GraphQL.SystemReactive/SubscriptionDocumentExecuter.cs
- src/GraphQL.Tests/DI/GraphQLBuilderBaseTests.cs
- src/GraphQL.Tests/DI/GraphQLBuilderTests.cs
- src/GraphQL.Tests/Execution/DocumentExecuterTests.cs
- src/GraphQL/DI/GraphQLBuilderBase.cs
- src/GraphQL/Execution/DefaultExecutionStrategySelector.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/ExecutionStrategyRegistration.cs
- src/GraphQL/Execution/IExecutionStrategySelector.cs
- src/GraphQL/GraphQLBuilderExtensions.cs
> Add ExecutionStrategySelector

- src/GraphQL.ApiTests/ApiApprovalTests.cs
- src/GraphQL.StarWars/Extensions/ResolveFieldContextExtensions.cs
- src/GraphQL.StarWars/IoC/SimpleContainer.cs
- src/GraphQL.StarWars/StarWarsData.cs
- src/GraphQL.StarWars/StarWarsMutation.cs
- src/GraphQL.StarWars/StarWarsQuery.cs
- src/GraphQL.StarWars/StarWarsSchema.cs
- src/GraphQL.StarWars/Types/CharacterInterface.cs
- src/GraphQL.StarWars/Types/DroidType.cs
- src/GraphQL.StarWars/Types/EpisodeEnum.cs
- src/GraphQL.StarWars/Types/HumanInputType.cs
- src/GraphQL.StarWars/Types/HumanType.cs
- src/GraphQL.StarWars/Types/StarWarsCharacter.cs
See https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/file-scoped-namespaces
For the demonstration I chose two projects in which conflicts should not arise with other PRs.
1 indentation saved! 😮 
Looks unusually IMO.
> Introduce file scoped namespaces [DEMONSTRATION]

- src/GraphQL.Tests/Bugs/Issue2932_DemoDIGraphType.cs
- src/GraphQL.Tests/Types/AutoRegisteringObjectGraphTypeTests.cs
- src/GraphQL/FromSource.cs
- src/GraphQL/Types/Composite/AutoRegisteringObjectGraphType.cs
This proposal might make more logical sense than #2932
> Alt for 2932 (supporting root types): support static methods

- src/GraphQL.ApiTests/GraphQL.MicrosoftDI.approved.txt
- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.MicrosoftDI/GraphQLBuilder.cs
- src/GraphQL.Tests/Bugs/BugWithCustomScalarsInDirective.cs
- src/GraphQL.Tests/Bugs/Issue2932_DemoDIGraphType.cs
- src/GraphQL.Tests/DI/GraphQLBuilderBaseTests.cs
- src/GraphQL.Tests/DI/GraphQLBuilderTests.cs
- src/GraphQL.Tests/DI/RegistrationTests.cs
- src/GraphQL.Tests/DI/UnsupportedRegistrationsTests.cs
- src/GraphQL.Tests/Execution/Performance/ListPerformanceTests.cs
- src/GraphQL.Tests/Execution/Performance/ThreadPerformanceTests.cs
- src/GraphQL.Tests/Execution/UnionInterfaceTests.cs
- src/GraphQL.Tests/QueryTestBase.cs
- src/GraphQL.Tests/StarWars/StarWarsTestBase.cs
- src/GraphQL/DI/IServiceRegister.cs
- src/GraphQL/DI/RegistrationCompareMode.cs
- src/GraphQL/GraphQLBuilderExtensions.cs
Rel: https://github.com/graphql-dotnet/server/issues/705
> Introduce RegistrationCompareMode

- .github/workflows/build-artifacts-code.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/publish-code.yml
- .github/workflows/test-code.yml
https://github.com/graphql-dotnet/graphql-dotnet/runs/5199930740?check_suite_focus=true works
https://github.com/graphql-dotnet/graphql-dotnet/runs/5207538082?check_suite_focus=true fails
> Lock SDK version on 6.0.102

- src/Directory.Build.props
- src/GraphQL.Tests/Types/TimeSpanMillisecondsGraphTypeTests.cs
- src/GraphQL.Tests/Types/TimeSpanSecondsGraphTypeTests.cs
> Add tests for TimeSpanMillisecondsGraphType/TimeSpanSecondsGraphType

- src/GraphQL.SystemTextJson/JsonConverterBigInteger.cs
> Fix STJ BigInteger JsonConverter

- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/DI/GraphQLBuilderBaseTests.cs
- src/GraphQL/DI/GraphQLBuilderBase.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/IDocumentExecuter.cs
Cherry pick of #3016 targeting the `master` branch.
> Add typed IDocumentExecuter (#3016)

- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL/Builders/FieldBuilder.cs
- src/GraphQL/Execution/ExecutionResult.cs
- src/GraphQL/Execution/SubscriptionExecutionStrategy.cs
- src/GraphQL/Resolvers/EventStreamMethodResolver.cs
- src/GraphQL/Resolvers/EventStreamResolver.cs
Partial towards #3022 
Contains only non-breaking changes in this PR.
> Non-breaking changes for renaming subscription stuff

- docs2/site/docs/migrations/migration5.md
> Add note about GetRecursiveVariables

- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL/Conversion/CamelCaseNameConverter.cs
- src/GraphQL/Conversion/DefaultNameConverter.cs
- src/GraphQL/Conversion/ValueConverter.cs
- src/GraphQL/Execution/DocumentError.cs
- src/GraphQL/Execution/ErrorInfoProvider.cs
- src/GraphQL/Execution/ExecutionError.cs
- src/GraphQL/Execution/ExecutionHelper.cs
- src/GraphQL/Types/Schema.cs
- src/GraphQL/Utilities/SchemaBuilder.cs
- src/GraphQL/Utilities/SchemaPrinter.cs
- src/GraphQL/Validation/Rules.Custom/InputFieldsAndArgumentsOfCorrectLength.cs
- src/GraphQL/Validation/ValidationError.cs
> Small code style and xmldoc fixes

- .github/workflows/test-code.yml
- src/Directory.Build.targets
- src/Tests.props
> Switch to coverlet.collector

- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/AuthorizationTests.cs
- src/GraphQL/Authorization/AuthorizationExtensions.cs
Merges into branch `allowanonymous` for #3079
> Rename to IsAnonymousAllowed

- docs2/site/docs/migrations/migration5.md
> Fix resolver docs

- src/GraphQL.Tests/Bugs/Bug3100.cs
- src/GraphQL/Types/Collections/SchemaTypes.cs
> Fix SchemaTypes so it does not create instances twice

- docs2/site/docs/migrations/migration6.md
- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Benchmarks/Benchmarks/DetailedBenchmark.cs
- src/GraphQL/Validation/BaseVariableVisitor.cs
- src/GraphQL/Validation/CompositeVariableVisitor.cs
- src/GraphQL/Validation/DocumentValidator.cs
- src/GraphQL/Validation/IVariableVisitor.cs
- src/GraphQL/Validation/Rules.Custom/InputFieldsAndArgumentsOfCorrectLength.cs
- src/GraphQL/Validation/ValidationContext.cs
> Convert IVariableVisitor to async

- docs2/site/docs/getting-started/directives.md
Replace DirectiveGraphType with Directive in Directive.md since DirectiveGraphType has been renamed to Directive.
> Replace DirectiveGraphType with Directive

- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL/GraphQLBuilderExtensions.cs
- src/GraphQL/Validation/Complexity/ComplexityAnalyzer.cs
- src/GraphQL/Validation/Complexity/IComplexityAnalyzer.cs
- src/GraphQL/Validation/Rules.Custom/ComplexityValidationRule.cs
> Mark IComplexityAnalyzer as obsolete

- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/IExecutionContext.cs
- src/GraphQL/Instrumentation/Metrics.cs
- src/GraphQL/Validation/DocumentValidator.cs
- src/GraphQL/Validation/Rules.Custom/ComplexityValidationRule.cs
- src/GraphQL/Validation/ValidationContext.cs
- src/GraphQL/Validation/ValidationOptions.cs
fixes #3176 
`IResolveFieldContext` and other bits already expose `Metrics` class so I did the same without new interface.
> Add ValidationContext.Metrics

- .github/workflows/dependency-review.yml
- src/GraphQL.sln
I saw this workflow in one of the watched projects and decided to try. At least it is very fast.
> Add dependency-review-action

- src/GraphQL.MemoryCache/AutomaticPersistedQueries/AutomaticPersistedQueriesExecutionBase.cs
- src/GraphQL.Tests/PersistedQueries/AutomaticPersistedQueriesTests.cs
https://www.apollographql.com/docs/apollo-server/performance/apq/:
> Handle both string and integer versions

- src/GraphQL.Tests/Bugs/Bug3194.cs
- src/GraphQL/Reflection/ReflectionHelper.cs
- src/GraphQL/Reflection/SingleMethodAccessor.cs
- src/GraphQL/Reflection/SinglePropertyAccessor.cs
> Fix inherited methods for schema builder

- docs2/site/docs/migrations/migration6.md
> AutoRegisteringObjectGraphType: Inherited methods migration note

- src/GraphQL.Tests/Complexity/ComplexityTests.cs
- src/GraphQL/Validation/Complexity/ComplexityAnalyzer.cs
Fixes #3221 
Two tests added (both failed previously, both pass now)
> Fix complexity analyzer

- .github/workflows/publish-documentation.yml
> Do not commit when working tree clean

- docs2/site/docs/getting-started/metrics.md
fixes https://github.com/graphql-dotnet/server/issues/404
> Add notes about metrics

- docs2/site/docs/migrations/migration5.md
> Update migration docs

- docs2/site/docs/migrations/migration7.md
- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Types/ComplexGraphTypeTests.cs
- src/GraphQL/Types/Composite/ComplexGraphType.cs
Allows for:
```cs
Field<int>("test")
.Resolve(_ => 123);
```
> Add Field overload with clr type

- docs2/site/docs/guides/known-issues.md
See repeated questions on this topic:
- https://github.com/graphql-dotnet/examples/issues/101#issuecomment-1197478809
- https://github.com/graphql-dotnet/graphql-dotnet/issues/3105
- https://github.com/graphql-dotnet/graphql-dotnet/issues/3156
> Add known issue for case insensitive enumeration value matching

- src/GraphQL.Tests/Bugs/Issue3233.cs
#3233 
Just to explicitly state the current status quo with serialization.
> Demonstrate issue 3233

- src/GraphQL.Harness/CountFieldMiddleware.cs
- src/GraphQL.Harness/GraphQLMiddleware.cs
- src/GraphQL.Harness/GraphQLSettings.cs
- src/GraphQL.Harness/GraphQLUserContext.cs
- src/GraphQL.Harness/Program.cs
- src/GraphQL.Harness/Startup.cs
> File-scoped namespaces for Harness project

- docs2/site/docs/getting-started/interfaces.md
> Update docs for ResolveType

- src/GraphQL.MemoryCache/MemoryCacheGraphQLBuilderExtensions.cs
- src/GraphQL.MemoryCache/MemoryDocumentCache.cs
- src/GraphQL.MemoryCache/MemoryDocumentCacheOptions.cs
- src/GraphQL.MicrosoftDI/ConnectionResolverBuilder.cs
- src/GraphQL.MicrosoftDI/DynamicScopedFieldResolver.cs
- src/GraphQL.MicrosoftDI/DynamicScopedSourceStreamResolver.cs
- src/GraphQL.MicrosoftDI/GraphQLBuilder.cs
- src/GraphQL.MicrosoftDI/MicrosoftDIGraphQLBuilderExtensions.cs
- src/GraphQL.MicrosoftDI/ResolverBuilder.cs
- src/GraphQL.MicrosoftDI/ScopedAttribute.cs
- src/GraphQL.MicrosoftDI/ScopedConnectionBuilderExtensions.cs
- src/GraphQL.MicrosoftDI/ScopedFieldBuilderExtensions.cs
- src/GraphQL.MicrosoftDI/ScopedFieldResolver.cs
- src/GraphQL.MicrosoftDI/ScopedResolveConnectionContextAdapter.cs
- src/GraphQL.MicrosoftDI/ScopedResolveFieldContextAdapter.cs
- src/GraphQL.MicrosoftDI/SelfActivatingServiceProvider.cs
> File-scoped namespaces for GraphQL.MemoryCache and GraphQL.MicrosoftDI

- docs2/site/docs/migrations/migration7.md
- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Builders/FieldBuilderTests.cs
- src/GraphQL/Builders/FieldBuilder.cs
> Add Argument overload with CLR type

- docs2/site/docs/migrations/migration7.md
Migration doc seems fine; just some minor tweaks.
> Migration notes updates

- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.DataLoader.Tests/Types/OrderType.cs
- src/GraphQL.DataLoader.Tests/Types/QueryType.cs
- src/GraphQL.DataLoader.Tests/Types/UserType.cs
- src/GraphQL.Tests/Bugs/Bug2279.cs
- src/GraphQL/Types/Composite/ComplexGraphType.cs
> Restore `Field<TGraphType>()` method

- src/GraphQL.Benchmarks/Benchmarks/DetailedBenchmark.cs
- src/GraphQL.Benchmarks/GraphQL.Benchmarks.csproj
> Bump BenchmarkDotNet from 0.13.1 to 0.13.2

- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Types/UnionGraphTypeTests.cs
- src/GraphQL/Types/Collections/SchemaTypes.cs
- src/GraphQL/Types/GraphQLTypeReference.cs
> Update UnionGraphType to support CLR references

- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL/Extensions/AuthorizationExtensions.cs
See https://github.com/graphql-dotnet/server/discussions/925
> Add missing authorization extensions from field and connection builders

- src/GraphQL/GraphQL.csproj
> Switch to Nullability.Source

- src/GraphQL.Tests/Bugs/Issue3370.cs
- src/GraphQL.Tests/Validation/ArgumentsOfCorrectTypeTests.cs
- src/GraphQL/Validation/ValidationContext.cs
> Fix validation of literal objects containing no properties

- src/GraphQL.Tests/Bugs/Issue3370.cs
- src/GraphQL.Tests/Validation/ArgumentsOfCorrectTypeTests.cs
- src/GraphQL/Validation/ValidationContext.cs
Fix for issue #3370
Cherry-pick of #3371
> v5 fix: Fix validation of literal objects containing no properties (#3371)

- .github/workflows/build-artifacts-code.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/publish-code.yml
- .github/workflows/test-code.yml
- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
See #3379. For some reason new commits did not get into it.
> Setup dotnet

- src/GraphQL/Execution/ExecutionResult.cs
> Add missed properties in ExecutionResult copy-ctor

- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL/Types/Schema.cs
> Prevent Schema.AllTypes too early initialization under debugger

- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Types/AutoRegisteringInputObjectGraphTypeTests.cs
- src/GraphQL.Tests/Types/AutoRegisteringInterfaceGraphTypeTests.cs
- src/GraphQL.Tests/Types/AutoRegisteringObjectGraphTypeTests.cs
- src/GraphQL.Tests/Utilities/GetGraphTypeFromTypeTests.cs
- src/GraphQL/Attributes/InputTypeAttribute.cs
- src/GraphQL/Attributes/OutputTypeAttribute.cs
- src/GraphQL/Extensions/TypeExtensions.cs
Demonstration.
See https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-11#generic-attributes
As I understand these may be problems on machines with compiler version less than 17.1
> Introduce generic attributes

- src/GraphQL.Tests/Bugs/Bug3331.cs
- src/GraphQL.Tests/Types/Collections/SchemaTypesTests.cs
- src/GraphQL/Types/Collections/SchemaTypes.cs
- src/GraphQL/Types/Schema.cs
Continuation of #3402 in light of #3374
> Change some error messages

- src/GraphQL/Utilities/ServiceProviderExtensions.cs
> Change error message for GetRequiredService

- src/GraphQL.NewtonsoftJson/GraphQL.NewtonsoftJson.csproj
- src/GraphQL.NewtonsoftJson/JsonSerializerSettings.cs
> Bump Newtonsoft.Json from 13.0.1 to 13.0.2

- docs2/site/docs/migrations/migration7.md
- src/GraphQL.ApiTests/net5/GraphQL.approved.txt
- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Benchmarks/Benchmarks/DetailedBenchmark.cs
- src/GraphQL/Validation/DocumentValidator.cs
- src/GraphQL/Validation/ValidationContext.cs
fixes #3418 
I just copied `GetVariableValuesAsync` body with little changes to return errors.
> New method to get variables values

- src/GraphQL/GraphQL.csproj
> Bump Nullability.Source

- src/Directory.Build.targets
https://learn.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items?view=vs-2022#content
> Hide logo and readme in Solution Explorer

- src/GraphQL.Tests/Complexity/ComplexityValidationTests.cs
- src/GraphQL/Validation/Complexity/ComplexityAnalyzer.cs
- src/GraphQL/Validation/Complexity/ComplexityResult.cs
> Better error messages for ComplexityAnalyzer

- src/GraphQL.Tests/Bugs/Bug2958DecimalPrecisionTests.cs
- src/GraphQL.Tests/Extensions/GraphQLExtensionsTests.cs
- src/GraphQL.Tests/Extensions/PrintTests.cs
- src/GraphQL.Tests/GraphQLSerializersTestData.cs
- src/GraphQL.Tests/TheoryExAttribute.cs
- src/GraphQL.Tests/TheoryExDiscoverer.cs
- src/GraphQL.Tests/Types/TimeSpanMillisecondsGraphTypeTests.cs
- src/GraphQL.Tests/Types/TimeSpanSecondsGraphTypeTests.cs
- src/GraphQL.Tests/Utilities/GetGraphTypeFromTypeTests.cs
- src/GraphQL.Tests/ValueConverterFacts.cs
> Get rid of xunit serialization warnings

- src/GraphQL.ApiTests/net5/GraphQL.approved.txt
- src/GraphQL.ApiTests/net6/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Bugs/Bug3331.cs
- src/GraphQL.Tests/Types/Collections/SchemaTypesTests.cs
- src/GraphQL/GlobalSwitches.cs
- src/GraphQL/Types/Collections/SchemaTypes.cs
- src/GraphQL/Types/TypeCollectionContext.cs
> Additional trace information in exception messages during schema initialization

- src/GraphQL.AotCompilationSample.TypeFirst/Program.cs
This change eliminates the use of `Preserve` in the type-first AOT compilation sample, and removes old comments that are not applicable to the sample.
> Update sample application for AOT type-first

- src/GraphQL/Extensions/ObjectExtensions.cs
Fixes build problems with latest .NET SDK.  No effective code changes or public API changes.
> Fix NRT attributes in ObjectExtensions.cs

- src/GraphQL.MemoryCache/AutomaticPersistedQueries/PersistedQueryBadHashError.cs
- src/GraphQL.MemoryCache/AutomaticPersistedQueries/PersistedQueryNotFoundError.cs
- src/GraphQL.MemoryCache/AutomaticPersistedQueries/PersistedQueryUnsupportedVersionError.cs
- src/GraphQL.Tests/PersistedQueries/AutomaticPersistedQueriesTests.cs
> Update APQ messages

- .vscode/tasks.json
- src/GraphQL.ApiTests/ApiApprovalTests.cs
- src/GraphQL.ApiTests/GraphQL.ApiTests.csproj
- src/GraphQL.ApiTests/net50/GraphQL.MicrosoftDI.approved.txt
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
Many fixes in public API surface.
> Bump PublicApiGenerator to v11

- docs2/site/docs/migrations/migration7.md
- src/GraphQL/ExperimentalFeatures.cs
- src/GraphQL/Extensions/SchemaExtensions.cs
> Add migration notes about deprecation of input values

- .github/workflows/build-artifacts-code.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/format.yml
- .github/workflows/publish-code.yml
- .github/workflows/test-code.yml
```
Run dotnet build --no-restore -c Release
MSBuild version 17.5.1+f6fdcf537 for .NET
```
> Revert to version 3 of setup-dotnet

- src/GraphQL.Tests/Subscription/SubscriptionExecutionStrategyTests.cs
- src/GraphQL.Tests/Validation/SingleRootFieldSubscriptionsTests.cs
- src/GraphQL/Validation/Errors/SingleRootFieldSubscriptionsError.cs
- src/GraphQL/Validation/Rules/SingleRootFieldSubscriptions.cs
> The root field of a subscription operation must not be an introspection field

- src/Directory.Build.props
- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/GraphQL.csproj
- src/GraphQL/Types/Composite/InputObjectGraphType.cs
- src/GraphQL/Types/Scalars/Enumeration/EnumerationGraphType.cs
- src/GraphQL/Utilities/Federation/FederatedSchemaBuilder.cs
- src/GraphQL/Utilities/SchemaBuilder.cs
> Make GraphQL.NET to be binary compatible with parser v9

- src/GraphQL.Tests/Subscription/ObservableExtensionsTests.cs
- src/GraphQL/Extensions/ObservableExtensions.cs
> Catch exceptions during Subscribe and pass to the unhandled exception delegate

- docs2/site/docs/migrations/migration7.md
I have removed the ConfiureAwait calls because it is generally not advisable and also in this case it also is not really needed.
> Don't use ConfigureAwait in docs

- docs2/site/docs/getting-started/directives.md
- docs2/site/docs/getting-started/errors.md
- docs2/site/docs/getting-started/field-middleware.md
- docs2/site/docs/getting-started/unions.md
Fixed links in the documentation
> #3702 Broken links in documentation

- src/GraphQL.Federation.SchemaFirst.Sample1/GraphQL.Federation.SchemaFirst.Sample1.csproj
- src/GraphQL.Federation.SchemaFirst.Sample2/GraphQL.Federation.SchemaFirst.Sample2.csproj
> Prevent sample federation projects from publishing

- docs2/site/docs/analyzers/GQL008_DoNotUseObsoleteArgumentMethod.md
- docs2/site/docs/analyzers/Overview.md
- src/GraphQL.Analyzers.CodeFixes/FieldArgumentCodeFixProvider.cs
- src/GraphQL.Analyzers.CodeFixes/FieldBuilderCodeFixProvider.cs
- src/GraphQL.Analyzers.CodeFixes/FieldNameCodeFixProvider.cs
- src/GraphQL.Analyzers.Tests/FieldArgumentAnalyzerTests.cs
- src/GraphQL.Analyzers/AnalyzerReleases.Unshipped.md
- src/GraphQL.Analyzers/Constants.cs
- src/GraphQL.Analyzers/DiagnosticIds.cs
- src/GraphQL.Analyzers/Extensions.cs
- src/GraphQL.Analyzers/FieldArgumentAnalyzer.cs
- src/GraphQL.Analyzers/FieldBuilderAnalyzer.cs
- src/GraphQL.Analyzers/FieldNameAnalyzer.cs
- src/GraphQL.Analyzers/HelpLinks.cs
- src/GraphQL.sln
Rewrite this
```c#
Field<StringGraphType>("Text").Argument<StringGraphType, string>(
"arg",
"description",
"MyDefault");
```
With this
```c#
Field<StringGraphType>("Text").Argument<StringGraphType>(
"arg",
"description",
argument => argument.DefaultValue = "MyDefault");
```
> FieldArgumentAnalyzer

- src/GraphQL.Tests/Bugs/SpecIssues.cs
Verifies that behavior of GraphQL.NET is correct.
See:
- https://github.com/graphql/graphql-spec/pull/1056
- https://github.com/graphql/graphql-spec/pull/1057
> Add tests for spec issues

- src/GraphQL.DataLoader.Tests/ApolloTracingTests.cs
> Stabilize Apollo tracing test

- docs2/site/docs/analyzers/GQL011_MustNotBeConvertibleToGraphType.md
- docs2/site/docs/analyzers/Overview.md
- src/GraphQL.Analyzers.Tests/NotAGraphTypeAnalyzerTests.cs
- src/GraphQL.Analyzers/AnalyzerReleases.Unshipped.md
- src/GraphQL.Analyzers/AwaitableResolverAnalyzer.cs
- src/GraphQL.Analyzers/FieldArgumentAnalyzer.cs
- src/GraphQL.Analyzers/FieldBuilderAnalyzer.cs
- src/GraphQL.Analyzers/FieldNameAnalyzer.cs
- src/GraphQL.Analyzers/Helpers/Constants.cs
- src/GraphQL.Analyzers/Helpers/DiagnosticIds.cs
- src/GraphQL.Analyzers/Helpers/HelpLinks.cs
- src/GraphQL.Analyzers/InputGraphTypeAnalyzer.cs
- src/GraphQL.Analyzers/NotAGraphTypeAnalyzer.cs
- src/GraphQL.Analyzers/ResolverAnalyzer.cs
- src/GraphQL.sln
- src/GraphQL/Attributes/NotAGraphTypeAttribute.cs
- src/GraphQL/Builders/ConnectionBuilder.cs
- src/GraphQL/Builders/ConnectionBuilder_Typed.cs
- src/GraphQL/Builders/FieldBuilder.cs
- src/GraphQL/DataLoader/IDataLoaderResult.cs
- src/GraphQL/Types/AutoSchema.cs
- src/GraphQL/Types/Composite/AutoRegisteringInputObjectGraphType.cs
- src/GraphQL/Types/Composite/AutoRegisteringInterfaceGraphType.cs
- src/GraphQL/Types/Composite/AutoRegisteringObjectGraphType.cs
- src/GraphQL/Types/Composite/ComplexGraphType.cs
- src/GraphQL/Types/Composite/InputObjectGraphType.cs
- src/GraphQL/Types/Composite/InterfaceGraphType.cs
- src/GraphQL/Types/Composite/ObjectGraphType.cs
- src/GraphQL/Types/GraphQLTypeReference.cs
Merging master to develop with a PR because there were many conflicts, and I wanted another pair of eyes to verify I didn't miss something.
> Merge NotAGraphTypeAnalyzer to develop branch

- src/GraphQL/GraphQL.csproj
> Bump parser to 8.4.2

- src/GraphQL.Analyzers/AnalyzerReleases.Shipped.md
- src/GraphQL.Analyzers/AnalyzerReleases.Unshipped.md
- src/GraphQL.Analyzers/Helpers/HelpLinks.cs
@Shane32, we need another release to fix the help links.
> Fix analyzers help links

- docs2/site/docs/analyzers/gql004.md
- docs2/site/docs/analyzers/gql006.md
- docs2/site/docs/analyzers/gql007.md
@Shane32, I think this is the last fix. You can release the 7.7.1 after this PR is merged.
> Misc doc fixes

- src/GraphQL.Tests/Bugs/Bug3825.cs
- src/GraphQL/Introspection/__Type.cs
> Deprecated fields are returned when feature is disabled

- src/GraphQL.Tests/Execution/InputConversionNewtonsoftJsonTests.cs
- src/GraphQL.Tests/Execution/InputConversionSystemTextJsonTests.cs
> Fix json tests

- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Extensions/TypeExtensionTests.cs
- src/GraphQL/Extensions/TypeExtensions.cs
- src/GraphQL/GlobalSwitches.cs
- src/GraphQL/Types/GraphType.cs
> Change default type naming

- src/GraphQL.Tests/Types/ObjectGraphTypeTests.cs
- src/GraphQL/Extensions/TypeExtensions.cs
- src/GraphQL/Introspection/__AppliedDirective.cs
- src/GraphQL/Introspection/__Directive.cs
- src/GraphQL/Introspection/__DirectiveArgument.cs
- src/GraphQL/Introspection/__EnumValue.cs
- src/GraphQL/Introspection/__Field.cs
- src/GraphQL/Introspection/__InputValue.cs
- src/GraphQL/Introspection/__Schema.cs
- src/GraphQL/Introspection/__Type.cs
After working on #3842, I realized some additional changes need to be made for proper support of the new feature.
> Updates to new GraphQLName function

- docs2/site/docs/migrations/migration8.md
- src/GraphQL.ApiTests/GraphQL.DataLoader.approved.txt
- src/GraphQL.DataLoader/Extensions/DataLoaderContextExtensions.cs
- src/GraphQL.DataLoader/Extensions/DataLoaderExtensions.cs
> Change DataLoader extensions' namespace to GraphQL

- src/GraphQL.Tests/Bugs/Bug3089.cs
- src/GraphQL/Execution/DocumentExecuter.cs
> Mix errors from validation and listener

- docs2/site/docs/getting-started/directives.md
- docs2/site/docs/getting-started/field-middleware.md
- docs2/site/docs/getting-started/schema-types.md
- docs2/site/docs/guides/known-issues.md
> Fix docs relative links

- docs2/site/docs/getting-started/dependency-injection.md
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/DI/GraphQLBuilderExtensionTests.cs
- src/GraphQL/Extensions/GraphQLBuilderExtensions.cs
To simplify examples in #3873 and #3885
> Add 'AddSchemaVisitor' builder extension method

- docs2/site/docs/getting-started/subscriptions.md
- src/GraphQL.Tests/Subscription/SubscriptionSchema.cs
Use field builders vs `AddField`
> Clean up subscription sample

- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Types/AutoRegisteringInputObjectGraphTypeTests.cs
- src/GraphQL.Tests/Types/AutoRegisteringObjectGraphTypeTests.cs
- src/GraphQL.Tests/Types/InputObjectGraphTypeTests.cs
- src/GraphQL.Tests/Types/QueryArgumentTests.cs
- src/GraphQL/Builders/FieldBuilder.cs
- src/GraphQL/Execution/ExecutionHelper.cs
- src/GraphQL/Extensions/QueryArgumentExtensions.cs
- src/GraphQL/Types/Fields/FieldType.cs
- src/GraphQL/Types/QueryArgument.cs
- src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs
I think this might be a better design, as it is compatible with the `+=` and `-=` operators of C#.
> Nullable Validator and Parser delegates

- src/GraphQL.Tests/ObjectExtensionsTest.cs
- src/GraphQL/Extensions/ObjectExtensions.Compiled.cs
- src/GraphQL/Extensions/TypeExtensions.cs
> Federation prep: Refactor TypeExtensions.GetListType

- src/GraphQL/Extensions/GraphQLBuilderExtensions.cs
> Document GraphQLTelemetryProvider.SourceName

- src/GraphQL.Tests/Utilities/SchemaExporterTests.Federation1Schema.approved.txt
- src/GraphQL.Tests/Utilities/SchemaExporterTests.Federation2Schema.approved.txt
- src/GraphQL.Tests/Utilities/SchemaExporterTests.StarWarsSchema.approved.txt
- src/GraphQL.Tests/Utilities/SchemaExporterTests.cs
> Update schema exporter tests

- docs2/site/docs/migrations/migration8.md
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL/Extensions/SchemaExtensions.cs
- src/GraphQL/Utilities/Visitors/AppliedDirectivesValidationVisitor.cs
- src/GraphQL/Utilities/Visitors/BaseSchemaNodeVisitor.cs
- src/GraphQL/Utilities/Visitors/ISchemaNodeVisitor.cs
Prerequisite for code-first federation in #3921 .  Targets v8.
> Add ISchemaNodeVisitor.PostVisitSchema

- docs2/site/docs/migrations/migration8.md
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Bugs/Bug947.cs
- src/GraphQL.Tests/Types/AutoRegisteringInputObjectGraphTypeTests.cs
- src/GraphQL/Federation/Types/AnyScalarGraphType.cs
- src/GraphQL/Federation/Types/EntityGraphType.cs
- src/GraphQL/Federation/Types/FieldSetGraphType.cs
- src/GraphQL/Federation/Types/LinkImportGraphType.cs
- src/GraphQL/Federation/Types/LinkPurpose.cs
- src/GraphQL/Federation/Types/LinkPurposeGraphType.cs
- src/GraphQL/Federation/Types/ServiceGraphType.cs
- src/GraphQL/Utilities/Federation/FederatedSchemaBuilder.cs
> Add GraphQL Federation v2 required types

- docs2/site/docs/analyzers/gql004.md
- src/GraphQL.Analyzers.CodeFixes/FieldBuilderCodeFixProvider.cs
- src/GraphQL.Analyzers.CodeFixes/Helpers/DocumentEditorExtensions.cs
- src/GraphQL.Analyzers.CodeFixes/Helpers/EnumerableExtensions.cs
- src/GraphQL.Analyzers.Tests/FieldBuilderAnalyzerTests.cs
- src/GraphQL.Analyzers/FieldBuilderAnalyzer.cs
- src/GraphQL.Analyzers/Helpers/Constants.cs
- src/GraphQL.Analyzers/Helpers/ExpressionExtensions.cs
Rewrite obsolete expression based field builder when both `nullable` and `type` parameters are used.
> Expression based field builder analyzer

- docs2/site/docs/migrations/migration7.md
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Subscription/ShouldlyExtensions.cs
- src/GraphQL.Tests/Types/ComplexGraphTypeTests.cs
- src/GraphQL/GlobalSwitches.cs
- src/GraphQL/Types/Composite/ComplexGraphType.cs
> Infer field nullability from NRT

- src/GraphQL.Tests/Bugs/Bug3988.cs
- src/GraphQL.Tests/Validation/PossibleFragmentSpreadsTests.cs
- src/GraphQL/Validation/Rules/PossibleFragmentSpreads.cs
> PossibleFragmentSpreads validation rule bug fix for inline fragment spreads

- docs2/site/docs/getting-started/dependency-injection.md
- docs2/site/docs/migrations/migration8.md
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.MemoryCache/AutomaticPersistedQueries/AutomaticPersistedQueriesExecutionBase.cs
- src/GraphQL.MemoryCache/MemoryCacheGraphQLBuilderExtensions.cs
- src/GraphQL.NewtonsoftJson/GraphQLRequestJsonConverter.cs
- src/GraphQL.SystemTextJson/GraphQLRequestJsonConverter.cs
- src/GraphQL.Tests/PersistedQueries/PersistedDocumentTests.cs
- src/GraphQL.Tests/Serialization/GraphQLRequestTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/Errors/ExecutionErrors.cs
- src/GraphQL/Execution/ExecutionOptions.cs
- src/GraphQL/Execution/ExecutionResult.cs
- src/GraphQL/Extensions/GraphQLBuilderExtensions.cs
- src/GraphQL/PersistedDocuments/DocumentIdInvalidError.cs
- src/GraphQL/PersistedDocuments/DocumentIdMissingError.cs
- src/GraphQL/PersistedDocuments/DocumentNotFoundError.cs
- src/GraphQL/PersistedDocuments/IPersistedDocumentLoader.cs
- src/GraphQL/PersistedDocuments/InvalidRequestError.cs
- src/GraphQL/PersistedDocuments/PersistedDocumentHandler.cs
- src/GraphQL/PersistedDocuments/PersistedDocumentOptions.cs
- src/GraphQL/Transport/GraphQLRequest.cs
Adds "Persisted Documents" support based on the spec here:
- https://github.com/graphql/graphql-over-http/pull/264
> Add persisted document support

- docs2/site/docs/analyzers/gql015.md
- src/GraphQL.Analyzers.Tests/FieldBuilderAnalyzerTests.cs
- src/GraphQL.Analyzers/AnalyzerReleases.Unshipped.md
- src/GraphQL.Analyzers/FieldBuilderAnalyzer.cs
- src/GraphQL.Analyzers/Helpers/DiagnosticIds.cs
- src/GraphQL.Analyzers/Helpers/HelpLinks.cs
- src/GraphQL.sln
> GQL015 Can't infer field name analyzer

- docs2/site/docs/guides/complexity-analyzer.md
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Complexity/ComplexityTests.cs
- src/GraphQL/Attributes/ComplexityAttribute.cs
- src/GraphQL/Utilities/FieldConfig.cs
- src/GraphQL/Validation/Complexity/IFieldComplexityAnalyzer.cs
> Add complexity attribute

- src/GraphQL.Analyzers.Tests/VerifiersExtensions/CSharpCodeFixVerifier.cs
- src/GraphQL.Analyzers.Tests/VerifiersExtensions/ReferenceResolver.cs
See https://github.com/dotnet/roslyn-sdk/pull/1160/files
> Reuse ReferenceAssemblies

- docs2/site/sitemap.yml
- src/GraphQL.Analyzers/AnalyzerReleases.Shipped.md
- src/GraphQL.Analyzers/AnalyzerReleases.Unshipped.md
Fill free to merge when you are ready to release 7.9 (or before)
> Ship analyzers with 7.9

- src/GraphQL.Analyzers.Tests/AllowedOnAnalyzerTests.cs
- src/GraphQL.Analyzers/AllowedOnAnalyzer.cs
> Fix NRE in AllowedOnAnalyzer when analyzed assebly name starts with GraphQL prefix

- src/GraphQL.Tests/Types/BooleanGraphTypeTests.cs
- src/GraphQL.Tests/Types/ByteGraphTypeTests.cs
- src/GraphQL.Tests/Types/ComplexScalarGraphTypeTests.cs
- src/GraphQL.Tests/Types/DecimalGraphTypeTests.cs
- src/GraphQL.Tests/Types/FloatGraphTypeTests.cs
- src/GraphQL.Tests/Types/GuidGraphTypeTests.cs
- src/GraphQL.Tests/Types/IdGraphTypeTests.cs
- src/GraphQL.Tests/Types/IntGraphTypeTests.cs
- src/GraphQL.Tests/Types/LongGraphTypeTests.cs
- src/GraphQL.Tests/Types/SByteGraphTypeTests.cs
- src/GraphQL.Tests/Types/ScalarGraphTypeTest.cs
- src/GraphQL.Tests/Types/ShortGraphTypeTests.cs
- src/GraphQL.Tests/Types/StringGraphTypeTests.cs
- src/GraphQL.Tests/Types/UIntGraphTypeTests.cs
- src/GraphQL.Tests/Types/ULongGraphTypeTests.cs
- src/GraphQL.Tests/Types/UShortGraphTypeTests.cs
- src/GraphQL/Types/Scalars/ComplexScalarGraphType.cs
- src/GraphQL/Types/Scalars/IdGraphType.cs
- src/GraphQL/Types/Scalars/ScalarGraphType.cs
> Fix SerializeList code

- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL/Attributes/DirectiveAttribute.cs
> Make values nullable for DirectiveArgument

- src/GraphQL.Tests/Bugs/Bug4059.cs
- src/GraphQL/Introspection/__Field.cs
> Deprecated arguments are returned when feature is disabled

- src/GraphQL.Tests/Bugs/Bug4064.cs
- src/GraphQL/Validation/ValidationContext.cs
Already works for ints and strings, but IDictionary is incorrectly recognized as a list
> Bug fix for issue 4064: object cannot be coerced to a list of objects

- src/GraphQL.Tests/Bugs/Bug1046.cs
- src/GraphQL.Tests/Bugs/Issue4075.cs
- src/GraphQL/Conversion/ValueConverter.cs
> Allow reading ids containing integers as strings

- src/GraphQL.Tests/Bugs/Bug1772.cs
- src/GraphQL.Tests/Bugs/Bug4078.cs
- src/GraphQL.Tests/Bugs/Issue4075.cs
- src/GraphQL.Tests/Bugs/Issue4077.cs
- src/GraphQL/Execution/DocumentExecuter.cs
Closes #4077 
Regression introduced in:
- #3870
> Bugfix: Treat operation name with empty string as null

- src/GraphQL.Tests/Bugs/Issue4086.cs
- src/GraphQL/Validation/DocumentValidator.ParseArgumentVisitor.cs
> Fix argument parsing for fields nested under union graph types

- README.md
> Remove dead facebook link

- .github/workflows/test-code.yml
- Tests.props
- samples/GraphQL.Federation.CodeFirst.Sample3/GraphQL.Federation.CodeFirst.Sample3.csproj
- samples/GraphQL.Federation.SchemaFirst.Sample1/GraphQL.Federation.SchemaFirst.Sample1.csproj
- samples/GraphQL.Federation.SchemaFirst.Sample2/GraphQL.Federation.SchemaFirst.Sample2.csproj
- samples/GraphQL.Federation.TypeFirst.Sample4/GraphQL.Federation.TypeFirst.Sample4.csproj
- Fix test scripts for federation samples
- Bump federation samples to .NET 8
- Disable .NET Core 3.1 testing on Linux
> Fix CI workflows

- src/GraphQL.Analyzers.Tests/InputGraphTypeAnalyzerTests.Fields.cs
- src/GraphQL.Analyzers/Helpers/Constants.cs
- src/GraphQL.Analyzers/InputGraphTypeAnalyzer.Fields.cs
> GQL006: don't report field with NoClrMapping

- src/GraphQL.Analyzers.Tests/InputGraphTypeAnalyzerTests.Fields.cs
- src/GraphQL.Analyzers/InputGraphTypeAnalyzer.Fields.cs
> GQL007 Handle struct implicit constructor

- docs2/site/docs/guides/serialization.md
Serialization documentation is out of date
See also:
- #4152
> Fix serialization documentation

- docs2/site/docs/migrations/migration9.md
- docs2/site/sitemap.yml
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
- src/GraphQL.Tests/Complexity/ComplexityTests.cs
- src/GraphQL/Execution/DocumentExecuter.cs
- src/GraphQL/Execution/ExecutionContext.cs
- src/GraphQL/Execution/ExecutionStrategy.cs
- src/GraphQL/Execution/IExecutionContext.cs
- src/GraphQL/Validation/DocumentValidator.ParseArgumentVisitor.cs
- src/GraphQL/Validation/FieldArgumentsValidationContext.cs
- src/GraphQL/Validation/IValidationResult.cs
- src/GraphQL/Validation/ValidationContext.cs
- src/GraphQL/Validation/ValidationResult.cs
Move from IReadOnlyDicrionary to IDictionary
and replaced Dictionary with ConcurrentDictionary 
check  [Related Issue](https://github.com/graphql-dotnet/graphql-dotnet/issues/4085)
> Use ConcurrentDictionary in ValidationContext #4085

- src/GraphQL.ApiTests/GraphQL.ApiTests.csproj
- src/GraphQL.ApiTests/GraphQL.DataLoader.approved.txt
- src/GraphQL.ApiTests/GraphQL.SystemTextJson.approved.txt
- src/GraphQL.ApiTests/net50/GraphQL.approved.txt
- src/GraphQL.ApiTests/net60/GraphQL.approved.txt
- src/GraphQL.ApiTests/netstandard20+netstandard21/GraphQL.approved.txt
> Bump PublicApiGenerator
